### ISSUE TITLE
Define a way to handle guides for features that are behind a feature flag.

### ISSUE THREAD

**Issue by abuiles** [emberjs/website#1054]
Currently the documentation for query-params by @alexspeller  has been waiting for merge for more than 2 months. This feature is being used by  a bunch of people who has discovered it mostly through IRC or comments on S.O

Discussing with @rjackson we came up to the conclusion that we need to establish a proper way to  handle guides for features which are behind feature flag. As Alex mention on the comments there 

> if the goal of flagged features is to get the community to test them before releasing, then no documentation for them hinders this

@rjackson point that the main issue would be  what to do with those  features that would change other guides.

As an initial proposal I would suggest having a section for "experimental features" where we compile documentation for all those features behind feature flags. 

We just merge additions to this section but not changes to other guides. Once the feature hits beta, then it can be moved to the right section and changes to other guides can be merged.

**Comment by trek** [comment]
I don't think we have the bandwidth for this currently. In the 2.x series feature authors will be required to submit to a beta features guide and will be required to audit and update guides before we merge their feature.
