### ISSUE TITLE
Legacy LoadingRoute example uses deprecated defaultContainer

### ISSUE THREAD

**Issue by lukegalea** [emberjs/website#1153]
The documentation at http://emberjs.com/guides/routing/loading-and-error-substates/#toc_legacy-code-loadingroute-code

suggests creating a view like this:

    Ember.View.create({
        templateName: 'global-loading',
        elementId: 'global-loading'
      }).append();

This triggers an error:

    Using the defaultContainer is no longer supported. [defaultContainer#lookup]

As per: https://gist.github.com/stefanpenner/5627411

What is the recommended way to append this view?

I was able to solve this like this:

application_view.js.coffee:

    App.ApplicationView = Em.View.extend
      templateName: 'application'

application.hbs:

    {{outlet}}

application_controller.js.coffee:

    App.ApplicationController = Em.Controller.extend
      isLoading: false

      actions:
        loading: ->
          return if @get('isLoading')

          @set 'isLoading', true

          applicationView = @container.lookup 'view:application'
          loadingView = applicationView.createChildView Em.View,
            templateName: 'loading'
            elementId: 'global-loading'
            controller: Em.Controller.create()
          loadingView.append()

          @router.one 'didTransition', =>
            @set 'isLoading', false
            loadingView.destroy()
        
The isLoading property is to prevent it from rendering multiple times if there are several routes nested that require a loading state. Otherwise we get multiple views at once.

Also, the empty controller is necessary or it breaks the Ember Inspector plugin (it looks up the controller for a view, so any view that doesn't contain a controller causes an exception)

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
