### ISSUE TITLE
Ember guides: "Creating and deleting records" has misleading usage examples.

### ISSUE THREAD

**Issue by michlord** [emberjs/website#1272]
Here: http://emberjs.com/guides/models/creating-and-deleting-records/
in the section "Deleting Records". It is correctly stated that to delete a record you call deleteRecord() on any instance of DS.Model. However in the example below there is a chance that it is called on a promise object. I would suggest changing the example to something like:
~~~
var post = store.find('post', 1).then(function(record){
    record.deleteRecord();
    record.get('isDeleted'); // => true
    record.save(); // => DELETE to /posts/1
});
~~~
Or we can state that we expect record to be already loaded on the store.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
