### ISSUE TITLE
Proper way to create an adaptor according to the guides.

### ISSUE THREAD

**Issue by lfalin** [emberjs/website#1275]
The docs currently show three different methods for creating adapters:

1. In the Getting Starting Guide's [Using Fixtures](http://emberjs.com/guides/getting-started/using-fixtures/) section, a Fixture Adapter is created by extending the Adapter class:

 ```
 Todos.ApplicationAdapter = DS.FixtureAdapter.extend();
 ```

2. In the [Adapter class documentation](http://emberjs.com/api/data/classes/DS.Adapter.html), they are created using DS.Store.create():

 ```
 App.store = DS.Store.create({
   adapter: 'MyAdapter'
 });
 ```
3. In the [Fixture Adapters Guide](http://emberjs.com/guides/models/the-fixture-adapter/), they're created using DS.Store.extend():

 ```
 App.Store = DS.Store.extend({
   revision: 13,
   adapter: DS.FixtureAdapter
 });
 ```

These all seem to work equally well, however option 1 relies on an [undocumented default value](https://github.com/emberjs/data/blob/v1.0.0-beta.6/packages/ember-data/lib/system/store.js#L1375) that isn't explained in the tutorial or elsewhere that I could find. Option 3 specifies a revision field which isn't explained and doesn't appear to be used. 

Is there a best practice for specifying adapters? I know I've submitted other documentation discrepancies, and I'm happy to fork/fix them, but as the API appears to be in a state of flux, I can't tell from the docs and code which is the correct method to use.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
