### ISSUE TITLE
Some Ember Data Documentaion/Guide Suggestions

### ISSUE THREAD

**Issue by rwjblue** [emberjs/website#1328]
- [ ] Document adapter `ajaxOptions` [see RESTAdapter's implementation](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest_adapter.js#L590-613)
- [x] Document adapter `headers` (will be used by `ajaxOptions` to build headers array)
- [ ] Custom inflection rules (likely just a mention in the FAQ)
- [ ] Guide describing the expected JSON format (this is partially covered but not super well).
- [ ] Adapter Customization Guide - Listing the main customization points (pathForType, host, narmespace, defaultSerializer)
- [ ] Serializer Customization Guide - Listing the main customization points (normalize, normalizeHash, keyForAttribute, etc). This is mostly just presenting the API doc information in the guides section.
- [ ] Section detailing various uses of `push`, `pushPayload`, and `createRecord`, how they are different, and when to use each.
- [ ] Add note about dynamic `headers` once Ember Data 1.0.0-beta.8 ships.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
