### ISSUE TITLE
Computed properties guide

### ISSUE THREAD

**Issue by perlun** [emberjs/website#1381]
Rerouting from emberjs/ember.js#4503, as requested:

[This page](http://emberjs.com/guides/object-model/computed-properties/) has some details which are hard to grasp:

> Ember will call the computed property for both setters and getters, so if you want to use a computed property as a setter, you'll need to check the number of arguments to determine whether it is being called as a getter or a setter. **Note that if a value is returned from the setter, it will be cached as the property’s value.**

What does this mean in reality? If I return `null`, will it be cached? Or `undefined`?

Perhaps a pointer to some other page describing this more in detail wouldn't be so bad there.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
