### ISSUE TITLE
Add multiple checkboxes selection recipe to the Cookbook 

### ISSUE THREAD

**Issue by taras** [emberjs/website#1384]
After some collaboration between @rjackson, @lindsey-s, @mixonic and myself on IRC. We came up with an example of how to show to show multiple checkboxes that allow selection without modifying the original models.

http://emberjs.jsbin.com/holem/1/edit

This should make its way into the cookbook.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
