### ISSUE TITLE
Runloop guide - testing

### ISSUE THREAD

**Issue by ckung** [emberjs/website#1390]
This following guide is great:
http://emberjs.com/guides/understanding-ember/run-loop/

However, a section about using the run loop during testing would be great. Sometimes ember-testing fails because I haven't wrapped app code timeouts in a run loop. And/or, when do I wrap test code in a run loop? I've found myself tangled in run loop gotchas during testing - so it'd be helpful to get a better understanding.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
