### ISSUE TITLE
YUIdoc data.json missing

### ISSUE THREAD

**Issue by mzgupta** [emberjs/website#1399]
When you generated YUI doc creates data.json,

example 
http://yuilibrary.com/yui/docs/api/data.json

But in case of ember.js , File does not exists
http://emberjs.com/api/data.json

Since In my project many of my objects extend Ember Objects. data.json helps to merge the ember.js documentation into my local yuidoc documentation.

**Comment by okuryu** [comment]
https://github.com/yui/yuidoc/issues/237 have been resolved in [YUIDoc v0.4.0](https://github.com/yui/yuidoc/releases/tag/v0.4.0). I bumped YUIDoc version of [ember-cli-yuidoc](https://github.com/cibernox/ember-cli-yuidoc/pull/9) and [Ember.js](https://github.com/emberjs/ember.js/pull/10327).

**Comment by michaelrkn** [comment]
Is this still an issue? cc @acorncom @locks since you two have been working on API docs related stuff recently

**Comment by acorncom** [comment]
Closing this due to it being so stale.  If it's still an issue that folks are having, please comment and we can re-open.
