### ISSUE TITLE
Loading/error substate guide flow is backwards

### ISSUE THREAD

**Issue by machty** [emberjs/website#1407]
Tomhuda pointed out to me that the [loading/error substate guide](https://github.com/emberjs/website/blob/master/source/guides/routing/loading-and-error-substates.md) has somewhat backward pedagogy; currently it goes into details about the `loading` and `error` events and mentions substates only after establishing these events, when it'd probably be more beneficial to just talk about substates up front and drop to the more low-level primitive towards the end.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
