### ISSUE TITLE
3rd party plugins / components / controls page

### ISSUE THREAD

**Issue by JulianLeviston** [emberjs/website#1410]
Heya,

Given that this kind of thing seems to surface once every month or so:
http://discuss.emberjs.com/t/controls-libraries-list-that-work-well-with-ember-js/4629/2
... perhaps it's a good idea to add a third party libraries / components / plugins / widgets section in the official ember documentation.

**Comment by trek** [comment]
I believe this morphed into http://www.emberaddons.com/
