### ISSUE TITLE
Testing Controllers - Providing data from Ember Data

### ISSUE THREAD

**Issue by ryanjm** [emberjs/website#1447]
I think the testing documentation could be improved by adding a section about how to properly provide ember data to the controllers.

Should the tests use Fixtures instead and `override the DS.FixtureAdapter::queryFixtures method to support querying the fixture store` OR is there a way to provide mock API calls and keep using the `RESTAdapter`?

What is the Ember way?

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
