### ISSUE TITLE
Ember Guides in pdf, epub and mobi

### ISSUE THREAD

**Issue by jahlomp** [emberjs/website#1480]
I have been working on making a book version of the Ember Guides at https://leanpub.com/emberjsguides

Please check it out.

**Comment by FractalizeR** [comment]
How actual is this book? Is it regularly updated? There is no publishing date there.

**Comment by JahlomP** [comment]
I have started another version due to the changes made to the original guides. https://leanpub.com/emberjsguidesv111

**Comment by FractalizeR** [comment]
Yep, I see, thanks. In the meantime I read it in Evernote, pulling all the pages into the notepad ;)
