### ISSUE TITLE
Reopening classes and instances is out of place

### ISSUE THREAD

**Issue by kalmanh** [emberjs/website#1506]
The "Reopening classes and instances" section of the guide should be moved up right after "Classes and Instances" section. Even if it doesn't end up there, it DEFINITELY should be in the middle of the whole explanation on computed properties, observers and bindings. Totally out of place and interrupts the flow.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
