### ISSUE TITLE
Thoughts on the landing guide for the Bloggr project

### ISSUE THREAD

**Issue by TrevorSayre** [emberjs/website#1513]
When a user first goes to learn about Ember.js from the official website, they might click on Guides and be presented with:
http://emberjs.com/guides/index.html
https://github.com/emberjs/website/blob/master/source/guides/index.md

The video does a good job explaining the concepts, but there are a few issues to be addressed.

The easiest thing to note is that the source code linked to on the page does not match what is shown in the video for a few key points. Also, the video tells the user to download the Starter Kit from the main site, but this Starter Kit does not marry well with the supplied answer source code. The details for this are covered in https://github.com/tildeio/bloggr-client/pull/11

Maybe that source code should be migrated to  the [website repo](https://github.com/emberjs/website/tree/master/source/guides)?

This guide also uses file:// as the method for learning and testing. This causes two issues that stand out to me:
  1. Ember.js is meant for building web applications, and file:// is not how you use the web.  
  1. [Hashbangs are considered bad form](http://danwebb.net/2011/5/28/it-is-about-the-hashbangs), and you can't implement HistoryLocation when using file:// as your "server."

I understand that it is important to keep things simple for a user. However, if the user is learning to develop web applications, they should have local testing as a foundation before approaching this guide. Maybe we can link to an existing guide? Maybe one needs to be made?

I also think it is important to help with best practices. The guide covers how to use a Router to allow loading data from a URI (e.g. /posts/2), so why not also help the user ditch hashbangs? Or why not at least set the user up to be able to learn about this within possibly their first encounter to hashbangs as a developer?

I think the TodoMVC is a great second project, but this Bloggr project is fantastic as an introductory guide. With some updating and rethinking, it could be even better.

**Comment by trek** [comment]
We no longer show the bloggr example on the guides. Thanks for the feedback.
