### ISSUE TITLE
Models FAQ talks on filters without explaining what filters are

### ISSUE THREAD

**Issue by lolmaus** [emberjs/website#1539]
https://github.com/emberjs/website/blob/master/source/guides/models/frequently-asked-questions.md

This article talks about queries vs filters. But it does not explain what filters are, and filters are never mentioned in the Models section of the guide.

I figured that "filters" mean the approach of retrieving all data into the frontend at once and accessing it with `this.store.find(model_name, item_id)` as opposed to querying `this.store.find(model_name, {item_property: item_value)`.

This should be explained. Also, the [Finding Records](http://emberjs.com/guides/models/finding-records/) subsection should use the same terminology.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
