### ISSUE TITLE
Can the ToDo tutorial made available in a single tutorial format?

### ISSUE THREAD

**Issue by dscyc0d3** [emberjs/website#1608]
I tried to follow through the ToDo tutorial (as a beginner), and 60% through, the cognitive load was immense (the different file structure, individual files) & confusion started, that I had to drop it. I checked out other tutorials, specifically this one - http://www.williamhart.info/an-emberjs-beginners-tutorial.html - which was easier to read and understand as a beginner. Can someone write the same tutorial but with with similar format? I absolutely think other beginners will certainly benefit from such an approach. And, I am not at all suggesting scraping the current one. Just another tutorial article for the same ToDo app.

**Comment by trek** [comment]
@dscyc0d3 glad you found a tutorial that was a better fit. Unfortunately it's not possible to create a single tutorial that fits everyone's background, experience, and learning style.
