### ISSUE TITLE
Misleading comment in observer documentation

### ISSUE THREAD

**Issue by nick-lehmann** [emberjs/website#1618]
While working through the ember.js guides, I found on the [documentation for observers](http://emberjs.com/guides/object-model/observers/#toc_observers-and-asynchrony) some code that confused me. 

```javascript
Person.reopen({
  lastNameChanged: function() {
    // The observer depends on lastName and so does fullName. Because observers
    // are synchronous, when this function is called the value of fullName is
    // not updated yet so this will log the old value of fullName
    console.log(this.get('fullName'));
  }.observes('lastName')
});
```

It says that the code will output the older version of fullName due to the synchronous nature of the observer. But it doesn't. When you try out this code in your browser you will get the updated version back. You can achieve the named behaviour by using `observesBefore()` instead of `observes()`. Also see [this stackoverflow question](http://stackoverflow.com/questions/24884925/observers-and-asynchrony-in-ember-js?noredirect=1#comment38661351_24884925).

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
