### ISSUE TITLE
Misleading console message order in Run-loop guide example

### ISSUE THREAD

**Issue by ctataryn** [emberjs/website#1663]
It has come be my understanding that Ember.run(..) will block until its queues have been flushed. However according to the console output depicted in the run-loop guide example it doesn't appear that way.

Given this example on the site:
```js
function logFour() {
  console.log('processing: task #4');
}

console.log('before Ember.run');
Ember.run(function(){
  Ember.run.schedule('actions', function task1(){
    console.log('processing: task #1');
  });
//...
  console.log('end of callback');
});

console.log('after Ember.run');
```
Actual output:
```
before Ember.run
end of callback
after Ember.run
processing: task #1
```

Expected output:
```
before Ember.run
end of callback
processing: task #1
after Ember.run
```

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
