### ISSUE TITLE
"Creating Reusable Social Share Buttons" doesn't work for dynamic data

### ISSUE THREAD

**Issue by acechase** [emberjs/website#1673]
I think this example is somewhat problematic because, as far as I can tell, it only works on initialization. Because takes the original a-tag properties and builds its own component out of them all the bindings are immediately lost. 

For instance, using the example code and then changing the bound "url" property one finds that the twitter button still points to the original URL.

Seems like there are a couple of paths:
 - I'm mistaken and doing something incorrectly... seems unlikely :)
 - There's a way to re-engineer this component to make it work with twitter's approach to replacing the original HTML with their own.
 - We update the cookbook page to note this shortcoming (and possibly suggest a hack to work around it).

I'd be happy to do the leg work of building a PR for this, but wanted to see if maybe I was missing something.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
