### ISSUE TITLE
Typeahead-style search results are incorrect.

### ISSUE THREAD

**Issue by richardkmichael** [emberjs/website#1682]
http://emberjs.com/api

In the top-menu bar search widget, type `outlet`; the typeahead-style dropdown offers `Ember.js - Ember.Handlebars.helpers` as the first result; follow/select it.

On the [resulting page](http://emberjs.com/api/classes/Ember.Handlebars.helpers.html#sts=outlet) there is no mention of `outlet` as a helper, nor does the string 'outlet' occur at all (using the browser's "find on page").  Flipping between the Index and Methods tabs and enabling all options: inherited, protected, private, deprecated doesn't reveal any new content related to `outlet`.

(The second type-ahead result relates to `Ember.Route`, and that page does include `disconnectOutlet`.)

I'm sure I'm embarrassing myself.. but what have I missed?  (Where is the documentation for the `{{outlet}}` helper?)

**Comment by trek** [comment]
Not sure if this was momentary? The word outlet does indeed appear on the page you linked.
