### ISSUE TITLE
Unnecessary return from `didTransition` event handler in GA cookbook?

### ISSUE THREAD

**Issue by machty** [emberjs/website#1693]
Looking at https://github.com/emberjs/website/commits/master/source/guides/cookbook/helpers_and_components/adding_google_analytics_tracking.md

Is the `return` necessary in `return ga(...)`? It suggests that the return value is meaningful, possibly promise-aware. If it doesn't do anything then we should probably remove it. 

/cc @tmcgilchrist

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
