### ISSUE TITLE
GUIDE : var meta = result.get("content.meta"); to get the metadata seems incorrect.

### ISSUE THREAD

**Issue by synthresin** [emberjs/website#1697]
Guide says to use ``var meta = result.get("content.meta");``to get the metadata for a query.
but It seems ``var meta = result.get("meta");`` is to be used to make it work.

Maybe It's documentation issue? I'm using Ember: 1.7.1+pre.f095a455 and Ember Data : 1.0.0-beta.9

**Comment by trek** [comment]
Closed due to missing follow-up from OP.
