### ISSUE TITLE
Update Needs API documentation with examples of naming conventions for different levels of route nesting

### ISSUE THREAD

**Issue by ultimatemonty** [emberjs/website#1734]
I think the `needs` API docs need to be updated to have examples of different naming conventions depending on route structure/nesting.

[This test](https://github.com/emberjs/ember.js/blob/4445be038bd839a1559020db5677b211dd3f1e9c/packages/ember-application/tests/system/dependency_injection/normalization_test.js#L18) has examples that are perfect and is where I found the solution to [an issue](http://discuss.emberjs.com/t/accessing-another-controllers-model-from-a-routeless-controller/6461) I ran into in one my projects.

Would like to submit a PR but wanted to get buy-off/approval first.

**Comment by trek** [comment]
`needs` won't be long for this world as we move away from controllers, but thanks for checking on on this.
