### ISSUE TITLE
Broken JSBin examples

### ISSUE THREAD

**Issue by kgish** [emberjs/website#1750]
I noticed that the jsbin examples at the bottom of the Getting Started Guide Query Parameters do not seem to be working.

http://emberjs.com/guides/routing/query-params/

This is one particular example, but I believe that there are a number of such examples broken in other chapters.

**Comment by tuhtah** [comment]
All JSBin examples for the *Testing* section would also currently need the handlebars 2.0.0 treatment.

I found the following affected pages:
* http://emberjs.com/guides/testing/test-helpers/
* http://emberjs.com/guides/testing/testing-user-interaction/
* http://emberjs.com/guides/testing/unit-testing-basics/
* http://emberjs.com/guides/testing/testing-components/
* http://emberjs.com/guides/testing/testing-controllers/
* http://emberjs.com/guides/testing/testing-routes/
* http://emberjs.com/guides/testing/testing-models/

Hmm, maybe it would be more economical to rather sync with the upcoming 1.10 HTMLBars enabled release and revisit all JSBin examples for HTMLBars usage while at it?

**Comment by tuhtah** [comment]
Please, ignore my previous comment. A fix for the handlebars issue in the testing section has already been commited: #1881, #1944

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides and no longer user JSbin.
