### ISSUE TITLE
Clarify sentence in Models: The Rest Adapter > JSON Root

### ISSUE THREAD

**Issue by davidtheclark** [emberjs/website#1755]
I came across this sentence at [JSON Root in the Models guide](http://emberjs.com/guides/models/the-rest-adapter/#toc_json-root):

> Note: Although after destroyRecord or deleteRecord/save the adapter expects an empty object e.g. {} to be returned from the server after destroying a record.

... And I don't think it fits the clarity of the rest of the documentation I've been reading. It's downright confusing.

I would have submitted a pull request with a simple change but I'm not entirely sure what it's *supposed* to say, as I'm reading this for the first time to learn.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
