### ISSUE TITLE
Bindings example does not work

### ISSUE THREAD

**Issue by codematix** [emberjs/website#1759]
The two-way bindings example @ [http://emberjs.com/guides/object-model/bindings/](http://emberjs.com/guides/object-model/bindings/) does not work.

Here is a JSBin for this - http://jsbin.com/guwoxi/3/edit?html,js,console

Am I missing something or are they broken?

Below are the versions of libraries I am using:
- jQuery - 2.1.1
- Handlebars - 1.1.2
- Ember.js -  1.7.1

**Comment by trek** [comment]
I think @barelyknown addressed this.
