### ISSUE TITLE
New cookbook: Authentication

### ISSUE THREAD

**Issue by alexspeller** [emberjs/website#1796]
Basic authentication could use a cookbook

@locks @krzkrzkrz

https://gist.github.com/alexspeller/4a4041f62215c78c201b

**Comment by RyannosaurusRex** [comment]
Yea, auth is really big and really hard for folks to get right starting out and generally people get it wrong (including me if I'm not careful).  I think even a curated list of "blessed" libraries would be helpful for people getting started, even with a disclaimer that these are outside the scope of the Ember project.

**Comment by kgish** [comment]
I played around a bit on my own with authentication and was very intrigued by all the great effort that has been done put in `simple-auth` as well as the documentation there.

Then again if you have a simple plain-vanilla app you want to get up and running quickly, some shortcuts could be nice.

Authentication can be a bit detailed and covers a wide area, so for myself I wrote a short high-level blurb in case anyone is interested:

https://github.com/kgish/ember-hal-client#authentication-and-how-it-works

**Comment by trek** [comment]
> Authentication is a huge problem space. I can't imagine an Ember guide could cover it well.

Agreed. This is more suited to a larger article.

**Comment by knownasilya** [comment]
Sounds good, I'll write it up as a blog post.
