### ISSUE TITLE
Early upgrade tips

### ISSUE THREAD

**Issue by samselikoff** [emberjs/website#1819]
Many folks found [this gist](https://gist.github.com/samselikoff/1d7300ce59d216fdaf97) I wrote helpful, and we were wondering if it should make it into the guides somewhere. That way it could stay updated + be more available.

Any interest in this, and if so, where? I was thinking another section under "Deprecations" called something like "From 1.x to 2.0".

**Comment by trek** [comment]
We'll communicate the migration paths as they become available. Many things cannot change until their replacement lands in 1.x
