### ISSUE TITLE
Validity errors when staging and building

### ISSUE THREAD

**Issue by wifelette** [emberjs/website#1822]
![2014-11-17_13-50-13](https://cloud.githubusercontent.com/assets/25433/5078321/a8b59f02-6e60-11e4-98c9-26ce5f34f942.png)

Lots of these, all under `toc_` IDs (screenshot is a small section). It all builds fine anyway, but flagging this because I'm pretty sure it's new. Something to fix? Pardon the noob :p

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
