### ISSUE TITLE
Raw markdown in some elements

### ISSUE THREAD

**Issue by huonw** [emberjs/website#1836]
E.g. [the top of "Defining a Component"](http://emberjs.com/guides/components/defining-a-component/) is rendered as:

>  \*\*Note:** Components must have a dash in their name. So \`blog-post\` is an acceptable name, but `post` is not. This prevents clashes with current or future HTML element names, and ensures Ember picks up the components automatically. 

And, [the last thing on "Customizing a Component's Element"](http://emberjs.com/guides/components/customizing-a-components-element/#toc_example) is rendered as

>  \*\*Note:** The binding functionality in this very simple example could also be implemented without the use of \`Ember.Component\` but by simply \[binding element attributes](/guides/templates/binding-element-attributes) or \[binding element class names](/guides/templates/binding-element-class-names). 

Presumably the markdown inside these `<aside>` elements is expecting to be processed into HTML.

(Migrated from https://github.com/emberjs/ember.js/issues/9671.)

**Comment by trek** [comment]
This appears to have been fixed.
