### ISSUE TITLE
Add information about validating and persisting models in a backend

### ISSUE THREAD

**Issue by ohcibi** [emberjs/website#1840]
The docs for 'creating and deleting records' are only explaining how to create a record with `store#createdRecord` directly in the store and then saving it with `model#save`. This makes little sense for a server backed model because:

* the process can fail because of network issues
* the process can fail because of validation issues
* the process can fail because of "some" reason

Please add information on how to deal with such models and the above issues.

**Comment by trek** [comment]
This will vary depending on your server environment of choice, so sadly not a topic we can cover well.

**Comment by ohcibi** [comment]
I'm not sure anymore what was actually disturbing me back then, but I guess I was distracted somehow by "Persisting Records" not being the immediate follower of "creating and deleting", I guess I wasn't 100% promise aware back then.

I'd propse to make "pushing records into the store" a subsection of "creating and deleting records" - maybe renaming it to something like "Add and remove records from the store", plus add a literal hint that persisting those records with success and failure treatment is covered in the next section..

I'll create a PR, if this sounds worth the effort to the core team.?
