### ISSUE TITLE
Add examples of using fixtures with associations

### ISSUE THREAD

**Issue by daniely** [emberjs/website#1853]
The current [fixture guide](http://emberjs.com/guides/models/the-fixture-adapter/) is pretty good but doesn't have any information on how to handle models with associations. I would gladly submit a PR but first wanted to make sure you guys want it.

A simple yes or no will do :)

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
