### ISSUE TITLE
Make emberjs.com responsive

### ISSUE THREAD

**Issue by mnquintana** [emberjs/website#1876]
I found myself browsing Ember docs today on my phone while traveling, and discovered that [Ember's website](http://emberjs.com) isn't currently responsive. It would be pretty fantastic if we could make the current design responsive so you can easily browse documentation no matter what device you're on. :smiley: 

(I'd be willing to contribute to this too!)

**Comment by gregone** [comment]
I'm also willing to help with this.

**Comment by tomdale** [comment]
This is definitely something we're interested in. We're in the middle of a revamp of the guides portion of the site and I'll make sure we make it mobile-friendly. I don't really want to crowdsource a major redesign, but I would be happy for PRs that make small tweaks to enhance readability on small screens.

**Comment by trek** [comment]
A company has volunteered to do a visual refresh for us. We've added making the site responsive as a requirement.

**Comment by jbrown** [comment]
@trek Just curious, which company?
