### ISSUE TITLE
Naming conventions | Dynamic Segments : route versus resource

### ISSUE THREAD

**Issue by kgish** [emberjs/website#1885]
In the section about dynamic segments you refer to a `route` using dynamic segments and then use a `resource` in the code sample without explaining the difference.

Then the `route's` name is `post`

This is a little confusing and could be improved with a short blurb and/or reference.

Reference: http://emberjs.com/guides/concepts/naming-conventions/#toc_dynamic-segments

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
