### ISSUE TITLE
Reopening classes and instances

### ISSUE THREAD

**Issue by kgish** [emberjs/website#1886]
The section about `reopen` and `reopenClass` is slightly confusing, and could be improved by adding an example or two in order to illustrate these concepts a bit more clearly.

Reference: http://emberjs.com/guides/object-model/reopening-classes-and-instances/

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
