### ISSUE TITLE
Fix Focus Textfield cookbook.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/website#1887]
The cookbook incorrectly indicates that you can have child elements inside of an `<input>` tag. This accidentally worked in Handlebars versions of Ember because the browser auto-corrected the contents to be outside the input element. In HTMLBars we do not rely on the browser auto-correcting behavior as we create the elements (including child elements) directly.

https://github.com/emberjs/website/blob/618e7ba8d55912b433fe69bcd4b62c18547e0282/source/guides/cookbook/user_interface_and_interaction/focusing_a_textfield_after_its_been_inserted.md

Brought up in https://github.com/emberjs/ember.js/issues/9992.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
