### ISSUE TITLE
Loading and error substates

### ISSUE THREAD

**Issue by kgish** [emberjs/website#1889]
http://emberjs.com/guides/routing/loading-and-error-substates/

Mentioned that `ArticlesOverviewRoute#model` will look for `ArticlesErrorRoute ...` but won't it first look in `ArticlesOverviewErrorRoute` ?

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
