### ISSUE TITLE
How to use two adapter(LS and Rest adapter) to a model(Foo - ModelName), but route based access/use the adapter in ember.js application?

### ISSUE THREAD

**Issue by Arunachalam** [emberjs/website#1891]
Hi Guys,

When I use the LS adapter to Foo model in first page, I defined/mentioned the DS.LSAdapter to that Foo model and get the model data from database to the local storage. after I can access/manage the model data using by local storage adapter in the first page. It is working fine here.

Next I will navigate to second page and this page model is defined/mentioned the Rest Adapter for Foo same model. Ember does not make REST API call here, because the problem is first LS adapter initiated in the first page and this second page is not initiate the REST adapter for that Foo model. How do we initiate the rest the adapter to Foo model in second page without page refresh?

Please you give the solution to fix it. Thank you so much.

**Model**

    App.Foo = DS.Model.extend({     
    id: DS.attr('id'),     
    name: DS.attr('string')    
    });

**Mention the Local Storage Adapter in first page**

**Controller**

    App.FirstPageController = Ember.ObjectController.extend({
    
    });

**Route**

    App.FirstPageRoute = Ember.Route.extend({ 
          
        model: function() {  
    
    		App.FooAdapter = DS.LSAdapter.extend({ namespace: 'ls-emberjs' });
    
            return this.store.find('foo');       
    
        }   
    
    });
   
 **Hbs**

    <ul>
    {{#each model}} 
    	<li>fooID: {{id}} - Name: {{name}}</li>
    {{/each}}
    </ul>

**Mention the Rest Adapter in second page**

**Controller**

    App.SecondPageController = Ember.ObjectController.extend({
    
    });

  **Route**

    App.SecondPageRoute = Ember.Route.extend({  
         
        model: function() {  
    
    		App.FooAdapter = DS.RESTAdapter.extend({});
    
            return this.store.find('foo');       
    
        }   
    
    });

**Hbs**

    <ul>
    {{#each model}} 
    	<li>fooID: {{id}} - Name: {{name}}</li>
    {{/each}}
    </ul>

Thank you.

**Comment by trek** [comment]
StackOverflow is a better venue for getting help when you're having trouble. We use Issues just report bugs. Thanks!
