### ISSUE TITLE
Add a note to the models faq about how to reset values with store.push

### ISSUE THREAD

**Issue by bmac** [emberjs/website#1902]
This use to be the default behavior but it was changed in `v1.0.0-beta.14.1`

#### Model FAQ page
http://emberjs.com/guides/models/frequently-asked-questions/

#### Change log entry describing how to reset values with store.push 
https://github.com/emberjs/data/blob/master/CHANGELOG.md#storeupdate-has-been-deprecated

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
