### ISSUE TITLE
Remove usage of Ember.ObjectController

### ISSUE THREAD

**Issue by rwjblue** [emberjs/website#1908]
This will be deprecated in 1.11, so we should update the guides to ensure folks starting out today do not have to change their apps when 1.11 comes out.

**Comment by fivetanley** [comment]
Do we want to remove usage of ArrayController as well?

**Comment by rwjblue** [comment]
Yes, but I am not quite done with the deprecation (still shooting for 1.11 though).

**Comment by indirect** [comment]
Is there an existing guide for migrating from ObjectController or ArrayController?

**Comment by trek** [comment]
We've migrated to a versioned guides project. Please reopen on https://github.com/emberjs/guides. Thanks!
