### ISSUE TITLE
Todo Tutorial - Toggling between Showing and Editing States

### ISSUE THREAD

**Issue by aek82** [emberjs/website#1911]
Doesn't work. Every time I double click on an item to edit, I get the error: "The action 'editTodo' did not exist on todos" in firebug.

I'm completely new to emberjs, so not sure how to fix or have any suggestions. Tried googling and stackoverflow, but just got even more confusing answers from previous versions of the tutorial.

**Comment by trek** [comment]
Did you check your application against the sample application? Likely you've just missed a step or have a typo somewhere.
