### ISSUE TITLE
Todo Tutorial - "Marking a Model as Complete or Incomplete" section does not work 

### ISSUE THREAD

**Issue by aek82** [emberjs/website#1912]
This snippet in the html template adds `itemController ="todos" attribute` and it ends up breaking the template.

`
 <ul id="todo-list">
                {{#each todo in model itemcontroller="todos"}}
                <li {{bind-attr class="todo.isCompleted:completed todo.isEditing:editing"}}>
                    {{#if todo.isEditing}}
                        <input class="edit">
                    {{else}}
                    {{input type="checkbox" checked=todo.isCompleted class="toggle"}}
                    <label {{action "editTodo" on="doubleClick"}}>{{todo.title}}</label><button class="destroy"></button>
                    {{/if}}
                </li>
                {{/each}}
            </ul>
`

If I remove it, the example works. Fixing this required me to remove the "_controller" suffix from the todos file name. Why is that?

**Comment by trek** [comment]
StackOverflow is a great place for questions if you're having trouble with tutorial.

**Comment by crazyboy867** [comment]
im having the same problem....any solutions?
