### ISSUE TITLE
Update tutorial doc to use ember-cli structure

### ISSUE THREAD

**Issue by nichoth** [emberjs/website#1935]
The tutorial feels old. I would not recommend starting any application with the `window.namespace` pattern. Ember is targeting ambitious web applications, and this pattern is too simple. Ember CLI should be the convention for app structure. Is this idea good, bad, or doesn't matter?

**Comment by cquillen2003** [comment]
+1

**Comment by trek** [comment]
That is the plan! This is widely discussed in a bunch of other issues.
