### ISSUE TITLE
Logging issue

### ISSUE THREAD

**Issue by novtor** [emberjs/website#1938]
Ember v 1.9.1. ember-data v 1.0.0-beta.14
When server error occures there are two wiered logs appear in console.

1. 'Undefined'
Stacktrace:
RSVP.onerrorDefault() ember.js:29488
__exports__.default.trigger() ember.js:48661
Promise.prototype._onerror() ember.js:49673
publishRejection() ember.js:47904
<anonyme> ember.js:29462
Queue.prototype.invoke() ember.js:848
Queue.prototype.flush() ember.js:913
DeferredActionQueues.prototype.flush() ember.js:718
Backburner.prototype.end() ember.js:143
Backburner.prototype.run() ember.js:198
run() ember.js:17905
ember$data$lib$adapters$rest_adapter$$default<.ajax/</hash.error() ember-data.js:1532
jQuery.Callbacks/fire() jquery.js:3094
jQuery.Callbacks/self.fireWith() jquery.js:3206
done() jquery.js:8261
.send/callback/<() jquery.js:8600

2. Error: Assertion Failed: [object Object]
No stacktrace available. Code ember.js:13749:

    function EmberError() {
--->      var tmp = Error.apply(this, arguments);

      // Adds a `stack` property to the given error object that will yield the
      // stack trace at the time captureStackTrace was called.
      // When collecting the stack trace all frames above the topmost call
      // to this function, including that call, will be left out of the
      // stack trace.
      // This is useful because we can hide Ember implementation details
      // that are not very helpful for the user.
      if (Error.captureStackTrace) {
        Error.captureStackTrace(this, Ember.Error);
      }
      // Unfortunately errors are not enumerable in Chrome (at least), so `for prop in tmp` doesn't work.
      for (var idx = 0; idx < errorProps.length; idx++) {
        this[errorProps[idx]] = tmp[errorProps[idx]];
      }
    }

**Comment by trek** [comment]
This is probably better suited for an Issue on the project repo instead of the website.
