### ISSUE TITLE
Differences between code Getting Started and the quickstart-code-sample project

### ISSUE THREAD

**Issue by IanWhitney** [emberjs/website#1939]
Starting at [the Displaying Model Step](http://emberjs.com/guides/getting-started/displaying-model-data/) of the Getting Started guide, the code diverges from what's in the Quickstart Code Sample repo, which the guide links to.

The code sample on the page is:

```
  {{#each todo in model}}
    <li>
      <input type="checkbox" class="toggle">
      <label>{{todo.title}}</label><button class="destroy"></button>
    </li>
  {{/each}}
```
But the [git diff that this page in the guide links to](https://github.com/emberjs/quickstart-code-sample/commit/87bd57700110d9dd0b351c4d4855edf90baac3a8) has different code:

```
{{#each}}
<li>
  <input type="checkbox" class="toggle">
  <label>{{title}}</label><button class="destroy"></button>
</li>
{{/each}}
```

Code samples on later pages of the Guide continue to use the `{{#each todo in model}}` approach, while the commits continue to use the `{{#each}}` approach.

Until you reach the [Deleting a Model](http://emberjs.com/guides/getting-started/deleting-todos/) page and the code samples unexpectedly switch to use the `{{#each}}` approach and the app suddenly stops working (assuming the user, like me, was following along with the code samples.)

I was going to do a Pull Request for this, but I don't know which code style should be in the guide.

**Comment by trek** [comment]
The existing GSG is being dropped but thank you for the feedback.
