### ISSUE TITLE
"Using Fixtures" guide needs clarification on finding

### ISSUE THREAD

**Issue by ryanmurakami** [emberjs/website#1943]
In the ["Using Fixtures"](http://emberjs.com/guides/models/the-fixture-adapter/) guide, it states that after configuring a FixtureAdapter you can use `"all of methods for Finding Records"`. In fact, FixtureAdapters restrict the developer to only finding by id. Any finding by property or other such "queries" are unavailable until the developer has overridden the `queryFixtures` method on FixtureAdapter.

Here is an example of a failing find by property with a FixtureAdapter:
http://emberjs.jsbin.com/budiyusono/1/

I would suggest either revising the wording or adding a caveat/example about the `queryFixtures` method. If someone has a recommendation either way, I would be happy to submit a pull request.

**Comment by trek** [comment]
The existing GSG is being dropped but thank you for the feedback.
