### ISSUE TITLE
clarify usage the difference between 'model' and 'controller'

### ISSUE THREAD

**Issue by qbolec** [emberjs/website#1945]
At http://emberjs.com/guides/getting-started/displaying-model-data/ you can read:
>The template loops over the content of its controller.

 even though in the code you see:
```
 {{#each todo in model}}
```
As a person recently exposed to Ember, trying to grasp its point of view of reality I would welcome any clearfication in the tutorial I could get here, as I am totally confused now.

**Comment by teddyzeenny** [comment]
This sentence is explaining old code that has been changed since.  Is this [new explanation] (https://github.com/emberjs/website/pull/1946) better?

**Comment by qbolec** [comment]
Yes, now is much better.
I also found the site http://emberjs.com/guides/controllers/ quite helpful in understanding why model and controller can be used interchangably in this code example - perhaps linking to this site could help others as well.

**Comment by teddyzeenny** [comment]
Proxying behavior will be deprecated in the coming Ember.js versions, that's why it's been removed from the code examples.  This means using `model` will be the only option.

**Comment by qbolec** [comment]
Hm..that's interesting - having some experience with Backbone's, I was judging the proxying behaviour as a nice feature saving a lot of tideous work. I'll have to look into your reasoning behind this decision, as it had to be very inspiring:)
