### ISSUE TITLE
Clarify how automatic updates of collections work

### ISSUE THREAD

**Issue by qbolec** [emberjs/website#1948]
At page:
http://emberjs.com/guides/getting-started/show-only-incomplete-todos/
suggested implementation for the `model` function is:
```
    return this.store.filter('todo', function(todo) {
      return !todo.get('isCompleted');
    });
```
what I've tried instead was to combine two things I've learned in previous steps of the very same tutorial and I wrote:
```
    return this.modelFor('todos').filterBy('isCompleted',false);
```
for some reason this only "works" until I change a state of isCompleted of a Todo - the filter is not reexecuted.
As this obviously mean that this framework is performing some magic behind the scenes in the case of the first solution it would be very helpful to know what are the limits of this magic.
I suspect that .filter method of the data store returns a "live collection" while .filterBy of the other class does not.
As someone new to the framework I have now way of knowing which expressions will autoupdate and which not.
Perhaps a link (in the links section at the bottom) so a place which summarizes this differences could help.

**Comment by trek** [comment]
The existing GSG is being dropped but thank you for the feedback.
