### ISSUE TITLE
Clarify semantic of unused arguments key,value for allAreDone

### ISSUE THREAD

**Issue by qbolec** [emberjs/website#1949]
At http://emberjs.com/guides/getting-started/show-when-all-todos-are-complete/
the proposed implementation of allAreDone is:
```
allAreDone: function(key, value) {
  return !!this.get('length') && this.isEvery('isCompleted');
}.property('@each.isCompleted')
```
which does not use `key` nor `value`, so I thought it is safe to remove them.
It turns out that if I do that, then clicking the checkbox (actually clicking the "arrows") manually makes the app angry and it no longer responds to isCompleted changes.
I suspect that somewhere behind the scenes the function.length is checked to see what is the number of arguments of allAreDone to see if it handles `set` - if this is true, then it would be helpful to me if someone explained this in this example.

**Comment by trek** [comment]
The existing GSG is being dropped but thank you for the feedback.
