### ISSUE TITLE
Clarify how adapter knows that plural form of "person" is "people"

### ISSUE THREAD

**Issue by qbolec** [emberjs/website#1952]
In http://emberjs.com/guides/models/customizing-adapters/ there is a paragraph that says:

```
App.ApplicationAdapter = DS.RESTAdapter.extend({
  namespace: 'api/1'
});
```

>Requests for App.Person would now target /api/1/people/1.

While I can see how "api/1" gots interpreted, I have no idea how it works that Person maps to "people" :(

**Comment by trek** [comment]
Guides are intended to be focused and targeted. The API docs show how ember data inflects strings.
