### ISSUE TITLE
Routing and active handlers can change

### ISSUE THREAD

**Issue by kgish** [emberjs/website#1957]
In the chapter [Routing - Introduction](http://emberjs.com/guides/routing/) you indicate that the "active handlers can change for one of two reasons."

Not sure if it's also important to know, but other ways that active handlers can change or be instigated would be:

* via an external bookmark link
* refreshing the page
* typing in another url directly in the browser

I guess that what it boils down to is that one may take a snapshot of a given application state by saving the current location and state, emailing the url to another person, and having that person click on the link to re-create the application located at the same place and in the same state.

For me this is the ultimate test of the whole URI concept which forms the basis of Internet.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
