### ISSUE TITLE
Customizing a Component's Element

### ISSUE THREAD

**Issue by kgish** [emberjs/website#1969]
In the section [Customizing the Element](http://emberjs.com/guides/components/customizing-a-components-element/#toc_customizing-the-element), you show the `tagName: 'nav'` property as well as the `templates/components/navigation-bar` listing (shouldn't that be `app/templates/components/navigation-bar.hbs` by the way?) but nothing afterwards.

Wouldn't it be better to include an example (as above) of the generated HTML?

```
<nav id="ember180" class="ember-view">
  ...
</nav>
```

**Comment by trek** [comment]
This is addressed in the new versioned guides repo. Thanks!
