### ISSUE TITLE
Naming convention for handlebar templates

### ISSUE THREAD

**Issue by kgish** [emberjs/website#1970]
I noticed that there's an inconsistent naming convention for handlebar template extensions, sometimes `.hbs` is used and other times `.handlebars`.

For the sake of avoiding confusion, I'd recommend going for the `.hbs` as this seems to be the most widely used.

At the beginning of the section on Handlebars, one could write a small blurb explaining this choice.

Also some code examples use `templates/path/to/name` when I'd prefer `app/templates/path/to/name.hbs`

Sorry for being a stickler, but even small improvements are worthwhile I hope.

Keep up the great work.

**Comment by trek** [comment]
This is addressed in the versioned guides changes. Thanks for pointing it out!
