### ISSUE TITLE
API docs for Ember Data don't show inherited things from Ember project

### ISSUE THREAD

**Issue by ismyrnow** [emberjs/website#1971]
When viewing the Ember Data project API, if a class extends one in the Ember project, those inherited methods don't show up in the Index tab of the documentation.

For example: http://emberjs.com/api/data/classes/DS.RecordArray.html

I would expect to see all of the methods from here: http://emberjs.com/api/classes/Ember.ArrayProxy.html

Even the names of the classes in the Ember project (e.g. Extends: X, Uses: X) aren't clickable links.

**Comment by knownasilya** [comment]
This issue might be addressed as part of #1855, @trek can you confirm/deny?

**Comment by trek** [comment]
I don't think it will be, this is just how YUIDoc handles external dependencies. You can supply an external YUIDoc json file for linking to other dependancies, but that doesn't address the fact that dependencies are expressed as ranges, and different versions of dependencies might have different features. 

So, to @ismyrnow's example, if you're looking at `DS.RecordArray` and it extends `ArrayProxy`, which version of `ArrayProxy`'s API documentation would we point to? 1.0? 1.1... 1.10?

**Comment by wifelette** [comment]
Thanks so much for this. Alas, wrong repo, at least by now :p If this is still an issue, it belongs here: https://github.com/emberjs/ember.js/issues
