### ISSUE TITLE
No integration test helpers available in component tests

### ISSUE THREAD

**Issue by ohcibi** [emberjs/website#1976]
In http://emberjs.com/guides/testing/testing-components/#toc_interacting-with-components-in-the-dom it is stated that integration test helpers are available in components tests, which is not true as one hast to `App.injectTestHelpers()`, however there is no `App` in unit tests by default (which makes sense for unit tests)

**Comment by trek** [comment]
Are you using ember-cli or the just the globals form without cli?

**Comment by ohcibi** [comment]
I'm using ember-cli, but there shouldn't be an instance of `App` either? When creating new helpers, they are also only available (if not imported manually) when `App.injectTestHelpers()` is called, which is even described in the API: http://emberjs.com/api/classes/Ember.Test.html#method_registerHelper

So it appears to me that test helpers (the ones registered with `registerHelper` or `registerAsyncHelper` are a thing only for integration tests but not for unit tests, which should be made clear in the docs; currently this goes for built in test helpers as well.

**Comment by trek** [comment]
In the globals build, your application is available globally. The guides usually refer to this as `App`, but it could be any global variable (`window.Whatever`). We are in the process of updating the guides to reflect ember-cli usage.
