### ISSUE TITLE
Update /builds/ site to include ember template compiler in list of builds.

### ISSUE THREAD

**Issue by fivetanley** [emberjs/website#1998]
Reopened https://github.com/emberjs/ember.js/issues/10419 here thanks to @SlexAxton pointing it out.

**Comment by SlexAxton** [comment]
Thanks!

**Comment by mixonic** [comment]
The "builds" page should also list the template compiler file.

**Comment by ryanmurakami** [comment]
I'm working on this. It looks like two things happened, the ember-template-compiler.js needs to be included and the ember-qunit-builds was upgraded to 2.0+, causing some globals to not exist.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!

**Comment by rwjblue** [comment]
This is an issue for the builds site, not guides reopening...

**Comment by rwjblue** [comment]
Updated title, basically we need to update the `/builds/` app to include the template compiler in the list of builds shown in the various locations.

**Comment by ryanmurakami** [comment]
Was looking at this before, but couldn't find where in the app to add it. If you can point me in the right direction, I can take care of it!

**Comment by rwjblue** [comment]
I started looking at what needed to be done for this, and ended up just submitting a pull request.  Thanks for being willing to tackle this!  Sorry for the run around on it...

**Comment by ryanmurakami** [comment]
no problem!
