### ISSUE TITLE
deleteRecord() example not working on tutorial

### ISSUE THREAD

**Issue by nlhkabu** [emberjs/website#2009]
I've been going through the tutorial and noticed that the code for deleting a todo is not working:
This is the page: http://emberjs.com/guides/getting-started/accepting-edits/
It also doesn't work on the JS Bin demo: http://jsbin.com/gureki/1/edit?html,output

**Comment by stebru** [comment]
Shouldn't it work in the next step? http://emberjs.com/guides/getting-started/deleting-todos/
