### ISSUE TITLE
Back/forward buttons are broken in Ember guides when using Firefox

### ISSUE THREAD

**Issue by jamesshore** [emberjs/website#2029]
The back and forward buttons don't work properly in Firefox when browsing the Ember guides.

## To reproduce:

1. Open Firefox
2. Go to http://emberjs.com/guides/getting-started/planning-the-application/
3. Scroll to the bottom of the page and click the "Creating a Static Mockup" (next section) link.
4. Click the back button. Observe that you remain on the Getting Started page, but the forward button has now appeared.
5. Click the back button again. Observe that you are taken back one page, but the forward button has now disappeared.

## Observed (incorrect) behavior:

Clicking the back button on the "Creating a Static Mockup" page doesn't change pages the first time you click it, but Firefox's "forward" button appears. The second time you click it, you are taken back to the "Planning the Application" page, but the forward button disappears. (Note: in some cases, the forward button doesn't disappear. I'm not sure what exact circumstances are needed to make it disappear.)

## Expected (correct) behavior:

Clicking the back button on the "Creating a Static Mockup" page should take you back to the "Planning the Application" page, and enable Firefox's forward button. Clicking the forward button should return you to the "Creating a Static Mockup" page.

## Versions

Reproduced in Firefox 35.0.1 on Mac OS X 10.10.2.

Tested in Google Chrome 40.0.2214.115 (64-bit) on Mac OS X 10.10.2. Problem does not occur.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides and no long use JSBin.
