### ISSUE TITLE
"Quick Copy" buttons on release pages do not work on Firefox

### ISSUE THREAD

**Issue by jamesshore** [emberjs/website#2031]
The "Quick Copy" buttons at http://emberjs.com/builds/#/release (and other release channels too) don't work on Firefox. When the button is clicked, nothing happens, and nothing is copied to the clipboard. Also, the mouse pointer doesn't change to the 'pointing hand' icon.

On Chrome, the button works correctly. When it's clicked, a "flip over" animation occurs revealing the words "Copied." A link or tag is copied to the clipboard. And the mouse pointer turns into the 'pointing hand' icon when hovering over the button.

Reproduced using Firefox 35.0.1 and 36.0 on Mac OS X 10.10.2.

**Comment by jamesshore** [comment]
I've narrowed this down to an interaction with the "FlashBlock" Firefox extension. Feel free to close the issue. [Or not](http://caniuse.com/#search=clipboard).

Details:

The page uses the [CopyClipboardComponent](https://github.com/emberjs/website/blob/master/source/javascripts/app/builds/templates/components/copy-clipboard.js.hbs). That component checks to see if Flash is available, and if it is, displays the quick copy button using Flash. If it isn't, it just displays a raw link.

I'm using the FlashBlock plugin, which reports that Flash is available, but prevents it from running. That causes the CopyClipboardComponent to use the "show flash button" path, but flash isn't actually enabled yet, so clicking the button does nothing.

Normally, FlashBlock shows a clickable UI element to enable Flash, but it's not happening in this case.

**Comment by trek** [comment]
We've migrated to versioned guides at https://github.com/emberjs/guides. If you feel this is still an issue, please reopen on that repo, thanks!
