### ISSUE TITLE
Guide - Getting Started: LocalStorage adapter fails with 'undefined is not a function'

### ISSUE THREAD

**Issue by finnigantime** [emberjs/website#2036]
I created a repository to show the repro for this issue. I worked through each step of the "Getting Started" guide and hit this issue on the final step (adding the LocalStorage adapter).

## Repro:
1. Pull the lsAdapterRepro branch: https://github.com/finnigantime/emberjs-gettingStarted/tree/lsAdapterRepro
2. Refresh index.html in browser.
3. Type some text in the "What needs to be done?" placeholder and hit enter.

## Manual Repro (working through the getting started guide yourself):
1. Work through the EmberJS "Getting Started" guide all the way until you get to the last step "Using other adapters": http://emberjs.com/guides/getting-started/using-other-adapters/
2. Hook up the LSAdapter in application.js and include a script reference in index.html.
3. Download the LSAdapter source from the link given in the guide (https://raw.github.com/rpflorence/ember-localstorage-adapter/master/localstorage_adapter.js).
4. Refresh index.html in browser.
5. Type some text in the "What needs to be done?" placeholder and hit enter.

*Expected*: Task is created.
*Actual*: Error encountered. Chrome console shows the error "Uncaught TypeError: undefined is not a function" on line 229 of localstorage_adapter.js. The problem is ```record._createSnapshot``` is undefined.

This is on Windows 8.1 in Chrome.

**Comment by trek** [comment]
Which version of Ember and ember-data are you using? ember-data is still in beta and its API changes.

**Comment by finnigantime** [comment]
I'm using the files linked from the "Getting Started" guide here:
http://emberjs.com/guides/getting-started/obtaining-emberjs-and-dependencies/

http://builds.emberjs.com/tags/v1.8.1/ember.js
http://builds.emberjs.com/tags/v1.0.0-beta.11/ember-data.js

**Comment by trek** [comment]
An over-eager commit PRed bumped ember-data to latest (at the time) without checking if they it still with the other dependencies (https://github.com/emberjs/website/commit/13a1eb173be3f8fcd6919edba32c2bcc6380bbb3). The TodoMVC guide aren't long for this world but if you want to find the latest ember-data that works with the suggested ember-localstorage-adapter or (see if latest https://github.com/kurko/ember-localstorage-adapter works with latest ember-data?) we'd accept that PR.

**Comment by finnigantime** [comment]
Looks like this PR bumped localStorage-adapter from Ember Data 1.0.beta.14.1 to 1.0.beta.15:
https://github.com/kurko/ember-localstorage-adapter/commit/728b4d062b48f41baf838d11c15aef0a5fc9a94c#diff-639624853778297e9e33bf4519ca8898

Using the previous version of localStorage-adapter works:
https://raw.githubusercontent.com/kurko/ember-localstorage-adapter/c32477626ce0e7c8447e1ee79eb78e64a8357d70/localstorage_adapter.js

I am happy to submit a PR that links this version of localStorage-adapter in the TodoMVC guide. Why is it going away though - is it being superseded? I found it to be a nice intro tutorial.

**Comment by trek** [comment]
>  is it being superseded? I found it to be a nice intro tutorial.

It doesn't really do a good job showing off the power of the framework sadly.
