### ISSUE TITLE
DefaultResolver API docs missing important methods

### ISSUE THREAD

**Issue by jamesshore** [emberjs/website#2038]
The [DefaultResolver API docs](http://emberjs.com/api/classes/Ember.DefaultResolver.html) don't include `resolveTemplate`, `resolveView`, etc. Given that these are the primary way DefaultResolver is meant to be extended, this is a notable omission.

The methods are documented in [the actual source code](https://github.com/emberjs/ember.js/blob/v1.10.0/packages/ember-application/lib/system/resolver.js#L272-L278), I'm guessing there's some bug in the way the API docs are generated. Perhaps `@protected` methods are being excluded?

**Comment by lukemelia** [comment]
@jamesshore the docs for those methods are visible on the page you linked if you check the "protected" checkbox

**Comment by jamesshore** [comment]
I completely missed that, thanks.

**Comment by lukemelia** [comment]
I have now helped you 1/1,000,000 of the amount "Art of Agile Development" helped me. :-) Thanks for the amazing book.

**Comment by jamesshore** [comment]
Thanks!
