### ISSUE TITLE
maps.google.com blocked in many countries

### ISSUE THREAD

**Issue by amerov** [emberjs/website#2040]
for example http://en.wikipedia.org/wiki/Websites_blocked_in_mainland_China

**Comment by stefanpenner** [comment]
im not sure we can do anything about this?

**Comment by amerov** [comment]
maps used only http://emberjs.com/community/meetups/ ?

**Comment by amerov** [comment]
![selection_049](https://cloud.githubusercontent.com/assets/196747/6425515/bb7d61b2-bf4e-11e4-8103-fd54be6101a9.jpg)

**Comment by trek** [comment]
I don't think we can take action on this sadly. Users in counties without open internet can at least see the list.
