### ISSUE TITLE
JS Bin example not working on guides

### ISSUE THREAD

**Issue by dinoonex** [emberjs/website#2055]
Hi,
JS Bin  example on guides section "Specifying routes model" is not working, as far I can see the problem are script sources, when I edit sources it worked
http://emberjs.com/guides/routing/specifying-a-routes-model/
http://jsbin.com/lihenu/1/edit?html,css,output

**Comment by vire** [comment]
@dinoonex it's being discussed here https://github.com/emberjs/website/issues/1998

upgrading to ember 1.10+ http://emberjs.com/blog/2015/02/07/ember-1-10-0-released.html

**Comment by dinoonex** [comment]
ok thanks
