### ISSUE TITLE
API documentation alphabetical items alternate columns making scanning/using difficult

### ISSUE THREAD

**Issue by terryroe** [emberjs/website#2100]
The API docs now have two columns and the alphabetical order alternates from column 1 to column 2 on each line. It would be much nicer to at minimum go back to one column. Or better, break the columns at a midpoint of the list and show the first half of the list in the first column and second half of the list in the second column.

**Comment by orochi235** [comment]
+1. This is atrocious UX. When you're browsing an ordered list, you want your vision to flow in a straight line, and not a sawtooth wave pattern.

**Comment by trek** [comment]
@terryroe this oddly didn't use to be the case. Can you figure out when it was introduced?

**Comment by wifelette** [comment]
Thanks so much for this folks. Alas, wrong repo :p If this is still an issue, it belongs here: https://github.com/emberjs/ember.js/issues
