### ISSUE TITLE
Remove Google Maps from every page load

### ISSUE THREAD

**Issue by mixonic** [emberjs/website#2103]
Google maps seems to be loading on every page of the website, and blocking fonts and the site from loading. For example I'm seeing this today:

![](https://api.monosnap.com/rpc/file/download?id=aFM2Vp0Szsy1PEAHuKbPVEy2FRhfdh)

The assets should at best be lazy loaded, and at the minimum only be loaded when on the page that needs them (the community page I believe).

**Comment by rwjblue** [comment]
:+1: - Would love help from someone on this...

**Comment by rwjblue** [comment]
Closed by #2105.
