### ISSUE TITLE
The download links on the Ember build page are broken

### ISSUE THREAD

**Issue by stevehanson** [emberjs/website#2108]
On the [Ember builds](http://emberjs.com/builds/#/release) page, the download links at the top of the page are broken. Broken links are marked with an "X" below:

![image](https://cloud.githubusercontent.com/assets/1691324/6906571/58930a48-d6f5-11e4-969b-52223fff0e63.png)

You can see that the URL looks like it's missing some information:

![image](https://cloud.githubusercontent.com/assets/1691324/6906365/17ccbba4-d6f4-11e4-90e4-9838c9c301ee.png)

![image](https://cloud.githubusercontent.com/assets/1691324/6906357/0fec3ef0-d6f4-11e4-9cc8-a34b29c96d0b.png)

This issue is occurring on the [Release](http://emberjs.com/builds/#/release), [Beta](http://emberjs.com/builds/#/beta) and [Canary](http://emberjs.com/builds/#/canary) pages.

**Comment by rwjblue** [comment]
Oiy. I must have broken this in https://github.com/emberjs/website/pull/2107.
