### ISSUE TITLE
font used for api navigation bar

### ISSUE THREAD

**Issue by tdesmet** [emberjs/website#2113]
Honestly the font used for the navigation bar on windows does not look good (my opinion, don't want to insult anybody) .

![image](https://cloud.githubusercontent.com/assets/6105179/6963923/a710bdae-d944-11e4-9eec-b2bf8e5a419b.png)

for example the link ember-extension-support x is bigger then e, i is bigger then s....
Its a mess imo...

**Comment by rwjblue** [comment]
@bsclifton fixed this in the guides repo, perhaps you can grab his fixes from their (or he could PR them here...)

**Comment by bsclifton** [comment]
PR submitted
https://github.com/emberjs/website/pull/2114

**Comment by trek** [comment]
@bsclifton can you add this to https://github.com/emberjs/api as well?

**Comment by bsclifton** [comment]
Done https://github.com/emberjs/api/pull/25
:smile:
