### ISSUE TITLE
Better Ember ecosystem representation on front page

### ISSUE THREAD

**Issue by vectart** [emberjs/website#2115]
It seems that current front-page doesn't work well, thus I would like to come up with an idea how to reflect the whole great Ember.js ecosystem.

Below you can see design mockup with three snippets of Ember.js, CLI and Data:
- Ember.js and Data snippet reflect latest versions and activity;
- Ember CLI snippet is looking more attractive and suggest newcomers to start with it.

![Ember Frontpage Suggestion](https://www.dropbox.com/s/3bkc55hw11cpe7d/ember.png?dl=1)

I suppose that such main part of Ember website may dramatically increase users' attraction and give clearer explanation of how to start with Ember ecosystem.

**Comment by eccegordo** [comment]
I for one like the direction of this mockup. Very clear and direct. Visually makes it obvious the major parts of Ember.

I would suggest two other categories below

### Examples

Keep the inline demo examples , templates  routing, components, etc

### Third Party 

Dynamically show stuff from around the community.
e.g. most recent, popular, active, addons

This could either be curated by core team or else algorithmically fetched from other websites like ember addons or emberobserver.com

I think telling the third party widget/component/addon story will help evangelize Ember's strengths.

**Comment by vectart** [comment]
@eccegordo Thank you very much!

I totally agree with your suggestions and, additionally, I would promote subscription to http://emberweekly.com/. Therefore, newcomers will be up to date to the latest Ember.js updates.

Actually, I would suggest to redesign Emberjs.com to make it look as good as the best tech websites, for example https://www.firebase.com/, https://www.parse.com/ or http://ionicframework.com/ — clear, nice and welcoming.

**Comment by trek** [comment]
Thanks for the ideas. We have a company who has volunteered to do a visual refresh. We'll point them to this issue.
