### ISSUE TITLE
Search/autocomplete from site to a result from the guides goes to 1.10 version

### ISSUE THREAD

**Issue by kategengler** [emberjs/website#2124]
Search on emberjs.com for 'query' and then select the first result for 'Routing: Query Parameters', it will take you to that page on the 1.10 version of the guides. I would expect it to take me to the newest stable version.

The same exercise from guides.emberjs.com goes to the 1.11 version of the guides.

**Comment by rwjblue** [comment]
Yeah, this is intended I believe.  See https://github.com/emberjs/website/issues/2111#issuecomment-88454878.

**Comment by kategengler** [comment]
This feels like a bit of a different scenario, though: Going to the 1.10 guides was the result of clicking on something the emberjs.com site provided and the search that looks identical on the guides page behaves like I would expect (searches the version you have selected). I would expect the website to be returning links to the latest version in the search or not return guide results at all.

**Comment by trek** [comment]
The website uses Swiftype's "crawling" feature to search. I think eventually guides results will not appear in the website search, only in the guide's search. Nobody was really clear on how we can do sitewide search across libraries and versions of libraries in a sane way :-/

**Comment by kategengler** [comment]
I think that the results not appearing on the main site at least makes sense, it's at least much better than them being stuck at 1.10.
