### ISSUE TITLE
Component testing guides are wrong

### ISSUE THREAD

**Issue by ohcibi** [emberjs/website#2125]
The component testing guides state that we would use "integration test helpers to interact with the component". However when setting up the component tests like normal unit tests there are no "integration test helpers" available... As far as I understand those helpers are only available if one calls `App.injectTestHelpers`, but there shouldn't be a `App` in unit tests.

So this section needs clarification

* are the component tests meant to be integration tests?
* are component tests not meant to be integration tests but still need to setup an `App` object somehow?
* is there a whole other way to inject the test helpers?

**Comment by trek** [comment]
This is likely fixed on latest? The [guides project](https://github.com/emberjs/guides) has changed significantly since April

**Comment by ohcibi** [comment]
@trek the stuff here: https://github.com/emberjs/guides/blob/master/source/testing/testing-components.md still shows unit testing code like `var component = this.subject();`. In current blueprints component-tests are integration tests and the test code in the blueprint looks completely different (i.e. there is no `this.subject` and `this.render` actually needs a handle bars template as parameter).

The point about the async test helpers still remains unclear as the blueprints still don't call `startApp` in `beforeEach` -- Which is what "acceptance" tests are doing in their blueprints and injects the test helpers amongst other things. I wonder why the test helpers can't just be injected without having an application instance created.

**Comment by trek** [comment]
Can you reopen on the guides repo. I suspect this will just got lost on this repo.
