### ISSUE TITLE
HTTPS for Ember family of sites

### ISSUE THREAD

**Issue by eliotsykes** [emberjs/website#2155]
It'd be great to see the Ember family of sites served securely over TLS/SSL.

**Comment by kitsunde** [comment]
Adding on. We can't use the CDN versions to create JSFiddles unless `build.emberjs.com` uses HTTPS. It gets blocked by chrome. I.e. this should work: https://builds.emberjs.com/release/ember-data.js

**Comment by michaelrkn** [comment]
The Guides support SSL, as they are hosted on Firebase. The naked emberjs.com website does not, as it is hosted on Github pages. There are two solutions:

1. Switch DNS to Cloudflare.
2. Switch hosting elsewhere.

If we switch hosting, I'm personally not super excited about Firebase hosting. It does the job, but it's really tooled around Firebase apps, most of which we don't need. It only lets app owners add new collaborators, and there's no staging environment. @rtablada suggested http://surge.sh/, which looks really nice, although I don't know if it fixes either of the problems with Firebase.

**Comment by locks** [comment]
@michaelrkn https://www.pagefronthq.com/ is the most like divshot, I think. They even have the different environments, and it seems to support SSL https://docs.pagefronthq.com/guide/ssl.html.

**Comment by mixonic** [comment]
Fastly has offered to sponsor an account with their service.

I worry about Pagefront being so young, and liable to shut down ala divshot. Surge has been around a bit longer I believe. :-/

**Comment by stefanpenner** [comment]
> Fastly has offered to sponsor an account with their service.

@mixonic ooo, we should take them up on this. (assuming everything checks out)

**Comment by michaelrkn** [comment]
I didn't realize Fastly now offers reverse proxy like CloudFlare - nice! If we can use them, then we don't have to update infrastructure and can stick with GH pages.

**Comment by acorncom** [comment]
:+1: On Fastly  Who do we need to help with this, @rwjblue ?

**Comment by rwjblue** [comment]
Yes, the delay has been 100% my fault. I need to gather a bit of info and get it back to them (they have been super responsive so far).

**Comment by acorncom** [comment]
4 hrs doesn't seem like a major delay :stuck_out_tongue_winking_eye:

**Comment by jasonkriss** [comment]
[Speaking for Pagefront] @locks Thanks for the heads up. We'd love to do everything we can to help out with all things Ember related. We do have multiple environments and SSL support. That being said, Pagefront is currently ember-specific, meaning that hosting other types of static sites might require more work than it is worth at this point.

Again though, anything we can do to help (free hosting, whatever) just let me know.

@mixonic Totally understand your concern (I would feel the same way). The only thing I can say is that Pagefront does not face the same type of pressure that Divshot did. We are completely bootstrapped and keep operating costs extremely low which means we can grow at a comfortable pace and wont be disappearing anytime soon.

**Comment by locks** [comment]
@rwjblue @mixonic @fivetanley were are we at with this?

**Comment by acorncom** [comment]
This has been resolved as part of our switch to Heroku hosting a few weeks ago.  Closing ...

**Comment by bgentry** [comment]
@acorncom wonderful, I can now access the sites over HTTPS!

Is it possible to do this by default (i.e. redirect from plain HTTP)?

**Comment by rwjblue** [comment]
Yep, its being worked on (having some issues with redirect + CDN ATM) and should hopefully be done soon.
