### ISSUE TITLE
'needs' documentation

### ISSUE THREAD

**Issue by ksnyde** [emberjs/website#2165]
I was struggling with a very basic `needs` use case where a nested route needs access to a parent and found the documentation missing some really important language nomenclature. I think the following SO post indicates the problem and solution very well:

> [SO description](http://stackoverflow.com/questions/29995005/ember-needs-objectcontroller-seems-inaccessible)

I hope for the future sake of others that this can be incorporated into future documentation. BTW, if there is a more helpful way to get this kind of suggestion into the team I'm very open to it. Still pretty new to this.

**Comment by igorT** [comment]
I feel this becomes much clearer once people stop using `resource` and moves over to `route`

**Comment by ksnyde** [comment]
No doubt you're right but the main point here is being clear about the syntax when using a nested `route`.  Maybe we could include a small "nudge" away from `resource` while we're at it.

**Comment by mixonic** [comment]
`needs` will be replaced by using `Ember.inject.controller`, or since controllers are going away even better would be a service.

I do not think we will be adding fresh documentation about how to use controllers to solve problems.

**Comment by ksnyde** [comment]
@mixonic I understand that everything must be prioritized (and the list is always long) but "needs" will be used for a some time to come in existing Ember apps (as will controllers). What we're talking about is a few lines of documentation, right? I'd just be careful about supporting the greater community rather than the front of the train (which I admit is a much nicer place to sit). ;)

**Comment by ksnyde** [comment]
If there's no interest then just close this issue but I'd vote for adding the documentation. I'll step out of this conversation at this point. My "needs" have been met.

**Comment by jgwhite** [comment]
@ksnyde I knew you wouldn’t be able to resist closing with a pun :grin:

**Comment by ksnyde** [comment]
@jgwhite I guess I'm predictable which is only a half step down from reliable

**Comment by mixonic** [comment]
Yeah sorry if I confused the matter. If there is a suggestion the documentation be tweaked here a PR is 100% welcome. Definitely want to guide people to the right place. Happy to review and make sure it gets in.

**Comment by trek** [comment]
Closing since `needs` is going away.
