### ISSUE TITLE
Notes on bound attribute syntax need clarification

### ISSUE THREAD

**Issue by protonate** [emberjs/website#2178]
HTMLBars bound attribute syntax differs from Handlebars with respect to how booleans are handled. I understand there is a planned {{boolean-attribute}} helper but until then the release notes for Ember 1.11 are misleading when migrating a Handlebars app. 

From [EMBER.JS 1.11.0 AND 1.12 BETA RELEASED](http://emberjs.com/blog/2015/03/27/ember-1-11-0-released.html)
```
<input disabled={{isDisabled}}>
```
In Handlebars this will work with a true/false boolean property. In HTMLBars the inline if helper should be used. It would be helpful to clarify this somewhere.

https://github.com/tildeio/htmlbars/pull/73
https://github.com/tildeio/htmlbars/issues/68

**Comment by xlfe** [comment]
Yeah this got me too & took a while to figure out what was going on

For example:
http://emberjs.jsbin.com/kaxicarufe/1/

**Comment by michaelrkn** [comment]
I believe this is covered in https://guides.emberjs.com/v2.2.0/templates/binding-element-attributes/.
