### ISSUE TITLE
tabs in examples in emberjs.com have no title text

### ISSUE THREAD

**Issue by Iftahh** [emberjs/website#2189]
See for example screenshot of the Gravatar example (but the same issue exists at all tabs)
![screen shot 2015-05-28 at 12 08 14 pm](https://cloud.githubusercontent.com/assets/798544/7856542/a6b1c8f2-0532-11e5-9981-c951eb90c57d.png)

**Comment by acorncom** [comment]
@Iftahh I'm assuming you are primarily talking about on the home page of the site?

**Comment by acorncom** [comment]
Fixed in #2218

**Comment by acorncom** [comment]
Closing this issue now ...
