### ISSUE TITLE
1.13 blog post: Add breaking change message for Safari's 'double finally on error bug'"

### ISSUE THREAD

**Issue by mixonic** [emberjs/website#2222]
- [ ] https://github.com/emberjs/ember.js/pull/11547

**Comment by acorncom** [comment]
@locks @mixonic Thoughts on this?  Do we still note this somewhere?

**Comment by acorncom** [comment]
See #2212 for suggestions on where to put these notes ...

**Comment by acorncom** [comment]
Given how long this has been outstanding, I'm going to close this.  v1.13.x isn't something we're actively working to support any more ...
