### ISSUE TITLE
Add link to Deprecations page on Guides or API page

### ISSUE THREAD

**Issue by mike1o1** [emberjs/website#2225]
When a developer uses a deprecated API or functionality, or receives a warning, the console logs the information with a link to the [deprecations page](http://emberjs.com/guides/deprecations). However, from what I can tell this deprecations page is never linked to anywhere in the guides.

**Comment by rwjblue** [comment]
That is correct, it is not linked from the website or the guides.  Not sure where that link should live, but I agree we should generally have one....

**Comment by igorT** [comment]
This will complicate things if we decide to host ED deprecations on a separate page

**Comment by mixonic** [comment]
Any link should likely go to http://emberjs.com/deprecations/, which could link to Ember 1.x, 2.x, Ember-Data etc.

**Comment by typeoneerror** [comment]
Submitted a PR related to this just a few days easlier: https://github.com/emberjs/website/pull/2219

**Comment by mixonic** [comment]
I'm closing this as resolved, but let me know if I've missed anything.
