### ISSUE TITLE
API Component missing reference to targetObject

### ISSUE THREAD

**Issue by Frozenfire92** [emberjs/website#2243]
I believe it is a common paradigm to want to access the parent's controller from within a component (especially now that views are changing over to components)

This is the only reference I found to it (which works as expected) http://stackoverflow.com/a/28663571/4330669 however the link to the ember API docs in that SO is gone, did this get removed by mistake?

**Comment by greyhwndz** [comment]
@Frozenfire92: checked on this and the documentation is in the source but is not being generated. @wifelette: is there anybody we could poke regarding this?

**Comment by toddjordan** [comment]
@Frozenfire92 @greyhwndz its in the documentation and its generated, but it is a private property, so if you the private box is unchecked, then the link won't work to it.  Once you check the private box the link works. Seems to be a limitation of the API doc site.

**Comment by toddjordan** [comment]
As targetObject is private, and new api doc infrastructure is being written, and this issue is ~10 months old, I am closing this issue.
