### ISSUE TITLE
Bad link pointing to the ember data filter repo

### ISSUE THREAD

**Issue by krzkrzkrz** [emberjs/website#2247]
http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html#toc_ds-store-filter-moved-to-an-addon mentions a link: https://github.com/ember-data/ember-data-filter

Clicking on https://github.com/ember-data/ember-data-filter redirects the user to http://emberjs.com/blog/2015/06/18/ember-data-1-13-released.html instead

**Comment by pdud** [comment]
This was fixed with #2257

**Comment by rwjblue** [comment]
Thanks @pdud, closing...
