### ISSUE TITLE
Deprectation of ArrayController is not documented anywhere

### ISSUE THREAD

**Issue by szimek** [emberjs/website#2260]
In http://emberjs.com/deprecations/v1.x/ docs `ArrayController` is not mentioned at all. The only information I get when running my app is: `Ember.ArrayController is deprecated.`. There're no docs describing how to migrate `ArrayController` to plain `Controller` if one uses methods from `Ember.MutableArray` class. Even if it just said something like: "set your model to an instance of `Ember.Array` (or `Ember.MutableArray`) and then use it like `this.get("model").addObject(object)` instead of `this.addObject(object)`", it would already be really useful.

The same thing is e.g. with `Ember.Set`. I found info somewhere in the docs that one should just use ES6 Set instead, but it doesn't say anywhere how to make it observable.

**Comment by stefanpenner** [comment]
> The same thing is e.g. with Ember.Set. I found info somewhere in the docs that one should just use ES6 Set instead, but it doesn't say anywhere how to make it observable.

Ember.Set wasn't public ever, and ES6 Set is not observable you are correct. But this is not at all related to ArrayController issue that i believe is the primary issue.



> In http://emberjs.com/deprecations/v1.x/ docs ArrayController is not mentioned at all. The only information I get when running my app is: Ember.ArrayController is deprecated.

yup, seems like an omission. cc @locks @cibernox @trek

**Comment by szimek** [comment]
@stefanpenner Yeah, the issue is mainly regarding `ArrayController`. I mentioned `Ember.Set`, because I was thinking about creating a separate issue for that as well, but if it was private then I agree that it's not really a bug.

**Comment by rwjblue** [comment]
https://github.com/emberjs/website/pull/2258 addresses this, but needs review.

**Comment by szimek** [comment]
In this case I think this issue can be closed as a duplicate. I'll add a comment to #2258.
