### ISSUE TITLE
Add to deprecation guide for Ember.ContainerView

### ISSUE THREAD

**Issue by martndemus** [emberjs/website#2261]
`ContainerView` will become deprecated. See emberjs/ember.js#11818 and emberjs/ember.js#11826.
I'd liked to do it myself but I have very little experience with it myself. Therefore I think someone with better experience with `ContainerView` should write it.

The deprecation message will point to the url `http://emberjs.com/deprecations/v1.x/#toc_ember-containerview`

**Comment by trek** [comment]
Closing in favor of #2265
