### ISSUE TITLE
Testing components section needs updating to reflect integration test as default

### ISSUE THREAD

**Issue by adam-knights** [emberjs/website#2262]
http://guides.emberjs.com/v1.13.0/testing/testing-components/

The setup section suggests that `ember generate component pretty-color` would generate a unit style test whereas now it generates an integration test by default.

The integration style examples lower down the page could all do with a refresh to match latest blueprints at the same time.

**Comment by EndangeredMassa** [comment]
The navigation should also probably include a section for Integration Tests. That's where I looked first to find more info on how these work.

**Comment by acorncom** [comment]
This should either be moved to the guides repo or closed.  We've got integration testing info under guides at this point ...

**Comment by adam-knights** [comment]
This is resolved in the 2.1 docs.
