### ISSUE TITLE
Broken link in guide: v1.13.0/models/

### ISSUE THREAD

**Issue by jacobbridges** [emberjs/website#2278]
Hi guys, found a broken link in the guide on the models page. 

In this [section](http://guides.emberjs.com/v1.13.0/models/#toc_convention-over-configuration-with-json-api) you will find a paragraph:

> Rather than create an arbitrary set of conventions, Ember Data is designed to work out of the box with **JSON API**. JSON API is a formal specification for building conventional, robust, and performant APIs that allow clients and servers to communicate model data.

The bolded text links to http://guides.emberjs.com/v1.13.0/models/jsonapi.org which does not exist.

Thanks so much for everything you guys do!

**Comment by acorncom** [comment]
Pull request for the change made at https://github.com/emberjs/guides/pull/550

@jacobbridges, in the future, there is a pencil icon up at the top of each guides page (I just learned about it myself last week). It will take you to the right place and make it super easy to send in a patch :-)

**Comment by locks** [comment]
@rwjblue please to close, as emberjs/guides#550 has been merged
