### ISSUE TITLE
API docs for DS.ManyArray doesn't show all inherited methods.

### ISSUE THREAD

**Issue by kitsunde** [emberjs/website#2291]
See: http://emberjs.com/api/data/classes/DS.ManyArray.html

It doesn't list down import methods like `removeObject` et. al. from `Ember.MutableArray`.

**Comment by wifelette** [comment]
Thanks so much for this. Alas, wrong repo :p If this is still an issue, it belongs here: https://github.com/emberjs/ember.js/issues
