### ISSUE TITLE
Instance initializer deprecation guide link is broken

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/website#2306]
There is a link in http://emberjs.com/deprecations/v1.x/#toc_access-to-instances-in-initializers
to http://emberjs.com/deprecations/v1.x/deprecations/1.11/instance-initializers which results in 404

**Comment by aexmachina** [comment]
Yes, this is still broken.

**Comment by rgbchris** [comment]
Link still appears to be broken - is there any update on this?

**Comment by acorncom** [comment]
If someone wants to open a pull request, we should be able to get this merged in ...
