### ISSUE TITLE
Please add reasons for deprecations to deprecation guides

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/website#2307]
As per conversation with @wycats in context of https://github.com/emberjs/rfcs/pull/84, documenting the reason(s) for a deprecation will be mandatory in future deprecation guides.

Could we please also add these to the 1.x deprecation guides? This will be helpful in explaining to coworkers and management why so many changes to Ember have been necessary. Thank you.

**Comment by wycats** [comment]
@Gaurav0 We're still pretty behind on just documenting all of the deprecations, but I'll try to fill in the rationale that I remember for the most recent deprecations once we're closer to full coverage on transition guidance.

**Comment by corrspt** [comment]
Sorry If I'm placing my comment in the wrong place, but it seemed like a good place/opportunity.

What would be the best way to help on with the documentation process? I know it's always a lot of work (and not the 'cool work') but it has to be done. I'm a fairly new developer to ember (picked an app on 1.7 and took it through 1.11/1.12) and I'm planning on starting an Ember 2.0 app. Having felt (some of) the pains with the transition(s), I would like to at least try and contribute to the documentation. Is there a list of issues with documentation to be addressed, is there someone I should reach out to? Sorry if I missed anything obvious, but my intention was good!

Thanks for all the hard work on Ember!

**Comment by Gaurav0** [comment]
@corrspt #2256 has the list of deprecation guides that still need to be written.

**Comment by corrspt** [comment]
Thanks for pointing it out. I'll look at it and try to figure out If I know enough to do something about it right away, or if I need to learn the stuff first before being able to help.

**Comment by Gaurav0** [comment]
@corrspt For what you don't know, just ask on the documentation channel in the Ember Slack community.

**Comment by acorncom** [comment]
@Gaurav0 In addition to #2256 is there other work here that is needed as well or can we close this issue?
