### ISSUE TITLE
Feature Flag Infrastructure for Guides

### ISSUE THREAD

**Issue by wycats** [emberjs/website#2311]
To make it possible to do documentation work for features that have not yet landed, we should have a feature-flag infrastructure in guides.

For example, you could imagine:

```
<feature-flag feature="ember-htmlbars-component-generation">
All of the new docs here.
</feature-flag>

<feature-flag not-feature="ember-htmlbars-component-generation">
All of the old docs here.
</feature-flag>
```

We would then use the `features.json` in Ember to build release-specific versions of the documentation. This would allow us to begin active work on documentation at the same time as active work on features, with the same collaboration benefits (versus feature **branches**) as feature flags have on the code itself.

The main work item here is to write infrastructure that strips content behind feature flags based on a `features.json`.

**Comment by wycats** [comment]
An alternative approach would be to preprocess the guides with Handlebars, and do something like:

```hbs
{{#feature-flag "ember-htmlbars-component-generation"}}
New docs
{{else}}
Old docs
{{/feature-flag}}
```

Might be nicer.

**Comment by eccegordo** [comment]
:+1:  Seems useful.

Given that this potentially opens some of the build infrastructure couple thoughts/questions

#### 1.) Emberify the docs and guides (e.g. remove middleman and have markdown content be pure API)

Pros:
- could be marketing benefit "Docs Built with Ember"
- could work well with handlebars format proposed above
- streamline publishing process, markdown content moved into API and separated from presentation concerns
- fast, iterative, versioned publish process (immutability of past guides should not preclude bug fixes on old content)
- content contributors don't have to be that concerned with presentation details (publish tooling, markup, CSS, etc) and just focus on content that feeds into API.
- ember app could potentially have extra rich features like the ability to peek at future content, or selectively manage the feature flag toggle state to understand and compare content changes. 
- offline mode
- api docs and guides could have first class UX that competes with tools like Dash.app.


Cons:
- potentially a lot of setup work
- requires writing and maintaining ember app
- publish process would be new and potentially disruptive to long term documentation contributors familiar with current system
- unnecessary complexity?

#### 2.) Provide nightly dumps of docs content if the feature flag system remains pre process.  e.g. a canary guides/docs

I think a lot more people would at least help review and help refine the content as it evolves. The middleman stuff while not hard to work with, might be just enough inertia to curtail more casual reviewers. Let alone understanding all the version and publishing infrastructure. 

A canary guides even if incomplete could give people an insight into the up coming features as they are evolving. A kind of "early warning" system for people frustrated by the deprecations process and pace of change.

**Comment by pzuraq** [comment]
@eccegordo how would converting the docs to an Ember app play with documentation applications like Dash? The ability to quickly search the docs offline is very useful to our workflow, would like to keep that. Not sure if Dash simply crawls web pages and saves rendered HTML, or something else.

**Comment by eccegordo** [comment]
@pzuraq I am not saying that ember app would necessarily enable Dash itself. But could provide a useful and similar user experience in its own right.

If dash needed to screen scrape some basic HTML perhaps this theoretical docs API could provide a plain unstyled HTML format output somewhere to serve as screen scrape target for tools like Dash.

**Comment by greyhwndz** [comment]
The idea of @eccegordo is great! :+1: 
Consider the multiplier effect brought about by making it easy for the community and would-be contributors to engage in the project and bringing it faster to new heights. I think it's way worth it.

**Comment by wifelette** [comment]
@wycats This belongs in the Guides repo. Is there an issue there so we can close this? Or is this even an issue anymore?

**Comment by michaelrkn** [comment]
Moved to https://github.com/emberjs/guides/issues/1101.
