### ISSUE TITLE
API links to github broken for RSVP

### ISSUE THREAD

**Issue by dlmccoy** [emberjs/website#2314]
Specific link I found was for RSVP, not sure if any other classes are affected.

Specific function I was looking at:
http://emberjs.com/api/classes/RSVP.html#method_all

Text:
"Inherited from RSVP but overwritten in bower_components/rsvp/lib/rsvp/all.js:3"

**Comment by wifelette** [comment]
Thanks so much for this. Alas, wrong repo :p If this is still an issue, it belongs here: https://github.com/emberjs/ember.js/issues
