### ISSUE TITLE
API for Component is missing new lifecycle hooks

### ISSUE THREAD

**Issue by mike-post** [emberjs/website#2321]
None of the [lifecycle hooks that were added in 1.13](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_component-lifecycle-hooks) are documented in the Ember.Component API. Looking at  [component.js](https://github.com/emberjs/ember.js/blob/v2.0.0/packages/ember-views/lib/views/component.js) I'm not surprised because the hooks aren't even defined in that class; I'm guessing their defined either by injection or somehow by the Glimmer engine.

**Comment by rwjblue** [comment]
They definitely do need to be documented (I know that @wycats is planning on working on that at some point), but they are generally considered "in development" at this point.  They work and are relatively stable, but may still be tweaked / adjusted once angle bracket components are enabled by default (hopefully by 2.2).

**Comment by trek** [comment]
Closing because these APIs are still private.
