### ISSUE TITLE
https://ember-community-slackin.herokuapp.com/ doesnt work

### ISSUE THREAD

**Issue by poeticninja** [emberjs/website#2325]
I was not sure where to post this but I have tried to setup myself as an ember slack user at https://ember-community-slackin.herokuapp.com/ based on the community page but I never receive an email. I have tried a few times over the past month and no email notification to login.

**Comment by mateuspv** [comment]
Hi, I think is https://embercommunity.slack.com/...not sure about the docs.

**Comment by poeticninja** [comment]
Perfect, i just reset my password from https://embercommunity.slack.com and it worked. Thanks!
