### ISSUE TITLE
Setup some way to share core "Ember design" CSS files between projects

### ISSUE THREAD

**Issue by acorncom** [emberjs/website#2326]
I'm starting to help on an integration of LiquidFire with the guides at https://github.com/emberjs/guides/issues/448.  Both there and on the Ember-Twiddle repo (https://github.com/ember-cli/ember-twiddle/pull/96) it's come up that we're trying to apply an Ember feel to the various sites.

Seems like it'd be helpful to start using a core SASS include of some sort across these various projects that applies the same look and feel.  Especially if there are rumblings about a redesign down the road.  Thoughts?  @wifelette

**Comment by wifelette** [comment]
Seems good :)

Do you have thoughts yet on how you'd want to structure it?

/ cc @wycats @rwjblue

**Comment by acorncom** [comment]
It looks like it's possible to export SASS files using Bower (https://github.com/twbs/bootstrap-sass/blob/master/bower.json#L13).  I think I'd export one main `_ember.scss` file, which in turn referenced two SASS files:

- `_generic.scss` (default heading, paragraph, link styles, sidebar / menu styling, drop down styles, etc)
- `_header.scss` (a more complete implementation, including background image with retina graphics, etc)

What I think we should be after with the above is to provide a base layer that can be identical across sites while allowing project-specific customizations (the Ember Twiddle edit box being a great example of something custom).

**Comment by acorncom** [comment]
Going to close this for now
