### ISSUE TITLE
Google searches return 1.10 versioned guides

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/website#2335]
When searching for issues in Google, search results prioritize pages from the 1.10 guides over more recent versions.

**Comment by alexdiliberto** [comment]
ping @trek

**Comment by trek** [comment]
This appears to be a common problem for api and guides that are versioned. I hit wrong version of docs for Rails, rspec, and other all day long. Not sure how to fix on our end since it depends, partly, on what has been linked to frequently and that was the the non-versioned (1.10) guides.

**Comment by michaelrkn** [comment]
See https://github.com/emberjs/guides/issues/604.
