### ISSUE TITLE
Module Transition

### ISSUE THREAD

**Issue by wycats** [emberjs/website#2339]
At some point in the future, we are going to want to support:

```js
import Component from "ember/component";
```

in addition to the current:

```js
import Ember from "ember";
var Component = Ember.Component;
```

We need the API docs to organize code around modules, but we also want to make sure that we keep around an up-to-date version of the docs (for 2.x) that organizes things around `Ember.*`.

The important thing is that people do not feel the ground shift out from under them when we start supporting the module form.

**Comment by SaladFork** [comment]
Related, easing the transition by automating as much of it as possible: https://github.com/abuiles/ember-watson/issues/13

**Comment by wifelette** [comment]
Thanks so much for this. Alas, wrong repo :p This belongs here: https://github.com/emberjs/ember.js/issues
