### ISSUE TITLE
Sidebar should not include private items

### ISSUE THREAD

**Issue by mixonic** [emberjs/website#2342]
In the API docs, the left sidebar should not include private namespaced items. Private APIs can still show up when looking at a class's methods etc, but should not be included in the main navigation.

![](https://api.monosnap.com/rpc/file/download?id=AWjFoACs8wbeG6jJsG3nW1z8prFQtL)

**Comment by wifelette** [comment]
Thanks so much for this. Alas, wrong repo :p If this is still an issue, it belongs here: https://github.com/emberjs/ember.js/issues
