### ISSUE TITLE
How to access 1.13 version of API docs?

### ISSUE THREAD

**Issue by eccegordo** [emberjs/website#2343]
It is really inconvenient that there appears to be no path to view 1.13 version of API docs. 

Is there a separate versioned set of API docs for 1.13?

If not, can an immutable, static snapshot be created? This is really bad and creates massive confusion for people who have not updated to 2.0 yet.

**Comment by rwjblue** [comment]
You can:

* use a YUIDoc viewer and view any published build's ember-docs.json file
* checkout the commit from this repo just prior to updating 2.0.0 docs, and run 'middleman'
* help out with the emberjs/api project to bring versioned API docs to fruition faster
* use a tool that provides versioned docs out of the box (Dash is a great example)

> This is really bad

Hopefully it is bad enough for people to be willing to help out and make it better.

**Comment by andrew-dixon** [comment]
@eccegordo FYI, you can view it here:

http://web.archive.org/web/20150513220302/http://emberjs.com/api/

**Comment by Gaurav0** [comment]
We are working on this at https://github.com/ember-learn/ember-api-docs Please help us out!
