### ISSUE TITLE
Slack link points to slack invitation app

### ISSUE THREAD

**Issue by SaladFork** [emberjs/website#2346]
http://emberjs.com/community/

In the sentence:
> You can also join the __Ember Community Slack__. To join, use _the Slackin app_.

The first link (bolded above) used to point to the Slack community itself with the latter (italicized above) pointing to the invite app. A [recent commit](https://github.com/emberjs/website/commit/95605399c9d3d1c3851ad15cc3fcde84393e1283) made both links point to the invite app. cc @wifelette

**Comment by wifelette** [comment]
Thanks for noticing, removed the link here: 628d47a03216e5b30287a8a2f006c4441ed1ffe6.

To be clear, I wanted to remove the direct link to the community _entirely_, because it led to getting numerous emails from people who clicked on it, never read the SlackIn part of the sentence, and were complaining that they couldn't figure out how to gain access :p

**Comment by pzenger** [comment]
@wifelette 
How can someone find the community domain name if they already have an account?  
Earlier I was trying to find the community name to login, but it's not anywhere on the community website.

**Comment by wifelette** [comment]
https://slack.com
https://slack.com/signin
https://slack.com/signin/find

If you go directly to Slack, there's a natural chain of links to follow: if you know the name of the community, if you don't, etc. It might be worth adding a footnote/tooltip or something with the name of the community, but again, wanting to avoid the link.

We have little to no bandwidth for email support, and people at large fail at reading :p So it's an awkward optimization, I know, but the correct one just the same.

**Comment by wifelette** [comment]
> You can also join the Ember Community Slack ("embercommunity" subdomain). 

Thinking that might do the trick and scratch both itches :) I'll hold on updating for any feedback on better wording!

**Comment by SaladFork** [comment]
Is there a way to link to the community itself from the invite app (which _is_ linked to)? Would that just be more confusing?

**Comment by wifelette** [comment]
It's possible, and might be a better idea! I don't manage that though, so I don't know. Not sure offhand who manages our instance of the Slackin app...

**Comment by wifelette** [comment]
cc @cromwellryan

**Comment by cromwellryan** [comment]
This what you were thinking? 

![image](https://cloud.githubusercontent.com/assets/129756/9457717/3ceb295a-4ab4-11e5-9113-22d22208f45f.png)

**Comment by wifelette** [comment]
+1!

**Comment by cromwellryan** [comment]
This has been merged and [deployed](https://ember-community-slackin.herokuapp.com).  Thanks for the idea all!
