### ISSUE TITLE
Broken link to ActiveModelAdapter in guides

### ISSUE THREAD

**Issue by mollerhoj** [emberjs/website#2353]
Link to ActiveModelAdapter goes nowhere:
http://guides.emberjs.com/v2.0.0/models/customizing-adapters/

**Comment by davidpett** [comment]
fix is here: https://github.com/emberjs/guides/pull/767

**Comment by locks** [comment]
Closed as per https://github.com/emberjs/guides/pull/768#issuecomment-141693126
