### ISSUE TITLE
Search results link to a nonexistant page.

### ISSUE THREAD

**Issue by mcantor** [emberjs/website#2364]
Steps:
1. Navigate to <http://guides.emberjs.com/>
2. Enter `debugging` in the search bar and hit Enter.
3. Click on the first result, which links to <http://guides.emberjs.com/configuring-ember/debugging/>.

What I expected:
- The search results should link to <http://guides.emberjs.com/v2.0.0/configuring-ember/debugging/>, or the page that is currently 404ing should redirect to it.

What happened instead:
- It stayed on the non-`v2.0.0/`-namespaced URL and 404'd.

**Comment by wifelette** [comment]
Thanks so much for this. Alas, wrong repo :p This belongs here: https://github.com/emberjs/ember.js/issues

**Comment by acorncom** [comment]
Actually, this one would probably need to go to https://github.com/emberjs/guides/issues if it's still an issue, but I believe we got that fixed a few months ago.
