### ISSUE TITLE
2.0.0 "Getting Started" section is inaccurate

### ISSUE THREAD

**Issue by tonylukasavage** [emberjs/website#2367]
If you follow the instructions as printed for getting started in the 2.0.0 section of the guides, you will end up with a project built for ember 1.13.7 (at the time of this issue). Specifically, after you create the app in the "your first ember app" section. To fix it I had to manually set the `ember` and `ember-data` versions in the `bower.json` file.

```
bower install --save ember#2.0.2
bower install --save ember-data#2.0.1
```

In lieu of `ember-cli` creating this automatically, the docs for 2.0.0 should reflect that this is not done automatically.

**Comment by locks** [comment]
That's because Ember CLI hasn't come out yet, so this is expected. We prefer to wait until it does than patch the guides.
We are also trying to figure out a way to make that guide more version-agnostic.

**Comment by wifelette** [comment]
Closing, to be reopened in the right place if it's still an issue.
