### ISSUE TITLE
Homepage examples don't work with ember-cli

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/website#2369]
Users trying to use examples on About page get Uncaught ReferenceError: App is not defined in ember-cli

**Comment by ultimatemonty** [comment]
most of these look pretty straight-forward to correct. The only tricky one is the Router example where you have several different things in `app.js`

Does it make more sense to add some comments on file location e.g.
```
// app/models/mailbox.js
let Mailbox = Ember.Object.extend();

Mailbox.reopenClass({
  find: function(id) {
    if (id) {
      return App.FIXTURES.findBy('id', id);
    } else {
      return App.FIXTURES;
    }
  }
});

export default Mailbox;

// app/router.js
export default Router.map(function() {
  this.route('mailbox', { path: '/:mailbox_id' }, function() {
    this.route('mail', { path: '/:message_id', resetNamespace: true });
  });
});
// ...
```

Or could we set these up in Twiddle's and then use iframes to embed each Twiddle? That'd be a nice way to show everything off as well as introduce folks to Twiddle right from the start.

**Comment by Gaurav0** [comment]
Twiddles to replace homepage examples:

https://ember-twiddle.com/45d81b7613faa6b9ad2aac6e1fb95b71
https://ember-twiddle.com/808b7181756ec08efe2dc795eefb3c3f
https://ember-twiddle.com/927461e47748823ceeab88dcf556bf6b

Example 4 needs discussion on how to replace fixture.

**Comment by ultimatemonty** [comment]
I'd say just move the fixtures to an array defined in model. outside of that I don't believe anything else needs to change

**Comment by Gaurav0** [comment]
Done that way:

https://ember-twiddle.com/aae9f2cccb25a5d41ba3a5de05bb13ab

**Comment by ultimatemonty** [comment]
thanks @Gaurav0! I'll try and take a look at this over the weekend

**Comment by acorncom** [comment]
@Gaurav0 One of the things we'd discussed in the past was the impact on Twiddle that the increase in traffic from the homepage would have.  Is that less concerning to you at this point?

**Comment by Gaurav0** [comment]
I don'the think that should be a problem.

**Comment by acorncom** [comment]
Per discussions we've had on the learning team, it's hard for us to contemplate switching to Twiddles for the home page (or elsewhere) while Twiddle has no support for IE/Edge: https://github.com/ember-cli/ember-twiddle#browser-support  While there are places we can get away with not having full support for IE, it's less than ideal to have our homepage displaying brokenness in IE 😀

Will keep this issue open, as we'd love to use Twiddles, but we may need some heavy lifting done on the Twiddle side of things before we can move this forward ...

**Comment by locks** [comment]
Solved by removing them :P
