### ISSUE TITLE
Deprecation Guide example for Ember.Select (1.13) works in a Controller but not in a Component 

### ISSUE THREAD

**Issue by maxkwallace** [emberjs/website#2372]
Having just attempted to use it myself, I discovered that the example given in the deprecation guide with `{{! app/templates/components/my-select.hbs}}`, `// app/components/my-select.js`, etc. doesn't work within a Component, only within a Controller.

I'm not asking that it be "fixed", but *please* update the documentation to reflect this. Otherwise, this issue will continue to cause confusion / frustration for people who attempt to replace Selects within Components using the example given.

I've pushed up a repo replicating the issue: https://github.com/maxkwallace/deprecation-guide-select-example-issue

**Comment by wifelette** [comment]
Can you submit a PR helping to explain the issue you've experienced to other people? I agree that it could be really helpful to others who might be similarly frustrated.

**Comment by maxkwallace** [comment]
@wifelette Thanks for the reply! I'd be happy to. But the ideal improvement would be to fix the example so it works in Components as well as Controllers (or at least explain why it doesn't work in both places) -- I will contact the person who originally wrote the example to see if this is possible.

I'll follow up with this in a few days.

**Comment by maxkwallace** [comment]
@wifelette So, I just attempted to replicate the issue again-- it turns out the error was on my end-- I forgot to call `this._super(...arguments);` in my Component. I'm going to close this issue. Sorry for the noise!

**Comment by rwjblue** [comment]
@maxkwallace - This was such a common issue that we figured out a way to throw a nice and useful error when they forget to call `_super` in a component.  This was added in https://github.com/emberjs/ember.js/pull/12396 and is included in 2.1.0.
