### ISSUE TITLE
Add Maintenance Policy

### ISSUE THREAD

**Issue by gpt559** [emberjs/website#2373]
Your security policy page ( http://emberjs.com/security/ ) states: 

"Fixes are prepared for all releases which are still under maintenance."

I don't see any place describing which versions are still under maintenance. Is it an explicit set like "1.13.x, 2.0.x", last X versions, or code released in the past X time?

My client needs this information in order to adopt Ember. 

Thanks!

**Comment by locks** [comment]
This is now addressed by http://emberjs.com/blog/2016/02/25/announcing-embers-first-lts.html.
