### ISSUE TITLE
Initializer vs Instance initializers

### ISSUE THREAD

**Issue by donovan-graham** [emberjs/website#2374]
How do you defer readiness when you're dependant on a service, in Ember 2.  I have the same use case and would have solved in similar to how is describe in the old docs.  Now in ember 2 it throws deprecation errors.  

This is the use case: http://guides.emberjs.com/v2.0.0/services-and-initializers/initializers/#toc_pausing-the-boot-process

**Comment by rwjblue** [comment]
You can use `deferReadiness` in an initializer, but not in an instance-initializer.  

This sort of howto question is almost definitely going to get a better set of answers on StackOverflow or the Ember community slack...
