### ISSUE TITLE
Broken "unit test helpers" link on 2.0+ guides

### ISSUE THREAD

**Issue by jblotus** [emberjs/website#2394]
Hi there. There is a broken link / missing article in the guides for 2.0.

If you go here:
http://guides.emberjs.com/v2.1.0/testing/unit-testing-basics/

or here:

http://guides.emberjs.com/v2.0.0/testing/unit-testing-basics/

and click the "unit-test helpers" link, which you will get a 404 at http://guides.emberjs.com/{version}/testing/unit-test-helpers

It does appear this section works in some older versions of the guide.

**Comment by jblotus** [comment]
![image](https://cloud.githubusercontent.com/assets/382230/10640520/0bcc37d6-77e3-11e5-94ce-a75cecaf9461.png)

forgot to enclose screenshot

**Comment by wifelette** [comment]
Thanks so much for this, and apologies for the delay. Alas, wrong repo :p If it's still broken, this belongs here: https://github.com/emberjs/guides/issues
