### ISSUE TITLE
Ember beta builds page out of date

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/website#2407]
Looks like @rwjblue shipped the 2.2.0-beta-2 release [a couple weeks ago](https://github.com/emberjs/ember.js/commit/d519881b2dfce5532938ca69b7b7c5044b158cbd) but the builds page didn't get updated.

If someone wants to tell me what needs to change, I'll (a) make that update today and (b) track it and help keep it up to date going forward. (I started scanning the source but it wasn't obvious what needed to change.)

**Comment by acorncom** [comment]
Sent over a few notes on your other issue

**Comment by locks** [comment]
After we finish extracting the builds app, we'll work on making the process more automated.
