### ISSUE TITLE
Ember builds "quick copy" is broken

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/website#2408]
The links to quickly download the builds from the builds pages are broken; the `<script>` tag is getting rendered inline (maybe because of something being escaped when it shouldn't be?):

![ember-builds](https://cloud.githubusercontent.com/assets/2403023/11160624/340952b0-8a3a-11e5-8efd-c09ddf2e7c71.png)

As with #2407, I'm happy to submit a PR with a fix if someone points me in the right direction. I started scanning the source but it wasn't obvious where I would need to submit the change.

**Comment by acorncom** [comment]
@chriskrycho I've poked at this a bit, so have a bit of reference on what is going on.

The builds page is an Ember globals app that's built using the Rails asset pipeline.  A few key files to get you going are:

- https://github.com/emberjs/website/blob/master/source/javascripts/builds.js
- https://github.com/emberjs/website/blob/master/source/javascripts/app/builds/app.js

Ping me if you need any other basic pointers, but you now know almost as much as I do about how it works ;-)

**Comment by chriskrycho** [comment]
👍🏼 I’ll try to take a gander again in the next week or three.

**Comment by acorncom** [comment]
@chriskrycho any updates here?

**Comment by chriskrycho** [comment]
Alas, not yet. In the middle of a job transition, do I've been busier than expected!

**Comment by acorncom** [comment]
Just checked, this is still broken

**Comment by acorncom** [comment]
Per a discussion with @Gaurav0 he pointed out I was "holding it wrong".  Clicking the "script tag" section copies a script tag to your clipboard.  Clicking the normal "builds" url copies that instead.  Closing this issue now.
