### ISSUE TITLE
Ember Data download links 404s

### ISSUE THREAD

**Issue by keith-g** [emberjs/website#2422]
On the releases page (http://emberjs.com/builds/#/release) Clicking any of the tagged links for Ember-Data on the release page gives a 404.

Eg:

http://builds.emberjs.com/tags/v2.2.0/ember-data.min.js
http://builds.emberjs.com/tags/v2.2.0/ember-data.js

I had to use the release builds.

**Comment by rwjblue** [comment]
@bmac - Would you mind looking into this when you have a minute?

**Comment by bmac** [comment]
Looking into this now.

**Comment by bmac** [comment]
Looks like there was a travis error that prevented the 2.2.0 file from being uploaded to s3. I don't have the credentials to re-upload the 2.2.0 file however I have published a new version of Ember Data (that includes this fix https://github.com/emberjs/data/pull/3866) and updated the builds page so it now points to a working `v2.2.1` file.
