### ISSUE TITLE
config.js example not working

### ISSUE THREAD

**Issue by JasperKamp** [emberjs/website#2436]
Hello. I could not get the mirage example to work, neither on a mac nor on a linux setup.
The website url is: https://guides.emberjs.com/v2.2.0/tutorial/ember-data/ 

I ended up looking at other examples on the internet which caused me to change the content of the config.js to [config.js.txt](https://github.com/emberjs/website/files/72839/config.js.txt)

**Comment by trek** [comment]
Hi @JasperKamp, you're probably looking to open an Issue on the https://github.com/emberjs/guides repo instead of here. This repo is just for homepage and blog.
