### ISSUE TITLE
Redirect /guides to the most recent version number

### ISSUE THREAD

**Issue by mozeryansky** [emberjs/website#2438]
Within the `emberjs/guides` project there is a current open issue working to implement a /current url pattern. Right now the layout in `emberjs/website/source/layouts/guide.erb` redirects to a hard coded version number. The current released version of the website will redirect to v1.13.0 guide, which is very old.

I want to open this issue and solve it when issue emberjs/guides#604 is solved.

**Comment by acorncom** [comment]
Looks like this was fixed by #2486
