### ISSUE TITLE
Code links are broken

### ISSUE THREAD

**Issue by cbou** [emberjs/website#2455]
On the API doc (e.g. http://emberjs.com/api/classes/RSVP.html#method_all) the links to the rsvp library are broken (e.g. [bower_components/rsvp/lib/rsvp/all.js:3!](https://github.com/emberjs/ember.js/tree/v2.3.0/bower_components/rsvp/lib/rsvp/all.js#L3))

**Comment by acorncom** [comment]
@cbou Could you open this issue on https://github.com/emberjs/ember.js?  API docs are generated over there.  Closing this now
