### ISSUE TITLE
Ideas for topics we can talk more about on the website

### ISSUE THREAD

**Issue by ebryn** [emberjs/website#2460]
_Just a few thoughts... feel free to suggest modifications to this list_

- Status updates of publicly visible features/initiatives, for example:
  - Routable components
  - Ember CLI 2.x stable release
  - The move to NPM for client side dependencies
  - Engines / lazy loading

- Architectural decisions made by the framework and build tooling, for example:
  - Why doesn't Ember CLI use Webpack?
  - What differentiates Glimmer from Virtual/Incremental DOM

- General FAQs
  - Why do I have to wipe out my NPM/Bower cache every time I upgrade Ember CLI?

I personally think we should have a structured area of the website to talk about these things. We end up piling a ton of information in long blog posts and I don't think users are able to find / reference it as easily.

**Comment by mmun** [comment]
- Why does Ember CLI use Broccoli?
- Why are the Ember CLI upgrade instructions as complicated as they are? [(link)](https://github.com/ember-cli/ember-cli/releases/tag/v1.13.15)
- Why does Ember CLI use QUnit by default?

**Comment by runspired** [comment]
+1 Advantage of having it in a structured way over blog posts is this information does change, blog posts tend not to.

**Comment by rtablada** [comment]
* Dedicated page (not just API and blog post) covering Ember Data store methods (findAll, findRecord, etc)

I think this could be a transplant of the 1.13 section from the blog

**Comment by grapho** [comment]
Comminity Page should be retooled/updated to include emberobserver.com, and other stuff, like the emberweekend podcast.. emberwatch.com.. and maybe links to different ember books and other things made by the commuity

**Comment by juliankmazo** [comment]
I think it would be awesome if we talk about [ember-browserify](https://github.com/ef4/ember-browserify) for managing some commun modules like lodash, moment, sweetalert...
I found out about it so late, and I think it works awesome. Just thinking ;)

Also covering the `component life cycle hooks` introduced in [1.13](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_component-lifecycle-hooks) All of us don't know about it

**Comment by locks** [comment]
@juliankmazo [The Component Lifecycle](https://guides.emberjs.com/v2.3.0/components/the-component-lifecycle/)

**Comment by juliankmazo** [comment]
@locks  :sweat_smile:

**Comment by jamilabreu** [comment]
Deployment services / options, i.e: prior to being acquired Divshot was a good choice, recently I saw a video where Yehuda used [Surge](https://surge.sh/)

**Comment by SuperManEver** [comment]
I'd like to know about overall Ember.js architecture, design decisions that were made and why they were made in this way.How all pieces fit together, what design pattern each component uses. 

Especially I'd like to have a overview of data layer of ember.js filled with details and snippets of code from  source code after which I can start hacking on Ember-Data.

Essentially what really want to have is a good resource where I can find information about how Ember.js really works and after reading it I can start dig into Ember.js source and it makes a lot of sense to me.

**Comment by SuperManEver** [comment]
@jamilabreu could you post a link where Yehuda uses Surge?

**Comment by jamilabreu** [comment]
@SuperManEver https://youtu.be/gk-xyLM7R4g?t=33m2s :)

**Comment by SuperManEver** [comment]
@jamilabreu thanks :+1:

**Comment by wifelette** [comment]
Lots of good ideas here, thanks all! 

As these are long-term wishlist items, I'm going to close (though not lock for now) the issue. In truth there is no perfectly appropriate spot for something like this right now :p I don't want to give anyone the false impression that these are things the team is currently working on; there are just very few volunteers working on docs and content stuff, so progress is slow-going. 

If any of you have time to step up and start/do the work on some of these, please ping in the Ember Community Slack! We'd probably start with a new issue devoted to one of the many ideas and flesh it out much more thoroughly.
