### ISSUE TITLE
Typo in Example Code - Customizing Serializers - EmbeddedRecordMixin

### ISSUE THREAD

**Issue by bhje** [emberjs/website#2467]
The code example for app/serializers/post.js should be **authors** not **author**.  

Occurrence #1
export default DS.JSONSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    **author**: {
      serialize: 'records',
      deserialize: 'records'
    }
  }
});

Occurrence #2
export default DS.JSONSerializer.extend(DS.EmbeddedRecordsMixin, {
  attrs: {
    **author**: { embedded: 'always' }
  }
});

**Comment by locks** [comment]
Hi @bhje, since this is an issue with the guides the proper repository to file the bug is emberjs/guides.
I went ahead and fixed it so you don't need to open it there :)
Thanks for reporting!
