### ISSUE TITLE
trying to get this running locally 

### ISSUE THREAD

**Issue by lordKnighton** [emberjs/website#2489]
**bundle exec middleman**  command not working. I ran the commands as the readme.md instructed 

`git clone git://github.com/emberjs/website.git`
`cd website`
`bundle`
`bundle exec middleman`

this is my result 
![screen shot 2016-03-05 at 7 43 30 pm](https://cloud.githubusercontent.com/assets/1773260/13552155/faa3afbe-e30a-11e5-94d0-155eca084bd9.png)

**Comment by locks** [comment]
Can you tell us your Ruby version?

**Comment by kelthenoble** [comment]
sure ☁  website [master] ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
