### ISSUE TITLE
Dead link in the deprecation guide

### ISSUE THREAD

**Issue by carlbennettnz** [emberjs/website#2492]
In the [Access to Instance Initializers section](http://emberjs.com/deprecations/v1.x/#toc_access-to-instances-in-initializers) of the 1.x deprecation guide, the final line ("For more information, see the instance initializer deprecation guide.") links to a [404 page](http://emberjs.com/deprecations/v1.x/instance-initializers).

**Comment by acorncom** [comment]
@carlbennettnz Confirmed.  Just opened a PR to fix that. The link should be pointing to http://emberjs.com/deprecations/instance-initializers/, so if you need that info in the meantime, that's where it is.
