### ISSUE TITLE
Rearrange content sections on the Community page

### ISSUE THREAD

**Issue by acorncom** [emberjs/website#2520]
Flip the the Stuck? Lost? header (and content) to be immediately beneath the meetup video (and move the "in a giving mood?" section down to where the Stuck? Lost? section was).

This prioritizes information a bit more to help new folks learning about the Ember Community for the first time.

**Comment by anilmaurya** [comment]
@acorncom Is anything pending in this issue OR it should be closed ?

**Comment by acorncom** [comment]
Thanks, closing
