### ISSUE TITLE
Deprecation Guide for 2.4-LTS items

### ISSUE THREAD

**Issue by mixonic** [emberjs/website#2538]
The deprecation guide is missing two items for Monday's release:

* [x] A deprecation guide for the private legacy view and controller flags.
* [x] A deprecation guide for deprecating `{{#render` https://github.com/emberjs/website/pull/2540

Additionally, we currently lack a unified way to note if a public or private API is being deprecated. Better than flagging things as public/private would be to add the `until` value of a deprecation to guide entries.

**Comment by mixonic** [comment]
![image](https://cloud.githubusercontent.com/assets/8752/14414933/adc5e396-ff67-11e5-8e2f-ae4590a023c0.png)
 via @locks

**Comment by rwjblue** [comment]
Added https://github.com/emberjs/website/issues/2543 for the last point (and I fleshed it out a bit more).
