### ISSUE TITLE
Builds Page LTS section is outdated

### ISSUE THREAD

**Issue by indvinoth** [emberjs/website#2541]
The first LTS was released on Feb 25, 2016. The [http://emberjs.com/builds/]() page LTS section is not yet updated.

![ember page](https://cloud.githubusercontent.com/assets/836863/14415938/05cfb066-ffd7-11e5-9ed3-df34b9027433.png)

**Comment by rwjblue** [comment]
The date is wrong, the first LTS is scheduled to be released at the same time as 2.5.0 (within the next day or so).

**Comment by anilmaurya** [comment]
I think this issue is not relevant anymore.

![screen shot 2016-04-12 at 1 22 47 pm](https://cloud.githubusercontent.com/assets/1912864/14453328/c1fae3de-00b1-11e6-8903-dc01c934d004.png)

**Comment by indvinoth** [comment]
@anilmaurya  Thanks for the update. I am closing the issue as it  is no longer valid.
