### ISSUE TITLE
Add `until` and `id` information to 2.x deprecation guide items.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/website#2543]
In Ember 2.0 when a deprecation is triggered, there are a few pieces of information that are helpful to know that are not currently shown in the 2.x deprecation guide.

* `until` - Each deprecation must include this property, which indicates the last version of Ember that a given feature will be supported in.
* `id` - Each deprecation must include this property, which is an easy to match `id` for a given deprecation. This is useful because many deprecations include information that is unique per invocation (i.e. filename / line / column info for template deprecations; object id / name for runtime deprecations; etc).

We should add this information under each header, so that users can understand when support will be dropped and/or can search for a given `id` and find a match...

#### Checklist
- [x] 2.1
  - [x] http://emberjs.com/deprecations/v2.x/#toc_initializer-arity
  - [x] http://emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry
  - [x] http://emberjs.com/deprecations/v2.x/#toc_ember-applicationinstance-container
  - [x] http://emberjs.com/deprecations/v2.x/#toc_ember-debug-function-options
  - [x] http://emberjs.com/deprecations/v2.x/#toc_ember-component-defaultlayout
  - [x] http://emberjs.com/deprecations/v2.x/#toc_ember-component-currentstate
- [x] 2.2
  - [x] http://emberjs.com/deprecations/v2.x/#toc_function-as-test-in-ember-deprecate-ember-warn-ember-assert
- [x] 2.3
  - [x] http://emberjs.com/deprecations/v2.x/#toc_injected-container-access
- [x] 2.4
  - [x] http://emberjs.com/deprecations/v2.x/#toc_render-helper-with-block
  - [x] http://emberjs.com/deprecations/v2.x/#toc_use-ember-string-htmlsafe-over-ember-handlebars-safestring
  - [x] http://emberjs.com/deprecations/v2.x/#toc_ember-component-didinitattrs
  - [x] http://emberjs.com/deprecations/v2.x/#toc_model-param-in-code-render-code-helper

**Comment by rwjblue** [comment]
@emberjs/guides-managers - Could y'all help muster the troops on this one?

**Comment by Serabe** [comment]
I take 2.4

**Comment by adamwysocki** [comment]
happy to pick this one up!

**Comment by adamwysocki** [comment]
I think this covers it https://github.com/emberjs/website/pull/2547

**Comment by rwjblue** [comment]
Thanks @adamwysocki!
