### ISSUE TITLE
Link in README to clone repo is wrong

### ISSUE THREAD

**Issue by TJScalzo** [emberjs/website#2589]
Currently it says:
```
git clone git://github.com/emberjs/website.git
```
It should be:
```
git clone https://github.com/emberjs/website.git
```

I assume everyone is smart enough to figure out the proper link to clone things. I just think it'd be best if the `README` had an accurate link.

**Comment by locks** [comment]
Can you submit a PR please?

**Comment by acorncom** [comment]
Either should work, but the `git://` link only works if you have your Github account setup with an SSH key (if I remember correctly)

![screen shot 2016-05-17 at 3 27 52 pm](https://cloud.githubusercontent.com/assets/802505/15339909/f54a47b8-1c43-11e6-8444-493675e8253a.png)
![screen shot 2016-05-17 at 3 27 57 pm](https://cloud.githubusercontent.com/assets/802505/15339910/f54be0e6-1c43-11e6-90d6-80a25daddec3.png)

**Comment by TJScalzo** [comment]
@acorncom I don't have mine set up with SSH so it didn't work when I tested it. That's what made me assume it didn't work. 
@locks Do you still want me to make a pull request with changes or is it fine how it is?

**Comment by acorncom** [comment]
@TJScalzo Yep, send in a PR, better to have instructions that work for everyone :-)
