### ISSUE TITLE
Version dropdown on guide does not maintain original navigation state within guide

### ISSUE THREAD

**Issue by Vaporbook** [emberjs/website#2599]
1. Google "Ember View Layer guide" https://www.google.com/search?q=Ember+View+Layer+guide&oq=Ember+View+Layer+guide&aqs=chrome..69i57j69i60.293j0j7&sourceid=chrome&ie=UTF-8

2. Click the first result. https://guides.emberjs.com/v1.10.0/understanding-ember/the-view-layer/

3. Change the version using the dropdown, to v1.13.0. It goes to https://guides.emberjs.com/v1.13.0/

This is either a bug or a UX defect, as the user intent is to go to the RELEVANT page in the selected version's documentation, not to go to the top level of that documentation. This is because the user, in this common scenario, has already landed on a desired topic, and just wants to see the corresponding topic in another version, not begin reading another version's guide from the beginning.

Unfortunately this may be a common scenario for those wishing to learn about ember, since browsing the source code can often surface doc URLs that 404, forcing the user to fall back to Googling things instead.

**Comment by locks** [comment]
The [explanation for the 404 page](https://github.com/emberjs/website/issues/2598) bug is also relevant to this problem.

The learning team is aware of both the problems with the version switcher, where we're limited by legacy infrastructure, and the need for technical explanations, where we're limited by lack of bandwidth.

I am closing this issue as there's already one in the respective Guides repository. Thank you once again, keep letting us know of problems you encounter so we can improve the experience.
