### ISSUE TITLE
Ember CLI Addon link broken

### ISSUE THREAD

**Issue by kgish** [emberjs/website#2601]
At the bottom of the [quick start](https://guides.emberjs.com/v2.5.0/getting-started/quick-start/) page, the Ember CLI Deploy Addon link is broken (404).

**Comment by locks** [comment]
Thank you for bringing it up. This [has been fixed](https://github.com/emberjs/guides/pull/1406) in the guides already, and should be updated when we release the 2.6 guides this week.
