### ISSUE TITLE
Tutorial: Minor typo

### ISSUE THREAD

**Issue by kgish** [emberjs/website#2605]
https://guides.emberjs.com/v2.5.0/tutorial/simple-component/

For the sample `app/templates/index.hbs`:

```
<h1> Welcome to Super Rentals </h1>

We hope you find exactly what you're looking for in a place to stay.

{{#each model as |rentalUnit|}}
  {{rental-listing rental=rentalUnit}}
{{/each}}
```
should be:

```
<h1> Welcome to Super Rentals </h1>

<p>We hope you find exactly what you're looking for in a place to stay.</p>

{{#each model as |rentalUnit|}}
  {{rental-listing rental=rentalUnit}}
{{/each}}

{{#link-to "about"}}About{{/link-to}}
{{#link-to "contact"}}Click here to contact us.{{/link-to}}
```

A suggestion might be to explain `{{partial shared/footer}}` before.

**Comment by acorncom** [comment]
@kgish Would you mind sending in a PR for your change above?

**Comment by kgish** [comment]
Sure i can do that, just lazy by nature ... :-)

**Comment by locks** [comment]
@kgish it's actually more work to open this issue than to click the pencil on the guides page and edit in-line ;P

**Comment by locks** [comment]
@kgish you mention a `{{partial}}`, but I can't find any in the Tutorial, where did you see it mentioned?

**Comment by locks** [comment]
cc @toddjordan

**Comment by kgish** [comment]
I tried clicking the pencil but it said that I had to fork it first in order to make changes. Looked in the code and see there's a `simple-component.md` file I can modify but don't know what to do with all the other language versions. Must I edit these as well?

**Comment by kgish** [comment]
In the guides repos. Which branch should I use?

**Comment by locks** [comment]
Strange, it should fork for you. I have to check it.

You just need to translate the source english one, `simple-component.md`. Master branch :)

**Comment by kgish** [comment]
I'm referring to the v2.5.0 one, there seems to be many differences between master and what I see.

**Comment by locks** [comment]
@kgish you can't, our current infrastructure only enables us to update master :\

**Comment by locks** [comment]
Reach us at #-learning on Slack if you need a bit more direction!

**Comment by kgish** [comment]
Bummer, will check in for assistance.

**Comment by toddjordan** [comment]
@kgish The tutorial's currently being revamped as part of https://github.com/emberjs/guides/issues/1374

The footer has turned into a navigation banner and placed in the application hbs.  I don't see a need for partials here.  as the banner will be single sourced.

You should start seeing more updates to the tutorial when the 2.6 version of the guides are deployed.  There will also be changes after that.  you can follow the issue above the keep track, as well as the super-rentals repo: https://github.com/emberjs/super-rentals which is kept up to date as tutorial updates are merged.

**Comment by toddjordan** [comment]
I see there's also issue #2606 which is related.  I'm closing this issue since the nav markup in index.hbs is going away.
