### ISSUE TITLE
Tutorial: Explain partials for header and footer in application.hbs

### ISSUE THREAD

**Issue by kgish** [emberjs/website#2606]
At the beginning of the tutorial I'd like to suggest explaining `application.hbs` by bracketing `{{outlet}}` with the common header/footer.

```
<div class="container">
    {{partial 'shared/header'}}
    {{outlet}}
    {{partial 'shared/footer'}}
</div>
```

with `shared/-header.hbs` containing:
```
<nav>
    {{#link-to "about"}}About{{/link-to}}
    {{#link-to "contact"}}Click here to contact us.{{/link-to}}
</nav>
```

and `shared/-footer.hbs` containing something like this:
```
<footer>
    &copy; Super Rentals 2016. All rights reserved.
</footer>
```

**Comment by acorncom** [comment]
@toddjordan Thoughts?  I'm inclined to agree, but wonder about not using partial but a few simple component there instead ...

**Comment by kgish** [comment]
Sure, components would be better and more applicable to the newer version ob emberjs.

**Comment by toddjordan** [comment]
@kgish @acorncom what do we think the advantage of using a partial or a component here as opposed to just declaring the markup in application hbs?

**Comment by locks** [comment]
@toddjordan conciseness in the Guides examples and an excuse to show components? Otherwise, inlining makes sense.

**Comment by kgish** [comment]
I always prefer to have my header and footer stuff easily referenced in separate files (be it either a component or partial), also for the sake of avoiding too much clutter.

**Comment by toddjordan** [comment]
While I am not opposed to the idea of using partials or components for clearing up clutter on the the application template, our goal with the tutorial is to introduce basic/universal concepts to get one started developing an app.  

Also, using a component introduces components before its formal introduction later in the tutorial.  

I would rather see partials introduced in the guides under the templates section, explaining this use case.  @locks thoughts on this?

**Comment by locks** [comment]
I consider `{{partial}]` and friends to be soft-deprecated, hence [their removal from the guides](https://guides.emberjs.com/v1.13.0/templates/rendering-with-helpers/).
I am closing this issue as the super rentals tutorial seems to have been updated significantly since the code mentioned by OP.

Thanks for the discussion everyone, let's keep improving the tutorial :)
