### ISSUE TITLE
Deprecation Guide for modifying property within didInsertElement

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/website#2615]
The solution presented here:

http://emberjs.com/deprecations/v1.x/#toc_modifying-a-property-within-code-didinsertelement-code

usually doesn't work. didRender triggers the same deprecation warnings. In fact, this deprecation warning is poorly worded in that regard.

Anyway, I suggest that the best solution is to use the run loop, i.e. `Ember.run.schedule('afterRender', ...` within `didInsertElement`.

**Comment by btecu** [comment]
This can be closed.

**Comment by acorncom** [comment]
Thanks
