### ISSUE TITLE
ember-fastboot deploy instructions error

### ISSUE THREAD

**Issue by steve9001** [emberjs/website#2626]
On http://ember-fastboot.com/docs/deploying under the "Deploying Your App" section, the first sentence of the third paragraph seems to contradict the rest of the section:
"Make sure that you install npm modules in dist **before** uploading dist to your server."

**Comment by rwjblue** [comment]
Hmm. I'm not sure which repo houses the fastboot website at the moment. 

@tomdale / @danmcclain - Do y'all know?

**Comment by danmcclain** [comment]
https://github.com/ember-fastboot/fastboot-website
