### ISSUE TITLE
Programmatically update link to Quick Start on builds page

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/website#2629]
It would be *great* if the link to the Quick Start guide on the builds page were updated automatically, so we don't need to remember to do manual changes like #2627 going forward.

@rwjblue [suggested](https://github.com/emberjs/website/pull/2627#issuecomment-227147791) doing similar to [how the `guide.erb` gets the version](https://github.com/emberjs/website/blob/05ff7028cf46f65ed36c6cb388990fb4541a86a5/source/layouts/guide.erb#L3-L13).

**Comment by locks** [comment]
Duplicate of #2628

**Comment by chriskrycho** [comment]
Ha! You beat me to it!
