### ISSUE TITLE
Old build?

### ISSUE THREAD

**Issue by samselikoff** [emberjs/website#2638]
I think an old version of the website might have gotten published?

http://emberjs.com/builds/#/beta shows "2.6.0 coming May 23rd"

![image](https://cloud.githubusercontent.com/assets/2922250/16503689/291a9992-3ee2-11e6-9476-9ffe3779840e.png)

and http://emberjs.com/blog/ shows May 17 as the latest post

![image](https://cloud.githubusercontent.com/assets/2922250/16503704/348c979e-3ee2-11e6-8035-ba92457c1f86.png)) 

etc

**Comment by rwjblue** [comment]
OK, looks fixed now.  I believe that @locks has tweaked the deploy script also to prevent this in the future.
