### ISSUE TITLE
Replace search system with new Algolia setup

### ISSUE THREAD

**Issue by bambery** [emberjs/website#2640]
Right now, when I search on the guides page (https://guides.emberjs.com/), I get API results. For example, I was looking for more information on _super. 

![screen shot 2016-07-05 at 7 00 41 pm](https://cloud.githubusercontent.com/assets/161639/16603594/d8486e90-42e2-11e6-963a-f60b11741f73.png)

When I do the same search on the API page, I got no results. I don't seem to be able to search the API docs from the API page.

![screen shot 2016-07-05 at 7 01 51 pm](https://cloud.githubusercontent.com/assets/161639/16603612/0028e818-42e3-11e6-9261-1f6e6dbc39db.png)

**Comment by acorncom** [comment]
What you are seeing is part of a slow swapping out of our search systems (the old one didn't work as well).  We've been testing on guides (v2.3-2.6) and were gauging people's reaction before back porting to older guides.  Once we finish back porting search, we'll replace search on the main emberjs.com website (and the API section in particular)

Thanks for the feedback, I'm gathering you like the new search system better? ;-)
