### ISSUE TITLE
Missing blog posts on emberjs.com/blog.

### ISSUE THREAD

**Issue by workmanw** [emberjs/website#2642]
Specifically the latest two about ember/ember-data 2.6 being released and the post about subteams. They're in the website's repo: https://github.com/emberjs/emberjs.github.com/tree/master/blog/2016/06/09 , they just don't seem to be listed on the blog index page. 

![image](https://cloud.githubusercontent.com/assets/825487/16716683/d2db1460-46d1-11e6-95ae-5669f365da9f.png)

**Comment by rwjblue** [comment]
Ugh. This happened once before. Something about our auto-deploy is resulting in older revisions being deployed.

**Comment by workmanw** [comment]
Oh. Perhaps it'll just disappear on it's own again? If I see that happen I'll close this issue.

**Comment by locks** [comment]
The `learn-page` got deployed. On it.

**Comment by locks** [comment]
That branch was older than the fix to the script, so it didn't contain the check for `master`. We should be good again! Thanks @workmanw.

**Comment by workmanw** [comment]
:+1: Those posts are back up now :)
