### ISSUE TITLE
Ember.Select documentation 404

### ISSUE THREAD

**Issue by radu-stefanache** [emberjs/website#2660]
I was looking for the documentation of the Ember.Select and got a 404 for the first result:
http://emberjs.com/api/classes/Ember.Select.html

**Comment by locks** [comment]
Hi @radu-stefanache, where and what did you search for that link to be the first result? Thanks!

**Comment by radu-stefanache** [comment]
Hi Ricardo,

did a google search and that link is the first result.

http://lmgtfy.com/?q=Ember+select+site%3Aemberjs.com

Cheers,
Radu S.

**Comment by locks** [comment]
Ah, in that case there's not much we can do to fix this problem, as far as I'm aware.
`Ember.Select` was removed in Ember 2.0, and our API docs aren't versioned, so they always show the current version.
I'll make a note to bring this up at the next meeting, thank you for bringing it up!
