### ISSUE TITLE
bundler: failed to load command: middleman (/usr/local/bin/middleman)

### ISSUE THREAD

**Issue by xmuplus** [emberjs/website#2663]
Sir, I follow your guides to operate. But after I enter `bundle exec middleman`, it prints such errors. I can find 'middleman-3.4.1' in `/usr/local/lib/ruby/gems/2.3.0/gems`.

`bundler: failed to load command: middleman (/usr/local/bin/middleman)
LoadError: cannot load such file -- rack/mime`

 I had tried several times on OS X, but couldn't deal with it. Please help me. Thanks!

**Comment by locks** [comment]
Hi @xmuplus, did you run `bundle install` before, and did it run without errors?

**Comment by xmuplus** [comment]
@locks Sir, it's so kind of you to reply. Thank you! I have solved it successfull by  reinstalling Ruby (via RVM) and Rubygems before using `bundle install` you recommended, . Because when I run some Jekyll blogs using `jekyll serve` locally today, there were many `failed to load command: ******`.

**Comment by acorncom** [comment]
Glad to hear you got this sorted out, will close this now then. :-)
