### ISSUE TITLE
Menu bar messed up on Safari

### ISSUE THREAD

**Issue by Ajeey** [emberjs/website#2667]
Safari Version 8.0 (10600.1.25)

<img width="1440" alt="screen shot 2016-08-22 at 12 40 58 pm" src="https://cloud.githubusercontent.com/assets/1799117/17879692/98374344-6911-11e6-94e2-3ed6364dec7e.png">

**Comment by acorncom** [comment]
@Ajeey Are you able to track down any additional information on what is going on here?  I'm running Safari 9.1.2 and am not seeing anything close to the same issue ...

**Comment by Ajeey** [comment]
I suppose it only occurs on Safari 8.0. Will debug and let you know.

**Comment by Ajeey** [comment]
@acorncom We need to add `display: -webkit-flex;` in .header .container rule for flex to be supported in safari browsers < 9.

PR - https://github.com/emberjs/website/pull/2668

**Comment by locks** [comment]
Thanks for the quick fix!
