### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by BrettKoenig** [emberjs/website#2681]
The link with the text "To tell us more about your request, reach out." is broken on the page http://emberjs.com/tomster/faq/

**Comment by wifelette** [comment]
Fixed in https://github.com/emberjs/website/commit/09b49c2e00036ecc43223696d61af065c79d89ee

**Comment by wifelette** [comment]
Pretty sure I broke this yesterday :p Will sort out _how_ later, but thanks for reporting!
