### ISSUE TITLE
Incorrect line of code in documentation?

### ISSUE THREAD

**Issue by teunsteenbekkers** [emberjs/website#2686]
Hi there!

To get familiar with your awesome tool I started out with the tutorial on your site and adapted it to my own use case.

I **think** I found an error in the section _Services and Utilities_ of the tutorial (Ember v2.8.0), though I'm not entirely sure.

Well, here goes:

In the file below there's a line in the integration test which is supposed to check if a map element was put on screen. It does so by expecting the amount of children of the _.map-container_ element to be 1:

_tests/integration/components/location-map-test.js - line 25_
`assert.equal(this.$('.map-container').children().length, 1, 'the map element should be put onscreen');`

However, this test always fails for me. I think it's because the _.map-container_ element, as it is shown in the template, does not contain any children whatsoever:

_app/templates/components/location-map.hbs - line 1_
`<div class="map-container"></div>`

So I think it's only logical that this test always fails up to this point. Am I correct in believing this is the case?

When I give the element a child, the test passes just fine. :-) I hope you can verify this is an error in the docs or not.

Keep up the great work, guys!

**Update 13.53:** In my comment below, you'll see I discovered that the following line was missing before the assertions in the last few lines:

`this.get('mapsService').getMapElement(this.get('myLocation'));`

This method is the one that sets the `calledWithLocation` variable on the service and adds the child element to the _.map-container_ element.

**Comment by teunsteenbekkers** [comment]
Also, in:

_tests/integration/components/location-map-test.js - line 25_
`assert.equal(this.get('mapsService.calledWithLocation'), 'New York', 'a map of New York should be requested');`

I should be getting a pass because the 'calledWithLocation' should be set to 'New York', yet this is not the case. Can't seem to get it to pass.

**Comment by toddjordan** [comment]
@teunsteenbekkers Thanks for reporting, I'll take a look.  Note that there's a working version of the super rentals turorial in github you can use to validate your code: https://github.com/ember-learn/super-rentals

**Comment by acorncom** [comment]
@teunsteenbekkers Regarding the above, would you be able to send in PRs for those two items on the guides repo (https://github.com/emberjs/guides/)?  Would be much appreciated! 👍 

I'll go ahead and close this issue for now

**Comment by teunsteenbekkers** [comment]
When I find time later today I'll certainly do that! :)
