### ISSUE TITLE
Ember.js guides link is down 

### ISSUE THREAD

**Issue by callmeNewbie** [emberjs/website#2689]
the ember.js guide https://guides.emberjs.com/ is broken link i try to click but the link is down

**Comment by locks** [comment]
Can't reproduce @callmeNewbie:

![screen shot 2016-10-03 at 11 07 18](https://cloud.githubusercontent.com/assets/32344/19034086/995d912a-8959-11e6-8160-2a718d181e05.png)

**Comment by callmeNewbie** [comment]
yeah i check the docs but the link is down

**Comment by callmeNewbie** [comment]
right now i just browse the guides in ember.js you can close now the issues :)
