### ISSUE TITLE
Update Getting Started on homepage to use yarn

### ISSUE THREAD

**Issue by iezer** [emberjs/website#2696]
`yarn global add ember-cli` instead of `npm install -g ember-cli` [docs](https://yarnpkg.com/en/docs/migrating-from-npm). 

Or maybe give both options?

<img width="339" alt="screen shot 2016-10-12 at 12 48 43 pm" src="https://cloud.githubusercontent.com/assets/87991/19319322/6e433d78-907a-11e6-9057-b8e79348d5e1.png">

**Comment by stefanpenner** [comment]
https://github.com/emberjs/website/pull/2697#issuecomment-253298283
