### ISSUE TITLE
A search with no results should indicate that there are no results

### ISSUE THREAD

**Issue by aren55555** [emberjs/website#2716]
I just used the search bar on emberjs.com; I pasted in the query `modulePrefix `... nothing happened. I then press `Return`; and the page redirected to `http://emberjs.com/?`. I repeated this a couple of times thinking it was broken. 

Turns out there are actually no results for the `modulePrefix` query. However the search in no way indicates this.

**Comment by acorncom** [comment]
Confirmed, I'm seeing this as well.  However, this seems to be an issue with the docsearch library (https://github.com/algolia/docsearch) that we're using. I'm seeing similar issues when searching on the React website for something that doesn't exist (https://facebook.github.io/react/).

@aren55555 Would you be interested in researching this further to see if you can work out a fix?  Would love to have it resolved, but time is pretty tight on this end.  If we don't find a volunteer, I'll probably just close this for now ...

**Comment by aren55555** [comment]
@acorncom I'm not too familiar with docsearch; but it looks like they have closed a similar issue: https://github.com/algolia/docsearch/issues/92

**Comment by Tonours** [comment]
Hi @acorncom a little fix for this issue is here #2799

**Comment by aren55555** [comment]
@Tonours nicely done - much appreciated.
