### ISSUE TITLE
Outdated Observable.addObserver documentation

### ISSUE THREAD

**Issue by ctusch** [emberjs/website#2759]
The [documentation for Observable.addObserver](http://emberjs.com/api/classes/Ember.Observable.html#method_addObserver) seems outdated. The optional _context_ parameter doesn't seem to exist anymore. The callback only has two arguments: _sender_ and _key_. The other 2 (or 3) arguments aren't passed to the callback.

**Comment by locks** [comment]
Hi @ctusch, thank you for the report. Could you move the issue to https://github.com/emberjs/ember.js? API documentation is generated from Ember's source code, so it'll need to be fixed there!

**Comment by ctusch** [comment]
Oh sorry, you are right. I've opened [a similar issue](https://github.com/emberjs/ember.js/issues/14714) there and am closing this one. Thank you!
