### ISSUE TITLE
Links to tests are broken

### ISSUE THREAD

**Issue by joshross4** [emberjs/website#2766]
From the release and beta channels of the builds pages, the links to the tests do not seem to work.

http://emberjs.com/builds/release
http://builds.emberjs.com/tags/v2.10.1/ember-tests-index.html

http://emberjs.com/builds/beta
http://builds.emberjs.com/tags/v2.11.0-beta.3/ember-tests-index.html

They both have a "NoSuchKey" error.

**Comment by acorncom** [comment]
We run into the above when clicking the link shown here:

![screen shot 2017-02-13 at 10 09 58 pm](https://cloud.githubusercontent.com/assets/802505/22916062/303cc42e-f239-11e6-9977-76eb047ee6c3.png)

The builds page is now built using https://github.com/ember-learn/builds and it's possible that that index.html file is no longer generated ...

**Comment by ajomadlabs** [comment]
@acorncom Can I take up this

**Comment by acorncom** [comment]
@ajomadlabs Absolutely! 😀

**Comment by jessica-jordan** [comment]
It seems the link to the `tests` link has already been removed by now in the [way @acorncom suggested above](https://github.com/emberjs/website/issues/2766#issuecomment-279610030):

<img width="624" alt="capture d ecran 2018-10-02 a 15 37 12" src="https://user-images.githubusercontent.com/8811742/46352092-3d70ed00-c659-11e8-8055-13803835fa26.png">

This seems good to be closed :+1:
