### ISSUE TITLE
Update main navigation

### ISSUE THREAD

**Issue by locks** [emberjs/website#2771]
- [x] Remove About (https://github.com/emberjs/website/pull/2767)
- [ ] Replace Guides with Learn dropdown. Dropdown:
  - [ ] Learn
  - [ ] Tutorial
  - [ ] Guides
  - [ ] Deprecations
- [ ] Make API a dropdown. Dropdown:
  - [ ] Ember
  - [ ] Ember Data
  - [ ] Ember CLI (needs to update styling to match)

@emberjs/learning-team-managers 
@MelSumner

**Comment by MelSumner** [comment]
Learn is both the main nav item and the first sub-nav item?

**Comment by MelSumner** [comment]
Also what about ember-engines or is that not ready for prime time yet?

**Comment by locks** [comment]
> Learn is both the main nav item and the first sub-nav item?

I'm not sure how to solve that one, because I want to link people to the learn page itself :\

> Also what about ember-engines or is that not ready for prime time yet?

Engines and fastboot are not 1.0.0 yet, though you could use them in production. Which is to say, we need to figure out how to best link the websites together.
