### ISSUE TITLE
Add a noindex meta tag to /internal pages

### ISSUE THREAD

**Issue by locks** [emberjs/website#2778]
We've recently split up our API documentation into framework user (`/api`), and framework developer (`/internal`) endpoints.
The internal API documentation section of the website should not be indexed by automated bots.

**Comment by acorncom** [comment]
Based on a quick glance (don't have time to send in a PR right now), we may be able to add the following to the beginning of each of the internal pages and then add the appropriate `noindex` meta tag much like we do here (https://github.com/emberjs/website/blob/master/source/layout.erb#L18-L20)

```
---
no_index: true
---
```

Pages we'll need to adjust:

- https://github.com/emberjs/website/blob/master/source/internal_api/class.html.erb
- https://github.com/emberjs/website/blob/master/source/internal_api/module.html.erb

**Comment by locks** [comment]
Fixed by referenced merged PR!
