### ISSUE TITLE
Add deprecation guide for ds.deprecated-initializers

### ISSUE THREAD

**Issue by jenweber** [emberjs/website#2780]
- RFC: https://github.com/emberjs/rfcs/pull/181
- Ember PR: https://github.com/emberjs/data/pull/4657

id: 'ds.deprecated-initializers',
until: '3.0.0'

@locks should this go under a pending features header or elsewhere? Is there anything else I should know besides what is in the RFC? This seems pretty straightforward.

**Comment by locks** [comment]
> @locks should this go under a pending features header or elsewhere?

Yup, pending features sounds good!

> Is there anything else I should know besides what is in the RFC?

Nope, that's it really, very straightforward update of a string!
