### ISSUE TITLE
Broken link in RSVP.Promise documentation

### ISSUE THREAD

**Issue by williamhaley** [emberjs/website#2789]
The link to the promise.js source seems to be broken in the [RSVP.Promise API docs](http://emberjs.com/api/classes/RSVP.Promise.html).

The link in that doc for **DEFINED IN: bower_components/rsvp/lib/rsvp/promise.js:30** results in a 404 for me.

![screenshot at 2017-01-22 12-35-25](https://cloud.githubusercontent.com/assets/1851748/22184815/4543065e-e09f-11e6-9463-4d28be457927.png)

 It currently links here: https://github.com/emberjs/ember.js/tree/v2.10.0/bower_components/rsvp/lib/rsvp/promise.js#L30

The problem seems to be here: https://github.com/emberjs/emberjs.github.com/blob/master/api/classes/RSVP.Promise.html#L607

**Comment by locks** [comment]
Thanks for reporting. API documentation is automatically generated from the source code, and I'm not quite sure how to fix this.

**Comment by locks** [comment]
This seems fixed as of late.
