### ISSUE TITLE
Confusion in Node LTS support blog post

### ISSUE THREAD

**Issue by locks** [emberjs/website#2795]
Original: https://github.com/emberjs/ember.js/issues/14893

> At http://emberjs.com/blog/2016/09/07/ember-node-lts-support.html, it says that Ember prefers the current Active LTS version of node and specifies Node.js v4.5.0 and then links to the Nodejs downloads page.  However, the linked to page says that the current Active LTS is 6.9.2.  So, for maximum Ember compatibility, should we use Node.js 4.5.0 or 6.9.2?
>
>I realize that this Ember doc may be out of date, but could we update it?  It's confusing to see conflicting statements about dep versions.  I'd be happy to help with edits if there's a desire ...
>
>Thanks!

— @joelpresence

**Comment by locks** [comment]
Hi @joelpresence, thanks for your feedback. The page in question is a blog post with a date stamp, which is slightly different from documentation that needs to be kept up to date. If you notice, the text says "At present that is Node.js v4.5.0.", because the active LTS will change as time goes on.
I think we could possibly move the link from the version number to `"Active LTS"` to be less confusing.

cc @nathanhammond

**Comment by joelpresence** [comment]
@locks thanks for the response.  :-)  I realize it's a blog post.  However, it's also *the very first* Google search result that comes up when I search for "ember nodejs version".  So, I'm politely suggesting that either some better SEO needs to be done to land on a more up to date page for that query or maybe update that page?  Otherwise, as it stands, it feels likely that it will confuse others in future and they might file annoying GH issues like me ;-)

I'm just trying to be helpful, not trying to be nitpicky or argumentative ... :-)

**Comment by locks** [comment]
Does my suggestion help? I agree that having a version number with a link that ends up in a page with a different version number is confusing.
I don't think we should keep updating the blog post as new LTS releases come out, but I do think we can improve the wording to make it clear that you need to consult the Node website to see what the current version is.

**Comment by joelpresence** [comment]
It does, thanks.

The problem is that I got a version in my Heroku ember deploy saying that Ember does not support node 7.4.0 and that stuff may break.  So I saw the post about 4.5.0 but I'm running 6.9.1 locally, so it lead to some confusion ...

**Comment by locks** [comment]
Can you post the full warning? I've seen it, and was trying to reproduce to make sure what it says, but I can't find it!

**Comment by joelpresence** [comment]
remote: WARNING: Node v7.4.0 has currently not been tested against Ember CLI and may result in unexpected behaviour.

**Comment by nathanhammond** [comment]
@joelpresence Your warning is to be expected if you're using an outdated version of Ember CLI with a brand new version of Node. Not a bug. We've already improved that error message: https://github.com/ember-cli/ember-cli/blob/594fca16260d33bfb883cfdedb4f2923e9c70211/lib/cli/cli.js#L127

The improved error message has reduced traffic to that blog post, and the wording in the blog post repeats twice to use the Active LTS, and says, "at present" just before providing the 4.X versioned link.

@joelpresence If you'd like to open a PR to reword that sentence in a way you'd have found more understandable we'll consider it. "At time of publishing this blog post," or something.
