### ISSUE TITLE
Add deprecation page entry for `factoryFor` API.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/website#2796]
- [ ] Add to Ember 2.12 deprecations
- [ ] Update deprecation URL's in emberjs/ember.js to point to the final URL

---

The deprecation can suggest the usage of `ember-factory-for-polyfill` (if an addon only needs Ember 2.3+ support) or `ember-getowner-polyfill` (supports 1.10+) for addons.

For apps, things are somewhat simpler `getOwner(this)._lookupFactory('some:thing')` -> `getOwner(this).factoryFor('some:thing')`.

**Comment by jenweber** [comment]
On it.

[RFC](https://github.com/emberjs/rfcs/blob/master/text/0150-factory-for.md) 

Notes to self: _lookupFactory was a private API mechanism, used primarily for passing in arguments when creating an instance of a factory. It's been replaced by the public API method factoryFor.

**Comment by jenweber** [comment]
@rwjblue or @locks Do you prefer opening issues in each repo, or would you just reference this issue in commits on both repos? Just trying to generally gauge how you like to manage issues when the task spans multiple repos.

[PR submitted](https://github.com/emberjs/website/pull/2800)

**Comment by rwjblue** [comment]
I'd just reference this meta issues from the Ember PR, but honestly it isn't something we are sticklers about anyways. We are mostly just happy for the help.
