### ISSUE TITLE
Uses of observers should be avoided in docs wherever possible

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/website#2833]
See http://emberjs.com/api/classes/Ember.Helper.html#method_recompute

**Comment by jessica-jordan** [comment]
In this particular example, I wouldn't even know how to update the code example while still being able to highlight how `compute` works. Do you have a suggestion @Gaurav0? 

If not, I'd suggest that this issue could be closed for now

**Comment by Gaurav0** [comment]
It may not be possible in this case. I opened the issue to highlight this usage.
