### ISSUE TITLE
Redirect `/tomster/*` to `/mascots/*`

### ISSUE THREAD

**Issue by locks** [emberjs/website#2834]
See title.

**Comment by acorncom** [comment]
We're interested in replacing the Tomster url by having /mascots/ in the url instead.  Example pages where this isn't working as we desire now would be when visiting: http://emberjs.com/tomster/faq/  You can also see https://github.com/emberjs/website/commit/be3a97011e66ca2b786dde369d817937989d0a16 as another example of some of the work we've been doing to replace the strict use of Tomster and instead to broaden the mascot idea.

As part of a solution to this issue, we'd also like to have 301 permanent redirects setup for older pages so any links to the pages we're replacing properly end up in the right place.  Details on how to do that on our website can be found in the docs for our Heroku build pack (https://github.com/heroku/heroku-buildpack-static#custom-redirects) and this file would need to be edited: https://github.com/emberjs/website/blob/master/static.json

**Comment by dxr27kejj** [comment]
@acorncom Hello! I am new to github and I want to contribute to this issue if you don't mind.
Should I change the code in static.json to 
`"redirects": {
    "/tomster/": {
      "url": "/mascots",
      "status": 301
    }
  }`
And do I need to use proxy as in your example?

**Comment by sivakumar-kailasam** [comment]
@dxr27kejj Adding the following to the [redirects section in static.json](https://github.com/emberjs/website/blob/master/static.json#L21) will result in the expected behavior.

```json
"/tomster":  {
    "url": "/mascots"
} 
```
