### ISSUE TITLE
Ember Inflector

### ISSUE THREAD

**Issue by rogeliorv** [emberjs/website#2837]
http://emberjs.com/api/data/classes/Ember.Inflector.html

Docs are missing a set of brackets in plurals and singular.

Doc states:  

```
var rules = {
  plurals:  [ /$/, 's' ],
  singular: [ /\s$/, '' ],
  irregularPairs: [
    [ 'cow', 'kine' ]
  ],
  uncountable: [ 'fish' ]
};

var inflector = new Ember.Inflector(rules);
```

Should be: 
```
var rules = {
  plurals:  [[ /$/, 's' ]],
  singular: [[ /\s$/, '' ]],
  irregularPairs: [
    [ 'cow', 'kine' ]
  ],
  uncountable: [ 'fish' ]
};

var inflector = new Ember.Inflector(rules);
```

**Comment by acorncom** [comment]
@rogeliorv Would you mind opening a PR on this repo to fix that? https://github.com/emberjs/ember-inflector/blob/master/addon/lib/system/inflector.js When that's done, please post here and we'll make sure that gets merged ...

**Comment by locks** [comment]
Somehow I got the wrong URL in the PR description. This is merged.
