### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by Serabe** [emberjs/website#2838]
Though emberjs.com is not supposed to be under https, when googling for Emberjs, users will get a link to https://emberjs.com.

Moved here from emberjs/ember.js#15025

**Comment by acorncom** [comment]
I just checked on this and there is not much we can do at the moment.  Google Webmaster Tools has no recourse on this (and there are lots of pages with people asking for help on resolving it).  We will be moving to Heroku for the main website tomorrow (https://github.com/emberjs/website/pull/2828) which should allow us to resolve that more permanently.

**Comment by Serabe** [comment]
Closing this as it is now solved. Thank you @acorncom!
