### ISSUE TITLE
404 for Routing - Preventing and trying transitions

### ISSUE THREAD

**Issue by cah-danmonroe** [emberjs/website#2845]
https://guides.emberjs.com/v2.12.0/routing/preventing-and-retrying-transitions/

**Comment by acorncom** [comment]
Hmm, I just tried this and it's working smoothly in my end. Are you still seeing issues?

**Comment by cah-danmonroe** [comment]
Hi,

Yes, it is still a 404 for me.  Other people in Slack are also reporting related issues.  One person reported https://guides.emberjs.com/v2.12.0/routing/ as a 404 but that one is working for me.  Looks to be a cert issue?

Dan

**Comment by locks** [comment]
Thank you for reporting! We are now tracking this at https://github.com/emberjs/guides/issues/1858 as the Guides are deployed to a different infrastructure to the website at the moment.
Several people, me included, have reported that the re-deploy fixed the problem. Please confirm on the linked issue!
