### ISSUE TITLE
Observer guide needs a better disclaimer/warning

### ISSUE THREAD

**Issue by martndemus** [emberjs/website#2865]
As a best practices consultant I've run more than once into clients justifying using Observers because they are in the guides. There is a paragraph in there that warns readers that they might not be a good idea, but it's easily glossed over and not nearly as explicit enough to convince readers to not use them.

Most often I need to sit them down with Stefan Penners WGE Observer Tip Jar talk to convince them they really are a really bad practice.

I would also be fine with just removing the whole page, as I feel like observers are just a power user feature of the framework.

For reference, I'm talking about this page: https://guides.emberjs.com/v2.12.0/object-model/observers/

**Comment by rwjblue** [comment]
IMHO, we should probably not introduce folks to observers in the guides. It is definitely still support API and whatnot, but I don't think observers should be considered one of the most important things for folks to grok when starting with Ember.

**Comment by martndemus** [comment]
Should I open a PR removing the page from the guides?

**Comment by rwjblue** [comment]
Seems good, but I'd like the leaning team folks to chime in and confirm before landing.

**Comment by locks** [comment]
I'm somewhat wary of removing them from the Guides. Best practices by obscurity haven't worked out for us so far.

**Comment by acorncom** [comment]
> I'm somewhat wary of removing them from the Guides

Ditto.  Seems like we need an power tool icon (or lightning bolt?) along with a "be very careful, here be sharp knives" and a link to Stef's video for background 😀

**Comment by locks** [comment]
Addressed meanwhile.
