### ISSUE TITLE
Problem in Running Middleman command 

### ISSUE THREAD

**Issue by harinath1983** [emberjs/website#2888]
1.When am trying to run middleman command I am facing this problem can anyone please help in this 
   issue 
2. And I have added slick.js in my js folder and tried running the build I can able to see the js file but content it is not referring 
2. need to add CSS file also 

please help me in the above points 

C:\interface_project>middleman
WARN: Unresolved specs during Gem::Specification.reset:
      thor (< 2.0, >= 0.17.0)
      rack (< 3, >= 1.4.5)
      activesupport (< 5.1, >= 3.1, >= 4.2)
      addressable (~> 2.3)
      listen (~> 3.0.0)
      sass (>= 3.4)
      execjs (< 3, >= 0.3.0, ~> 2.0)
      concurrent-ruby (~> 1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
C:/interface_project/config.rb:13:in `evaluate_configuration!': undefined method
 `compass_config' for #<Middleman::ConfigContext:0x000000047f2a70> (NoMethodErro
r)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/mid
dleman-core/application.rb:329:in `instance_eval'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/mid
dleman-core/application.rb:329:in `evaluate_configuration!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/mid
dleman-core/application.rb:286:in `initialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.1/bin/midd
leman:49:in `new'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.1/bin/midd
leman:49:in `<top (required)>'
        from C:/Ruby23-x64/bin/middleman:22:in `load'
        from C:/Ruby23-x64/bin/middleman:22:in `<main>'

C:\interface_project>

**Comment by locks** [comment]
Hi @harinath1983. I am not sure what the problem is, did you do all of the instructions in the README on how to set up the repository locally?

**Comment by harinath1983** [comment]
Yes as per the doc i went

**Comment by acorncom** [comment]
Hello @harinath1983, yes, we've had other people have issues getting Middleman running smoothly on Windows too. Was there some issue on the website you were working on addressing that led to you hitting this problems?

Do you have the same problems if you run these two commands:

```sh
bundle
bundle exec middleman
```

Running `middleman` directly may not work ...

**Comment by locks** [comment]
Closing from inactivity. Please let us know how we can help you further @harinath1983!
