### ISSUE TITLE
Link to ember collection breaks

### ISSUE THREAD

**Issue by plck** [emberjs/website#2891]
There's a link in the description https://github.com/emberjs/ember-collection that doesn't work.
This one https://emberjs.com/ember-collection/

**Comment by acorncom** [comment]
Confirmed.  We've got an outstanding issue at https://github.com/emberjs/ember-collection/issues/147 that discusses this, but the TL;DR is it's a side effect of a new hosting system we shifted to in the last few months.  Will close this issue for now in favor of the above issue
