### ISSUE TITLE
'ember new' does not create a bower.json file beginning with 2.13

### ISSUE THREAD

**Issue by myartsev** [emberjs/website#2896]
Docs need to be updated to take this into account, as a lot of the current documentation actively mentions bower and assumes the config file is created by the CLI.

For example: [https://guides.emberjs.com/v2.13.0/tutorial/ember-cli/#toc_directory-structure](https://guides.emberjs.com/v2.13.0/tutorial/ember-cli/#toc_directory-structure)

**Comment by locks** [comment]
Thanks for reporting, I've fixed the bower mentions in this page in https://github.com/emberjs/guides/commit/c2291c88c539756fbec7f225240506659e85b167.
If you find more of them please file them at https://github.com/emberjs/guides/issues !
