### ISSUE TITLE
Routing docs/examples should show how multi-word model names are converted

### ISSUE THREAD

**Issue by dlee** [emberjs/website#290]
http://emberjs.com/guides/routing/defining-your-routes/ only uses simple model names such as Post and Comment, and does not show how multi-words would be converted between the various name conventions (model, path, ID param, controller, template, etc).

For example, if I have a model named `BigMac`, I don't know if the resource path should be `/big_macs/:big_mac_id` or `/big_macs/:bigMac_id`. It also doesn't show if the route name would be `big_macs` or `bigMacs`, or if the template name should be `big_macs` or `bigMacs`

**Comment by fguillen** [comment]
What about the:

* file name?: `big_mac.js` or `bigMac.js` or `big-mac.js`?
* DS relations: `DS:hasMany('bigMac')` or `DS:hasMany('big_mac')` ...?
* DS.store: `store.findRecord('bigMac')` or `store.findRecord('big_mac')` ...?

?

**Comment by acorncom** [comment]
If there are further tweaks needed on the guides, please open an issue in the guides repo: https://github.com/emberjs/guides/issues

**Comment by dlee** [comment]
@acorncom This issue is still not fixed. Do you want me to open a duplicate issue?

**Comment by locks** [comment]
@dlee yup, in the linked repository
