### ISSUE TITLE
beta & canary instructions need updating

### ISSUE THREAD

**Issue by knownasilya** [emberjs/website#2901]
https://emberjs.com/builds/canary still shows `bower` as the way to use canary and beta (other link).

**Comment by locks** [comment]
The only way to use Ember data is through `bower`. Can you send a PR updating the beta instructions?

**Comment by knownasilya** [comment]
Was talking to @rwjblue last night, and he mentioned that Ember is still bower based for canary and beta.

**Comment by jgelens** [comment]
Should this be re-opened for Ember 3>= ?

**Comment by locks** [comment]
I believe @rwjblue is still confirming tarballs are working.

**Comment by knownasilya** [comment]
The 3.0 beta is still on bower though?
