### ISSUE TITLE
Remove usage of ember-middleman gem

### ISSUE THREAD

**Issue by acorncom** [emberjs/website#2909]
Now that we've removed the about page examples:
- https://github.com/emberjs/website/commit/2b192878e77816d8274a2179e00aa4c9e7ca4c98
- https://github.com/emberjs/website/pull/2906

we should also remove the `ember-middleman` gem after confirming that we don't use it anywhere else on the site.  As far as I know we don't ...

**Comment by tricknotes** [comment]
This issue will be closed by https://github.com/emberjs/website/pull/2920 .
I think there are no any problem without it 😄

**Comment by locks** [comment]
Thanks for reminding us, and for your contribution!
