### ISSUE TITLE
Add the Heroku logo to our footer

### ISSUE THREAD

**Issue by acorncom** [emberjs/website#2910]
As part of switching our website to Heroku hosting (with Fastly CDN), we want to add sponsor logos to our footer thanking Heroku (and Fastly in the near future).

@wifelette and I have discussed adding those two logos to the right side of the footer (I've put a rough draft below, but it is definitely rough).  We need someone to champion this project and help it get finished (I don't think I'll have time). Not all the items below have to be done by the same person, but getting the ball rolling on the design is the where this issue has gotten stuck.

This project will be done when:
- [ ] the design has been iterated on (screenshots posted here are probably enough to help the conversation along)
- [ ] @wifelette has signed off on the design
- [ ] the design has been implemented for
  - [ ] website repo (this repo)
  - [ ] guides repo (https://github.com/emberjs/guides)
  - [ ] the api repo (https://github.com/ember-learn/ember-api-docs)

Heroku assets/info:
- [Brand Guidelines](https://www.dropbox.com/s/m6hb2x4s0uog1gg/guidelines.pdf?dl=0)
- [All logo options](https://www.dropbox.com/sh/cd0h7jzalg1m7id/AACI8rneaxZT0VnXhRotMW7ra?dl=0)
- [Logo we likely want to use, see in below screenshot](https://www.dropbox.com/sh/cd0h7jzalg1m7id/AAAmEicKss8ojSd_e3yDofhAa/SVG%20(Vector)?dl=0&preview=heroku-logo-stroke-purple.svg)

Fastly assets/info:
- I don't see any when browsing their site, please comment if you see some and we can update this description

Rough draft:
![screen shot 2017-06-01 at 12 32 24 pm](https://cloud.githubusercontent.com/assets/802505/26694984/7dbbb372-46c6-11e7-8a3d-4642e320c1d5.png)

**Comment by wifelette** [comment]
First design thought: these need to have a clear indication of _why_ they're there. So above or below the logo, "Hosted by", "CDN provided by" etc. A la https://rubygems.org/, though I'm not directing us there for _design_ tips :p 

Thoughts? I don't have time to play with the CSS myself right now, plus it's not precisely my area, but that's probably the most useful starting direction.

**Comment by toddjordan** [comment]
cc @jenweber

**Comment by amyrlam** [comment]
I'd be game to work on this, I have time this weekend. (Also I can get the Fastly asset, cause I work there.)
