### ISSUE TITLE
ember-metal.model_factory_injections anchor is broken?

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/website#2912]
The anchor for the `ember-metal.model_factory_injections` deprecation has an unexpected pair of `-em-`'s in it around `factory`:

> https://emberjs.com/deprecations/v2.x/#toc_ember-model-em-factory-em-injections-removed, 

which doesn't match what is being linked to from the [actual deprecation](https://github.com/emberjs/ember.js/blob/d338c608e5ce00eb98d2617f4b2e7d102035b6e4/packages/ember/lib/index.js#L188).

I was going to make a PR to ember to fix the link but this seems like it shouldn't be happening in the first place as I don't see any other anchors on https://emberjs.com/deprecations/v2.x with these `-em-`s in them.  Is there a reason this is happening?

**Comment by locks** [comment]
It's reading `model_factory_injections` as though `factory` should be italicised :x

**Comment by Dhaulagiri** [comment]
Yeah, looking through the other ids none of the other ones have the two `_` in them so it makes sense why this is happening.  It's probably too late to change the actual deprecation id at this point, so I could at least get the link updated so it goes to the right place.  Sound good?
