### ISSUE TITLE
Add padding to Ember user logos in the grid

### ISSUE THREAD

**Issue by locks** [emberjs/website#2918]
At the moment, the logos in the grid at `/ember-users` does not have any padding.
As some of the submitted logos don't have padding built into the image, they touch the edges and don't look that good.

Thus, the task is to add some padding to these:

![screen shot 2017-06-12 at 10 47 27 am](https://user-images.githubusercontent.com/118005/27047378-be30432a-4f5c-11e7-8e1e-d924fa351c63.png)

cc @robustdj

**Comment by robustdj** [comment]
@locks Won't this add extra padding to logos that already have padding in the image?

**Comment by locks** [comment]
It would, but ['tis a price we're willing to pay](https://github.com/emberjs/website/pull/2916#issuecomment-307869000).
