### ISSUE TITLE
Huge amount of image data for ember users page

### ISSUE THREAD

**Issue by simonihmig** [emberjs/website#2923]
Just stumpled upon the fact, that the aggregated file size of all logo images on https://emberjs.com/ember-users/ is pretty huge, even on my desktop machine it took a while to load (>6s), probably quite unusable on a mobile phone with a slow connection:

![image](https://user-images.githubusercontent.com/1325249/27325229-04ca3c04-55a8-11e7-9dfa-28932ac97635.png)

A lot of the logos are way too large given their small size, some of them seem to include unnecessary meta data (Adobe Fireworks stuff, maybe color profiles as well). But even the smaller ones could be compressed much better without a noticeable loss of quality, by converting them from raw PNG24 to optimized PNG8.

This could be done manually for the existing files (e.g. by using some service like https://tinypng.com/) and requiring new submissions to do the same, or by adding some optimization step to the build process (running some CLI tool like https://pngquant.org/). (*I have no idea about Ruby and Middleman, so I cannot be of any help there...*)

**Comment by wifelette** [comment]
Hi @simonihmig—

Agreed, this has been on our backburner radar for a bit :) 

I was chatting with @locks about it and he said running as part of the build step sounded ok, but that it would of course depend on how long it took. 

Is this something you'd be game for experimenting with? Doing a manual run and then submitting a PR? We'd love the help!
