### ISSUE TITLE
No main navigation in FireFox 54.0

### ISSUE THREAD

**Issue by filippovdaniil** [emberjs/website#2932]
&nbsp; | &nbsp; |
----: | ---- |
**Operating system**: | Debian GNU/Linux |
**Browser**: | FireFox 54.0 (64-bit) |
**Issue**: | There is no main navigation at the website [index page](https://emberjs.com/)
**Cause**: | ```window.customElements``` is undefined
**Possible solution**: | To use legacy [```Document.registerElement```](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement)

### Screenshot:

![screenshot](https://user-images.githubusercontent.com/154306/27591161-138dfa40-5b7b-11e7-8ffd-6e75fb281df1.png)

### Console error output:

![console-output](https://user-images.githubusercontent.com/154306/27591286-680bfa18-5b7b-11e7-88b6-6454e3dc76f6.png)

**Comment by locks** [comment]
@filippovdaniil Thank you for the thorough report! I forgot to add the shim for custom elements yesterday. Curiously, the footer was also missing but since it's a footer people hadn't realized ;)
The fix has been deployed and is now working on my Firefox. Please let me know if the problem persists, or any new problem you might encounter!

**Comment by filippovdaniil** [comment]
@locks, yep, everything is working now :)

By the way, is it planned to add server-side rendering (like fastboot) for these custom elements? In the page source I only see

```html
<main-navbar></main-navbar>
...
<main-footer></main-footer>
```

— as far as I know, it can negatively affect SEO.

**Comment by locks** [comment]
> By the way, is it planned to add server-side rendering (like fastboot) for these custom elements?

Likely, but in the slightly longer term.
The idea is to migrate nibble by nibble over to Ember/Glimmer.
