### ISSUE TITLE
Background color for sponsors

### ISSUE THREAD

**Issue by locks** [emberjs/website#2957]
Change the background color of the sponsor grid items, because it looks off at the moment.

**Comment by qZzQ1** [comment]
Hi,
I have add a new background for your items sponsors but i can't create a new branch in you project for a PR.

![background-items](https://user-images.githubusercontent.com/8742090/29522644-277e9796-868a-11e7-8ae0-cc94863f30ef.png)

**Comment by wifelette** [comment]
Hi @qZzQ1 The color was previously a light grey :) An orange like this is alas too big of a change that would result in many folks needing to change their logos. We need a super neutral color, though @MelSumner may have some feedback about best options for contrast.

**Comment by qZzQ1** [comment]
Hi @wifelette, ok I see but whit seamless background-image is not good for you? Or neutral color is compulsory?

![background-seamless-ember](https://user-images.githubusercontent.com/8742090/29609421-729d4236-87f7-11e7-9c2a-92852d681e59.png)

**Comment by MelSumner** [comment]
the pattern background will not be sufficient for accessibility purposes. What about a solid square border instead? @wifelette it would coordinate with the other things I'm working for the website too. 
![image](https://user-images.githubusercontent.com/4587451/29615820-eb20d83a-87d4-11e7-9fb5-ef0cca848fa6.png)

**Comment by wifelette** [comment]
I'm not loving the aesthetics of the bold outline... but is it that it's the only good way to make it more accessible? Any ideas for something more attractive? I'd also love to see the other things you're referencing @MelSumner, might give me a better sense of it so I could make more useful suggestions :) Chat on Slack?

**Comment by wifelette** [comment]
PS, @qZzQ1, it isn't lost on me that we totally tagged this as `help wanted` _and_ `good for new contributors` and that it turns out to be slightly more complicated than that :p THANKS for your attempts, regardless of where we land <3 <3 <3

**Comment by qZzQ1** [comment]
No problem @wifelette and thanks ^^ :+1: , I have a last idea but later I would have no it anymore ^^ I take the bold outline of @MelSumner and I cut this for more attractive.

![capture du 2017-08-24 09-36-53](https://user-images.githubusercontent.com/8742090/29655724-3ccbf970-88b2-11e7-94c4-4b00cbec8f6e.png)

**Comment by xtuc** [comment]
The last one is looking amazing @qZzQ1. It doesn't feel as bold as https://github.com/emberjs/website/issues/2957#issuecomment-324314318.

@wifelette 
I took the liberty to publish the beginner-friendly issues from Ember on https://beta.contributor.ninja.

**Comment by acorncom** [comment]
I like the looks of https://github.com/emberjs/website/issues/2957#issuecomment-324562133 myself, 👍

**Comment by wifelette** [comment]
Indeed, it's a good compromise :) That said, I don't fully understand the accessibility issues. Assigning to someone who does to hopefully investigate!

**Comment by qZzQ1** [comment]
Hi, ok @wifelette I wait for the response of @MelSumner, thanks ^^

**Comment by devshiva619** [comment]
@locks is there anything to be still done in this ? If so I will surely like to work for it

**Comment by MelSumner** [comment]
@locks @devshiva619 we could move forward with the in-between version.

**Comment by wifelette** [comment]
@melindaweathers To be sure, you mean this one, yes?

https://github.com/emberjs/website/issues/2957#issuecomment-324562133

If so, just want to make sure @qZzQ1 also notices this email in case they want to submit the PR :)

**Comment by jkumar712** [comment]
Hi, I just try with the simple version.

`Without hover`
![image](https://user-images.githubusercontent.com/16778890/31437610-77f2b856-aea3-11e7-909f-59d772b2b8fc.png)

`With hover`
![image](https://user-images.githubusercontent.com/16778890/31437638-90d2247e-aea3-11e7-9a7b-9f79393b3c42.png)

**Comment by jkumar712** [comment]
Any update on this?

**Comment by MelSumner** [comment]
I think this looks good @jkumar712

**Comment by jkumar712** [comment]
Raised PR https://github.com/emberjs/website/pull/3076!

**Comment by locks** [comment]
Closed by #3076. Thanks @jkumar712!
