### ISSUE TITLE
Ember Data link on /learn is wrong

### ISSUE THREAD

**Issue by dgading** [emberjs/website#2970]
I was reading the page https://emberjs.com/learn/ and the Ember Data link is linking to https://emberjs.com/api/data/ which returns an "Internal Server Error" message. 

After looking at the API docs pages, I think it should be linking to https://emberjs.com/api/ember-data/

I didn't want to open a pull request right away if I did miss this existing in another Issue.

**Comment by locks** [comment]
@sivakumar-kailasam did we miss a redirect?

**Comment by sivakumar-kailasam** [comment]
Looks like we handled full urls like https://emberjs.com/api/data/classes/DS.RESTAdapter.html but not https://emberjs.com/api/data. Saw your commit for the learn page. I've made changes on the api viewer to now handle this.
