### ISSUE TITLE
Add header search to API section's header

### ISSUE THREAD

**Issue by allthesignals** [emberjs/website#2972]
The header search is available everywhere except the API section. I think when I go to the API section, it's useful to be able to search for documentation, read it, then go back and search again, without needing another window open. I think this would make the API section more useful. 

I'm guessing because the API section is an Ember app, implementing the search dialogue is a bit more complicated. 

If there's any interest, I'll work on a PR.

**Comment by sivakumar-kailasam** [comment]
@allthesignals Thanks for reaching out. Its being tracked via https://github.com/ember-learn/ember-api-docs/issues/275. We would appreciate help with issues marked with the `help wanted` label on the emberjs org repos & on the [api docs](https://github.com/ember-learn/ember-api-docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) as well

**Comment by allthesignals** [comment]
Thanks, @sivakumar-kailasam, but I'm confused - why is that in a different repository and organization? What is ember-learn?

Separately, I would add a note in the README about the "help wanted" label, and even the status of the new api docs - it sounds like you only want outside contributors to focus on those? That was the first place I looked before opening this issue and didn't see anything about it under "contributing."

Thanks!

**Comment by sivakumar-kailasam** [comment]
@allthesignals ember learn is a github org owned by the ember learning sub team. The API docs is an ember app so it exists in a separate repo. Our api docs' readme contains a [section](https://github.com/ember-learn/ember-api-docs#want-to-help-out) on issues that we'd like help with. 

The labels are a general suggestion for new contributors but isn't intended to be the only issues that we seek help on. If you have suggestions on how to improve the wording around it, please raise a PR and we'd be glad to discuss & merge it.
