### ISSUE TITLE
Array.includes docs duplicated

### ISSUE THREAD

**Issue by eccegordo** [emberjs/website#2991]
The same method seems to be duplicated in the docs output.

https://www.emberjs.com/api/ember/2.14/classes/Ember.MutableArray/methods/includes?anchor=includes

![ember_mutablearray_-_2_14_-_ember_api_documentation](https://user-images.githubusercontent.com/497659/30672425-2ac564f8-9e21-11e7-9b75-fcbd77715062.png)

**Comment by acorncom** [comment]
Thanks @eccegordo, just opened an issue for that at https://github.com/ember-learn/ember-api-docs/issues/343  Will close here now
