### ISSUE TITLE
Combine _variables stylesheets

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3013]
**Expected:** 
There should only be one _variables.scss stylesheet. 

**Actual:** 
There are two. There is a _variables.scss stylesheet in source/stylesheets/ and another one in source/stylesheets/base/.

**To Fix:** 
The two stylesheets should be merged, and there should only be one in source/stylesheets/base.

**Comment by Minimilk93** [comment]
I can help with this? :)

**Comment by locks** [comment]
Thanks @anu0012, @Minimilk93 and @shruthigopinath. @anu0012 got here first so we went with that PR.
There is a follow up task at https://github.com/emberjs/website/issues/3029, please comment that you are picking up the task so we avoid duplicates. See you in the next PR! :D
