### ISSUE TITLE
og:image and twitter:image point to 404'd images

### ISSUE THREAD

**Issue by chadhietala** [emberjs/website#3018]
A lot of social media sites will look at these to take to display an image for the page. This seems to be broken.

<img width="1354" alt="screen shot 2017-10-10 at 7 33 38 pm" src="https://user-images.githubusercontent.com/183799/31415535-0eebe0f0-adf2-11e7-9f59-56086351fb27.png">
<img width="1611" alt="screen shot 2017-10-10 at 7 33 49 pm" src="https://user-images.githubusercontent.com/183799/31415536-1158220e-adf2-11e7-9966-9059ea348b64.png">

This ends up looking like this:

<img width="553" alt="screen shot 2017-10-10 at 7 33 58 pm" src="https://user-images.githubusercontent.com/183799/31415543-1b05b50a-adf2-11e7-97cf-599b1be4e162.png">

**Comment by NullVoxPopuli** [comment]
what is the image supposed to be?  just a small screenshot of the article?

**Comment by chadhietala** [comment]
@NullVoxPopuli I think its supposed to be Tomster.

**Comment by NullVoxPopuli** [comment]
@chadhietala yeah, I think middleman has some limitations around the use of images in meta tags, so I just excluded the image(s) from the asset fingerprinting

**Comment by acorncom** [comment]
Closed by #3020
