### ISSUE TITLE
Address heading inconsistencies in the CSS

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3028]
**Expected:** 
The heading elements should be consistent across all pages. 

**Actual:**
The heading elements are not consistent across all pages. 

**To Fix- 5 Steps:** 
1. move all of the h1, h2, h3 and h4 elements out of each *.scss file & put them in the source/stylesheets/base/_typography.scss file. 

2. set these variables in the source/stylesheets/base/_variables.scss file: 
```
$orange: #E04E39;
$orange-darker: darken($orange, 10);
$orange-darkest: darken($orange, 20);
```
3. Set the following values: 
```
html {
	font-size: 16px;
}
body {
	font-size: 1em;
	line-height: 1.7;
}
h1, h2, h3, h4 {
	line-height: 1;
	margin-top: 1.25em; 
	margin-bottom: 0.5em;
}
h1 {
	color: $orange;
	font-size: 3.157em;
}
h2 {
	color: $orange-darker;
	font-size: 2.369em;
}
h3 {
	color: $orange-darkest;
	font-size: 1.777em;
}
h4 {
        color: #222;
        font-size: 1.333em;
}
```
4. ensure that no CSS is nested in other files that would conflict with these items. 
5. ensure that the site builds correctly and visually confirm that the pages appear balance- include screenshots in the PR.

**Comment by Anisha1234** [comment]
I would like to take this one on :)

**Comment by locks** [comment]
@Anisha1234 thank you for taking it up! Let us know if you have any problems.
