### ISSUE TITLE
Remove duplicate rules from stylesheets

### ISSUE THREAD

**Issue by locks** [emberjs/website#3029]
Due to some duplication in the SCSS files, we have several rules that are duplicated, for example https://github.com/emberjs/website/blob/master/source/stylesheets/base/_variables.scss#L37 and https://github.com/emberjs/website/blob/master/source/stylesheets/base/_variables.scss#L53.

The task is to clean these up, also removing any commented out styles.

**Comment by zzbazinga** [comment]
I would like to take this one on :)
