### ISSUE TITLE
Feature: indicate guest or syndicated blog post

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3049]
Feature: allow for indication of syndicated or guest blog posts. 

- [ ] Blog posts should have a tag that indicates regular, syndicated or guest post. 
- [ ] when tagged as "guest post" (or similar), the blog post should say "Guest Post" under the blog title but above the "posted by" author line. 
- [ ] add the class "blog-post-title" to the h2 in the title. 
- [ ] CSS: add margin-bottom: 0; to that h2.blog-post-title class. 
- [ ] insert the tag information after the h2 of the blog post title: 
`<span class="post-tag">Guest Post</span>` 
- [ ] CSS: add the class .post-tag in the scope of the blog SCSS
`.post-tag {
  color: #4d4d4d;
  font-size: 1em;
  font-weight: bold;
`
- [ ] when tagged as a "syndicated post" (or similar), it should say "Syndicated Post" under the blog title but above the posted by author line. 
- [ ] when tagged as a syndicated post (only) , the bottom of the post should have a line at the bottom: "Originally posted at (url)."

**Comment by MelSumner** [comment]
@locks

**Comment by pbishop16** [comment]
@MelSumner I would like to tackle this.

**Comment by pbishop16** [comment]
@MelSumner Just wanted to double check the styling with you. Do you have concerns with the below?

![image](https://user-images.githubusercontent.com/4172262/32924040-647ccf72-cb00-11e7-970c-472983d17333.png)

![image](https://user-images.githubusercontent.com/4172262/32924239-40442d48-cb01-11e7-9bb5-cb1ea0e4c188.png)

**Comment by pbishop16** [comment]
@MelSumner Added the below to the blog post page

![image](https://user-images.githubusercontent.com/4172262/33004238-402672e0-cd85-11e7-9748-3b850ddcfea9.png)

The original url for a syndicated post:
![image](https://user-images.githubusercontent.com/4172262/33004251-58ca245e-cd85-11e7-87a7-9909fbb206d6.png)
