### ISSUE TITLE
Users listing page asks for submit form first

### ISSUE THREAD

**Issue by sarupbanskota** [emberjs/website#3052]
<img width="561" alt="screen shot 2017-10-28 at 12 17 36 pm" src="https://user-images.githubusercontent.com/3149580/32133533-1dec2038-bbda-11e7-98c1-fc08fffa3218.png">

Probably meant to say `PR first and then form` because it asks for the PR

**Comment by wifelette** [comment]
Agreed! Would welcome a PR to fix the instructions 👍

**Comment by lukesargeant** [comment]
I had a quick look into this and couldn't find the code in the website repo. Perhaps this form is configured at airtable.com?

**Comment by wifelette** [comment]
SORRY to drive people nutty 😢 I didn't read this correctly and thought the instructions _in the Yaml file_ were the problem. It is indeed Airtable and I just fixed it!

**Comment by lukesargeant** [comment]
No trouble, nice one! 👍
