### ISSUE TITLE
Navbar does not display in IE

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3066]
**Expected:**
Navbar should display for all browsers. 

**Actual:** 
Navbar does not display for IE11.

**To-Fix:** 
Determine the root cause & resolve it. 

**Screenshot:**
![image](https://user-images.githubusercontent.com/4587451/32252095-c63b1666-be61-11e7-9529-ff2307d80693.png)

**Comment by rwjblue** [comment]
@MelSumner - Which version?

**Comment by MelSumner** [comment]
@rwjblue apologies, should have included. IE 11 (11.0.9600.18816)

**Comment by locks** [comment]
We are using Glimmer.js for the header and footer, which don't support IE, as far as I know.

**Comment by acorncom** [comment]
@rwjblue @locks Given the desire to continue support for IE 11 in Ember 3.0, should we consider switching away from Glimmer components used on the website? We could theoretically argue that although Ember 3.0 itself will continue supporting IE 11 that we as the learning team don't actively support it. But that seems to be a decision via fiat and not something that we've actually decided / landed on as a team (or with core).

Thoughts?

**Comment by MelSumner** [comment]
Closing this issue since it will be resolved with #3082
