### ISSUE TITLE
Builds page: CTA needs responsive update

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3069]
**Context**
The call to action (CTA) on the builds page should still appear proportionally sized no matter what the viewport. Currently, it is wrapping in a strange way. 

Screenshot:
![image](https://user-images.githubusercontent.com/4587451/32628409-62268be6-c55b-11e7-9e7a-16c250623e1a.png)

**To Fix**
- [ ] use CSS to style the CTA appropriately for the viewports already supported in the styles

**Comment by jkumar712** [comment]
![image](https://user-images.githubusercontent.com/16778890/33129827-533c4e98-cfb7-11e7-993b-4f2af622c2ed.png)

Is it ok?
