### ISSUE TITLE
Ember 2.16 @ember/object API docs are confusing

### ISSUE THREAD

**Issue by petey** [emberjs/website#3073]
There are numerous components under @ ember/object that have confusing documentation, largely because it looks like they haven't been updated from ember 2.15. Today, namely, I've spent far too much time hunting down exactly what I need to use to pull in `ObjectProxy` and `PromiseProxyMixin`. There is nowhere in this documentation that mentions:

```
import PromiseProxyMixin from '@ember/object/promise-proxy-mixin';
import ObjectProxy from '@ember/object/proxy';
```

I also looked at the api docs, release blog post, [RFC](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) which makes no mention of these component changes, and tried to find something in the code for `ember-modules-codemod` but didn't easily see how anything maps. Eventually I only got the correct imports by using the ember 2.15 imports, and run ember-modules-codemod against it.

Please update the examples for these, and other scoped modules to have the correct imports listed in either the examples or the TOC.

https://emberjs.com/api/ember/2.16/classes/ObjectProxy
https://emberjs.com/api/ember/2.16/classes/PromiseProxyMixin

**Comment by locks** [comment]
Hi @petey, currently the source of truth for the mappings is https://github.com/ember-cli/ember-rfc176-data. That is what the codemod also uses.
Having the imports listed is something we have planned, would you be able to help us implement it?

**Comment by toddjordan** [comment]
@petey this is a known todo and is represented in https://github.com/ember-learn/ember-api-docs/issues/360  

Will add some extra details on some implementation possibilities...
Also, the current state of the api is represented in https://github.com/ember-learn/ember-api-docs/issues/344

Let us know if you are willing/able to help :-)

Closing as the other issues represent the same concerns...
