### ISSUE TITLE
Create new page for LTS information

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3074]
**Context:**
The LTS process was thoroughly explained in a blog post, but really should have its own page so it can permanently and easily be found with the rest of the releases information. 

**Steps to Implement:**
- [ ] create page that points to /releases/lts
- [ ] visit https://emberjs.com/blog/2016/02/25/announcing-embers-first-lts.html and pull that content into the page
- [ ] ensure use of semantic HTML

**Comment by ajomadlabs** [comment]
@wycats Can I take up this issue

**Comment by MelSumner** [comment]
@ajomadlabs we already have this issue taken care of, but thank you!

**Comment by acorncom** [comment]
@ajomadlabs if you're interested in helping in other ways, we've got lots of things we could use help on 😀 Do you happen to be on the Ember Slack?  We find that's sometimes an easier way to organize thoughts about what people can work on to start with ... Find us in the `#-team-learning` channel if you're interested.
