### ISSUE TITLE
Update navbar

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3082]
**To Do:** 
Implement navbar into the current website . 

**Prototype:** 
https://codepen.io/melsumner/pen/b09957277ef32aa0626bf6c227a4e961 

Confirm that it works in all major browsers, and is responsive.

**Comment by jkumar712** [comment]
I shall take it up! Should it be change in `ember-learn/glimmer-styleguide` or add a partial ?

**Comment by MelSumner** [comment]
I think partial, because the current Glimmer one isn't rendering in IE.

**Comment by jkumar712** [comment]
I am working on. Will raise PR within this week.

**Comment by locks** [comment]
By partial do you mean middleman partial?

**Comment by jkumar712** [comment]
@locks Yes, I asked in the mean middleman partial.

**Comment by samselikoff** [comment]
Dropdowns look great on the new navbar!

I felt like the "ember" logo is a bit tight/needs more whitespace, wanted to come here and get yall's thoughts? 

Also what about the gradient (the one that's still on https://emberjs.com/api/ember/2.18/modules/@ember%2Fapplication), I felt like that was a nice touch

**Comment by acorncom** [comment]
@MelSumner Thoughts about Sam's comments here? I'd be inclined to see the nav bar get a tad taller myself so it looks a bit more roomy in the header. I like the gradient as well, but @samselikoff that may have been removed for accessibility reasons in the interests of making things more distinct ...

**Comment by MelSumner** [comment]
@samselikoff @acorncom we could iterate on it- the gradient on the header is something that went away based on feedback that was exactly the opposite. Additionally, there wasn't enough contrast to pass accessibility tests.  

If anyone wanted to help by submitting a PR or comment with a CodePen mockup ([you could just fork the styles in progress if you wanted](https://codepen.io/melsumner/pen/9d551738a81e319a773395a2cfa1a82e)) for https://github.com/ember-learn/ember-styleguide/issues/3 that would probably be the most helpful. The current iteration was only meant to be a stopgap while we transform the parts into components. 

Thanks!
