### ISSUE TITLE
Deprecation guides should be data driven

### ISSUE THREAD

**Issue by locks** [emberjs/website#3100]
Like the status board, the deprecation guides should be driven by data, instead of having to manipulate the markdown.
This would avoid things like having "upcoming deprecations in 2.16", when 2.16 and 2.17 have already been released.

**Comment by rwjblue** [comment]
I’m happy to have the main page be generated based on _something_ but I am very opposed to being forced to maintain markdown within a JSON blob (as I have stated a few times in the past RE: status dashboard).

One possible solution that satisfies both constraints would be having a subdir of individual markdown files that have frontmatter (for various data like `id`, `until`, initial version the deprecation was introduced, etc) which we use to generate the current guide pages.

**Comment by locks** [comment]
@rwjblue you picked the thoughts right from my brain.

**Comment by locks** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Serena Fritsch](https://trello.com/c/dEsQODZv/4-serena-fritsch)

**Comment by serenaf** [comment]
@locks I would like to take this on, do you have any pointers on how the status board was refactored?

**Comment by locks** [comment]
The status board was rebuilt from the ground up as a Glimmerjs application which was then integrated with the main website like the builds page, but I'm not sure we want to do that again.
We could do a page at a time, and set up some visual regression?

**Comment by serenaf** [comment]
Basic idea after chatting with @locks is:
- Have each deprecation in its own markdown file
- name, until and since attributes go into frontmatter
- To Display we read the frontmatter and group by version
- We might/need some sorting by deprecation, but for now sorting by deprecation id might be enough

**Comment by jenweber** [comment]
Closed, new deprecation app is deployed :D
