### ISSUE TITLE
Update last LTS version

### ISSUE THREAD

**Issue by heat** [emberjs/website#3102]
The build web page indicates:
> LONG-TERM SUPPORT (LTS)
> The latest LTS release is 2.12.2, made on April 27th, 2017

The follow post sugests the current version *2.16*. 
https://emberjs.com/blog/2017/10/03/the-road-to-ember-3-0.html

**Comment by locks** [comment]
Thanks for reporting, do you have some type to send over a PR? Moved to https://github.com/ember-learn/builds/issues/54.

**Comment by heat** [comment]
I'll use the new Issue in corrrect project.
