### ISSUE TITLE
Blog headlines have strange fonts

### ISSUE THREAD

**Issue by mixonic** [emberjs/website#3103]
The blog has several font issues:

* There are four different colors and two different font weights.
* Items that were previously CAPS CASE are no longer, for example "Ember.Js". Perhaps these need to be changed in the source.

This leaves the posts pretty difficult to read.

<img width="749" alt="screen shot 2017-12-14 at 12 55 45 pm" src="https://user-images.githubusercontent.com/8752/34015364-0f3247e8-e0d3-11e7-8c2e-8b684d3237d8.png">

**Comment by MelSumner** [comment]
@mixonic thank you for bringing this up. The [styleguide in progress is here](https://codepen.io/melsumner/full/9d551738a81e319a773395a2cfa1a82e/)- any feedback you have would be really awesome. 
One of the difficulties is that everything inextricably linked right now, as of course happens sometimes in multi-year projects with different contributors; we've been working to unravel it and keep the specificity low, going forward. 
This is a specific example where there's some overly-specific CSS that is overriding what we're trying to do. I'll get this fixed ASAP!
