### ISSUE TITLE
Difficulty with Module Imports.

### ISSUE THREAD

**Issue by alexmasita** [emberjs/website#3116]
The API documentation has not fully documented all the module imports.  Am having trouble getting this code to work

```
import ObjectProxy from '@ember/object/objectProxy'; // How do we do this import
import PromiseProxyMixin from '@ember/object/promiseProxyMixin'; //And this?

let ObjectPromiseProxy = Ember.ObjectProxy.extend(Ember.PromiseProxyMixin);

let proxy = ObjectPromiseProxy.create({
  promise: Ember.RSVP.resolve($.getJSON('/some/remote/data.json'))
});

proxy.then(function(json){
   // the json
}, function(reason) {
   // the reason why you have no json
});
```

**Comment by Gaurav0** [comment]
The answers are here: https://github.com/ember-cli/ember-rfc176-data

It would be nice to have a link to this from somewhere on emberjs.com

**Comment by locks** [comment]
Thanks for reporting. This should be mostly addressed by https://github.com/ember-learn/ember-api-docs/pull/413. We have some more ideas to improve API documentation.
