### ISSUE TITLE
Deprecation Guide is not discoverable

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/website#3117]
There is no link to the deprecation guide, and it doesn't appear when one searches for 'deprecation'.

**Comment by acorncom** [comment]
@Gaurav0 We added deprecation guide links to the learn page a while back, does that address what you're after? https://emberjs.com/learn/

**Comment by locks** [comment]
We are also currently reworking the navbar and the sitemap in general to address the general discoverability problem we have.

**Comment by Gaurav0** [comment]
Thanks.
