### ISSUE TITLE
Document missing deprecation guides

### ISSUE THREAD

**Issue by locks** [emberjs/website#3121]
From https://github.com/thoov/ember-2-legacy/blob/master/config/environment.js:
- [x] ~_ENABLE_UNDERSCORE_ACTIONS_SUPPORT~ (private API)
- [x] _ENABLE_RESOLVER_FUNCTION_SUPPORT [Guide](https://emberjs.com/deprecations/v2.x/#toc_registry-resolver-as-function)
- [ ] _ENABLE_REVERSED_OBSERVER_SUPPORT [Source](https://github.com/emberjs/ember.js/pull/15893/files)
- [ ] _ENABLE_ROUTER_RESOURCE [Source](https://github.com/emberjs/ember.js/pull/11517)
- [x] _ENABLE_CURRENT_WHEN_SUPPORT [Source](https://github.com/emberjs/ember.js/pull/11822/files)
- [x] _ENABLE_DEPRECATED_REGISTRY_SUPPORT [Guide](https://emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry)
- [x] _ENABLE_STRING_FMT_SUPPORT [PR](https://github.com/emberjs/website/pull/3120) / [Guide](https://emberjs.com/deprecations/v2.x/#toc_ember-string-fmt)
- [x] _ENABLE_FREEZABLE_SUPPORT [Guide](https://emberjs.com/deprecations/v1.x/#toc_ember-freezable)
- [ ] _ENABLE_PROPERTY_REQUIRED_SUPPORT

**Comment by thoov** [comment]
`_ENABLE_RESOLVER_FUNCTION_SUPPORT` already has a section located here (https://emberjs.com/deprecations/v2.x/#toc_registry-resolver-as-function) so we can mark that as complete. I will create one for _ENABLE_FREEZABLE_SUPPORT

**Comment by thoov** [comment]
_ENABLE_DEPRECATED_REGISTRY_SUPPORT (https://emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry) already exists

**Comment by thoov** [comment]
_ENABLE_PROPERTY_REQUIRED_SUPPORT should be added to deps 1.12 (https://github.com/emberjs/ember.js/pull/10668)

**Comment by cibernox** [comment]
_ENABLE_CURRENT_WHEN_SUPPORT is documented in https://github.com/emberjs/website/pull/3154

**Comment by btecu** [comment]
This can probably be closed.
