### ISSUE TITLE
Setup a Heroku redirect for all old guides files and trash source files

### ISSUE THREAD

**Issue by acorncom** [emberjs/website#3125]
Guides used to be part of this repo. When we wanted to allow versioning of the guides, they were split out into a separate repo and redirect pages were setup in Middleman to help handle the move.

We'd like to clean those old files up now that we can do redirects using Heroku's redirect system instead.

Getting this all tidied up will include:
- [ ] add redirect line(s) to the https://github.com/emberjs/website/blob/master/static.json file to redirect any file as appropriate to the corresponding place at `http://guides.emberjs.com/current`.  Details on how redirects work for the Heroku build pack we use can be found here (https://github.com/heroku/heroku-buildpack-static#custom-redirects)
- [ ] deleting all the `source/guides/*` files that still exist
- [ ] deleting the https://github.com/emberjs/website/blob/master/source/layouts/guide.erb file
- [ ] anything else that I don't know about here 😀

**Comment by jenweber** [comment]
Closed, we fixed this with the migration to the guides-source and guides-app
