### ISSUE TITLE
Improve Teams Page

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3131]
**1. Update information for each team**
For each team listed: 
- [x] include team description
- [x] what projects the team is responsible for
- [x] link to meeting notes
- [x] information when meetings happen
- [x] slack channel information

**2. Separate out each team to its own section**
- [x] separate each team into its own section (#3249)

**Comment by sivakumar-kailasam** [comment]
in case you hadn't noticed, on phones:
![emberjs com_team_ pixel 2 xl](https://user-images.githubusercontent.com/604117/38196877-f94ce156-36a2-11e8-8290-6e08bb4114af.png)

**Comment by MelSumner** [comment]
Thanks @sivakumar-kailasam - the issue should be resolved now :)

**Comment by MelSumner** [comment]
Obtained the necessary information to update the teams page, closing issue.
