### ISSUE TITLE
Improve the "who uses Ember" carousel on the home page.

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3134]
There could be two approaches here: 
1. update the slider used
2. remove that slider (and customizations) and replace it with something different. 

Either approach: 
- should be responsive/device-agnostic
- should complement the current site
- should be accessible (A11y)

**Comment by jenweber** [comment]
@MelSumner would it be bad to just remove the controls altogether? I think they make it look dated.

![screen shot 2018-04-01 at 7 45 26 pm](https://user-images.githubusercontent.com/16627268/38178648-480e16c0-35e5-11e8-9871-ae34be533400.png)

**Comment by acorncom** [comment]
I think in the interests of marketing it might be best to keep it. Given that we’re working uphill against the brand recognition that Facebook and Google add to their frameworks, having some of our own seems sensible ...

**Comment by jenweber** [comment]
@acorncom I mean just remove the ui controls (the bottom bar and arrows) but leave the carousel

**Comment by acorncom** [comment]
@jenweber sorry, I missed that one solitary word 🤕
