### ISSUE TITLE
Add Invitation to Contribute to page layout

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3137]
Goal: to add a "Contribute to this page" link to each page. 

Criteria: 
- must be at the bottom of each page, centered, above the footer
- must link to: https://github.com/emberjs/website 
- should be responsive (device-agnostic)
- should be accessible 
- should complement the existing site design

Guidelines:   
- code should go into the layout.erb file
- css should go into the site.css.scss file (at the bottom of the file is fine)

**Comment by SeanHealy33** [comment]
I've had a quick look at implementing this @MelSumner 

![screenshot from 2018-04-04 12-10-09](https://user-images.githubusercontent.com/6124835/38304386-25aedf60-3801-11e8-8530-7e964b73f85b.png)

Any thoughts on this attempt? It feels like it's a too close to the gear/donate section.

**Comment by MelSumner** [comment]
Thanks for doing this!
