### ISSUE TITLE
Incorrect link to tomster/commission

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3140]
On the tomster/faq page, there is a link to the commission inquiry form, but the link directs to /commission instead of /tomster/commission. 

![image](https://user-images.githubusercontent.com/4587451/34653594-bd56004c-f3b3-11e7-8a03-0e0eb0df6ff3.png)

**Comment by amyrlam** [comment]
👋 I took this issue with https://github.com/emberjs/website/pull/3173

**Comment by locks** [comment]
Fixed by linked PR!
