### ISSUE TITLE
Missing navigation links to Ember.Templates.helpers Class in API docs prior to 2.16

### ISSUE THREAD

**Issue by tambo** [emberjs/website#3169]
There are no navigation links to the Ember.Templates.helpers class in the API docs prior to 2.16. However it is possible to get to the page by manual edit of the url fragment for the Ember version.

This should be fixed as it key information required for building contextual components. The class is not listed in the Classes index in any API guide prior to 2.16, but has apparently been present historically.

**Comment by locks** [comment]
We can't fix this as the documentation is generated from the published Ember source. That said, we can't make breaking changes to the API, so consulting the latest one should be fine!

**Comment by MelSumner** [comment]
@locks making a note that I'd like us to consider a way to either communicate "if missing, consult latest" or think about ways that missing docs could be added.
