### ISSUE TITLE
Move video to the bottom of the community page

### ISSUE THREAD

**Issue by jenweber** [emberjs/website#3218]
The most important content on [this page](https://emberjs.com/community/) is below the fold. The video should go below the meetup and mascots instead.

_Note, this issue is set aside for the EmberConf contributors workshop on 3/12. If it's not claimed by the end of that day, feel free to grab it!_

**Comment by yininge** [comment]
I'll do this and try to keep the style consistent.

**Comment by jenweber** [comment]
Closed with #3222
