### ISSUE TITLE
Add a section on the deprecations app to the ember learn page

### ISSUE THREAD

**Issue by toddjordan** [emberjs/website#3235]
Currently the page has a section highlighting various internal ember apps so people can browse the source to see ember in action. This is also a good place to see what ember apps we have if people want to contribute.  Recently we've release the deprecations app at https://emberjs.com/deprecations and it uses some interesting technologies such as prember and json static site generator.  

@serenaf or @mansona can provide a couple of bullet points to the more interesting aspects of the app.

The file to update is data/showcase.yml.  Just fool the pattern set by the others.  Name the screenshot showcase-deprecations.png and follow the image guidelines listed in showcase.yml.

**Comment by jenweber** [comment]
Closed by #3661 and #3299. Thanks!
