### ISSUE TITLE
'Symbol' is undefined error on IE11 (Windows 7)

### ISSUE THREAD

**Issue by miketeo** [emberjs/website#3253]
When viewing https://www.emberjs.com/builds/release/ on IE11 on Windows 7 machine, the page appears to hang with the loading animation. On the developer tools, I can see the following error.

![error](https://user-images.githubusercontent.com/6134522/38162024-79acfae0-350c-11e8-8625-dced2388c9e4.png)

On API pages, a "whoops" page is shown with the error on the console.

![error2](https://user-images.githubusercontent.com/6134522/38162043-d7517da6-350c-11e8-89d8-7682d71bb683.png)

**Comment by jenweber** [comment]
Yikes, thanks a bunch for reporting it, @miketeo 

Work to be tracked in https://github.com/ember-learn/builds/issues/82. Leaving this open until that issue is closed, in case other people come here to report a problem.

**Comment by WebStew** [comment]
I'm having similar problems on IE11 Windows 7 on the API pages.

![ie11-api](https://user-images.githubusercontent.com/1636565/38298204-47e05412-37e6-11e8-9aad-291482ce0b91.png)

**Comment by jenweber** [comment]
Closed with https://github.com/ember-learn/builds/pull/83

Thank you @miketeo for your help reporting and documenting this! I'm sure this affected other people too. Should be fixed now.
