### ISSUE TITLE
Hover issue social links in footer

### ISSUE THREAD

**Issue by anpenava** [emberjs/website#3273]
I think text decoration just needs to be none, I can make PR tonight if nobody have time for styling issues :D

`.footer .footer-social a:hover {
  text-decoration: none;
}`

**Comment by MelSumner** [comment]
@anpenava can you tell me what page you're seeing this issue on? I thought we already fixed it. Thanks! :+1:

**Comment by anpenava** [comment]
I am using most recent google chrome browser on macbook, I added screenshot.
[Link to screenshot](https://ibb.co/hGqLz7)

**Comment by anpenava** [comment]
@MelSumner sorry on late response, now I can see bug only on this page 
 https://guides.emberjs.com/v3.1.0/

**Comment by Willibaur** [comment]
@MelSumner  :point_up:  PR is in place for solving this issue

**Comment by jenweber** [comment]
Closed, addressed by PRs to ember-styleguide. Thanks everyone for reporting!
