### ISSUE TITLE
Add mission statement to learning team

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3288]
“Empowering Ember users to learn, build, and teach.” 

Integrate this into the description of the learning team on the /team page. Content may need to be edited for brevity.

**Comment by kamizen** [comment]
@MelSumner, I've submitted a simple pull request at https://github.com/emberjs/website/pull/3298.

**Comment by Willibaur** [comment]
@MelSumner Not sure if this PR has been updated but I could help if you want?

**Comment by MelSumner** [comment]
@Willibaur thanks for checking! That would be great- can you look at PR 3298 and help it over the finish line? Thank you!! :+1:

**Comment by localpcguy** [comment]
this looks like it was fixed by #3354

**Comment by acorncom** [comment]
Thanks @localpcguy it was
