### ISSUE TITLE
Ember.String namespace has TODO 

### ISSUE THREAD

**Issue by efx** [emberjs/website#3338]
On  https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-string-namespace I see:
<img width="719" alt="screen shot 2018-05-11 at 07 19 57" src="https://user-images.githubusercontent.com/472721/39922150-bff334ca-54eb-11e8-88ab-ad51d0b78882.png">

I would think `TODO: update to` should be removed?

**Comment by locks** [comment]
Moved to depreciations app.
