### ISSUE TITLE
Uncaught TypeError: Cannot read property 'currentRouteName' of undefined in Builds section

### ISSUE THREAD

**Issue by bogdansireteanu** [emberjs/website#3348]
When accessing [https://www.emberjs.com/builds/](https://www.emberjs.com/builds/), the page does not load. There is an error in console: 

> Uncaught TypeError: Cannot read property 'currentRouteName' of undefined

**Comment by kennethlarsen** [comment]
@bogdansireteanu Are you still experiencing this? It seems to work now.

**Comment by bogdansireteanu** [comment]
@kennethlarsen Everything is looking fine now.
