### ISSUE TITLE
ember-data docs "Defined In" point to Travis build

### ISSUE THREAD

**Issue by ryanrishi** [emberjs/website#3358]
The "Defined In" section of all the DS classes point to the built project on Travis instead of the source code: https://emberjs.com/api/ember-data/release/classes/DS . These links end up 404ing since they don't exist on Github.

![screen shot 2018-05-23 at 1 26 38 pm](https://user-images.githubusercontent.com/5033038/40449313-fe02165a-5e8c-11e8-9d34-102d848390b9.png)

**Comment by sivakumar-kailasam** [comment]
Thanks for reporting this. It's tracked at https://github.com/ember-learn/ember-api-docs/issues/505 and should be fixed soon

**Comment by ryanrishi** [comment]
Ah thanks, didn't think to look there.

**Comment by sivakumar-kailasam** [comment]
@ryanrishi no worries. Feel free to report issues and provide feedback anytime you come across something that could be better
