### ISSUE TITLE
Update copy for sponsors page, layout updates

### ISSUE THREAD

**Issue by localpcguy** [emberjs/website#3378]
Copy is dated on the Sponsors page. Also the layout of the sponsors is not organized.

## Current Behavior
The text at the top of the Sponsors page says 
> It's still early in the life of the project, but we couldn't have gotten ...

## Expected Behavior
It should not say it's early in the life of the project 

## Possible Solution
Update the copy, suggested:
> Since it's beginnings in 2011, Ember has only gotten as far as we have due to the support—both financial and technical—of the following companies: 

Organize the sponsors into a more grid-like layout and normalize the sizing of the logo images

**Comment by localpcguy** [comment]
@MelSumner I took a stab at this, and will put a PR in shortly with both the copy updates and the pill box border styles and a grid-style layout

**Comment by localpcguy** [comment]
Just noticed there is already an issue and PR fix in for this: #3376. Feel free to check out the updates I made and let me know if you are interested in the PR. Otherwise feel free to close this. Should have searched better.

**Comment by MelSumner** [comment]
@localpcguy I like yours better :+1:
