### ISSUE TITLE
"Defined In" section of DS api is going 404 

### ISSUE THREAD

**Issue by abdullah2891** [emberjs/website#3382]
## Current Behavior

Lot of the "Defined in" links in version 3.01 is going o 404 page  

## Expected Behavior

It should go to the definition of the code 

## Steps to Reproduce

1. Go to Sample link  [Adapter Documentation](https://www.emberjs.com/api/ember-data/3.1/classes/DS.Adapter/methods?show=inherited%2Cprotected%2Cprivate%2Cdeprecated) 
2. Go to one of the documentation for example "createRecord"  
3. Click on the link "Defined In" link . it is going to 404 
![image](https://user-images.githubusercontent.com/6827586/40932516-9376fbec-67fc-11e8-8f25-16b9539bf169.png)
4. This is happening in most of the link i tested such as DS.belongsToReference . I could not make any other link to work :(

## Environment

Chrome

**Comment by abdullah2891** [comment]
Addendum 
does the check boxes in the Index works ? I change them but they don't seem to work

**Comment by kennethlarsen** [comment]
Hi @abdullah2891 - thanks for submitting this issue. It looks like it now works again ✨ 

Closing the issue. Feel free to re-open if you still face the issue.
