### ISSUE TITLE
Need design for "NOTE:"/tip/warning blocks in docs

### ISSUE THREAD

**Issue by machty** [emberjs/website#339]
The unstyled "NOTE:"s are looking pretty ugly, would be nice to have a stylized well, perhaps with progressive degrees of "intensity".

Problem:

![Screen Shot 2013-02-24 at 2 19 43 PM](https://f.cloud.github.com/assets/81818/189890/30d52880-7eb7-11e2-9d09-1cd0b511e193.png)

**Comment by trek** [comment]
NOTE's in general are bad and should simply be removed. We'll get to this in an audit for 1.11
