### ISSUE TITLE
Broken routing guide at EmberRouter class documentation

### ISSUE THREAD

**Issue by jithin1987** [emberjs/website#3411]
## Current Behavior
Invalid link to routing guide from `EmberRouter` description.

## Expected Behavior

`routing guide` link should take me to Routing Guide documentation web page
## Steps to Reproduce

1. Visit https://www.emberjs.com/api/ember/release/classes/EmberRouter
2. See the text `The EmberRouter class manages the application state and URLs. Refer to the **routing guide** for documentation.`
3. Click on `routing guide`
4. It takes user to https://emberjs.com/guides/routing/ which is broken.

## Environment

Firefox 60

## Possible Solution

Fix the link to documentation.

## Sources

1.  https://www.emberjs.com/api/ember/release/classes/EmberRouter
1. https://emberjs.com/guides/routing/

**Comment by kennethlarsen** [comment]
This seems to have been fixed in the source (https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js#L30) but not live yet.

**Comment by kennethlarsen** [comment]
It seems this is live now and fixed. Closing the issue.
