### ISSUE TITLE
Quick start link on builds page leads to crashed site

### ISSUE THREAD

**Issue by bracke** [emberjs/website#3462]
Hi Everybody

## Current Behavior
The "Getting Started Guide" button on the builds page (https://emberjs.com/builds/) leads to empty white page with javascript errors.

## Expected Behavior
It should show me the Quick Guide.

## Steps to Reproduce

1. Goto https://emberjs.com/builds/
2. Click on "Getting Started Guide" button
3. A white page is shown with javascript errors in the console.

## Environment
macOS High Sierra, Safari 11.1.1, Chrome Version 67.0.3396.99 (Official Build) (64-bit)

## Sources
![untitled](https://user-images.githubusercontent.com/627383/42898577-d01c202e-8ac3-11e8-989e-d5c2aa58981d.png)

**Comment by amyrlam** [comment]
Made https://github.com/ember-learn/builds/pull/118 to fix, let me know if any feedback!
