### ISSUE TITLE
Missing API documentation for Controllers on 3.3

### ISSUE THREAD

**Issue by skaterdav85** [emberjs/website#3470]
![screenshot 2018-07-22 23 38 07](https://user-images.githubusercontent.com/687449/43061205-2aecfff8-8e09-11e8-8aa1-39e440e3e4ee.png)

**Comment by lancedikson** [comment]
I'd even say a half of all the packages are missing 🤔

**Comment by rwjblue** [comment]
Yep, this is something we are working on.

@toddjordan already fixed the main issue in https://github.com/emberjs/ember.js/pull/16836.

**Comment by btecu** [comment]
This can be clossed

**Comment by acorncom** [comment]
Thanks @btecu
