### ISSUE TITLE
DS.EmbeddedRecordsMixin "defining relationships" link in API documentation leads to 404 page

### ISSUE THREAD

**Issue by jad359** [emberjs/website#3504]
## Current Behavior
On https://emberjs.com/api/ember-data/release/classes/DS.EmbeddedRecordsMixin, clicking the link:

> See the [defining relationships](https://emberjs.com/guides/models/defining-models/#toc_defining-relationships) section of the Defining Models guide page.

leads to a 404 page.

## Expected Behavior
The link should likely be changed to https://guides.emberjs.com/release/models/relationships/ (or equivalent)

**Comment by kennethlarsen** [comment]
Thanks for submitting this issue @jad359 ✨ 

It looks like my former fix no longer works 🤔 

The link has to be changed to https://guides.emberjs.com/release/models/relationships/ in https://github.com/emberjs/data/blob/master/addon/serializers/embedded-records-mixin.js#L80
