### ISSUE TITLE
Home page document title

### ISSUE THREAD

**Issue by camskene** [emberjs/website#3521]
The home page title is currently 'Ember.js - Homepage'. 

Perhaps the word 'Homepage' could be replaced with a short description?

It would be more descriptive for search results?

![image](https://user-images.githubusercontent.com/507499/44533229-0fe06d80-a6c3-11e8-85fc-e189516d3d8d.png)

**Comment by MelSumner** [comment]
Resolved with the merge of #3591 :+1:
