### ISSUE TITLE
Homepage search redirects to non-latest version of Ember API docs

### ISSUE THREAD

**Issue by patocallaghan** [emberjs/website#3528]
## Current Behavior
Searching the API from the homepage's search box results in you being redirected to the 3.1 API docs

## Expected Behavior
I'd expect the search results to redirect to the latest version of the API docs

## Steps to Reproduce
1. Go to https://www.emberjs.com/
2. Type "Service" into the search input
3. Select the top "Services" result from the dropdown
4. The page redirects to https://guides.emberjs.com/v3.1.0/applications/services/#ember315515

## Environment
Chrome 68, macOS High Sierra

I was directed to open an issue from https://github.com/emberjs/website/issues/3296#issuecomment-415505221

**Comment by acorncom** [comment]
Thanks @patocallaghan. We've been busy reworking the guides app and missed one line that tied search to the latest version of the guides here (https://github.com/emberjs/website/blob/master/lib/versions.rb#L13). Should have a fix out for that shortly ...
