### ISSUE TITLE
"Defined In" links for DS.Model v3.4 are broken

### ISSUE THREAD

**Issue by luketheobscure** [emberjs/website#3564]
## Current Behavior
Clicking the link on any of the "Defined In" sections for DS.Model go to 404's. [Here's what 'belongsTo' is trying to link](https://github.com/emberjs/data/tree/v3.4.2/addon/-private/system/model/model.js#L854) to as an example. The same link for v3.3 is working.

## Expected Behavior
Clicking the link should go the correct definition.

## Steps to Reproduce
1. Click a "Defined In" link anywhere on https://emberjs.com/api/ember-data/3.4/classes/DS.Model/methods
2. ???
3. Profit!

## Environment
MacOS, Firefox 62

## Possible Solution
It appears that the correct location for the model code is now https://github.com/emberjs/data/blob/v3.4.2/addon/-record-data-private/system/model/model.js

**Comment by kennethlarsen** [comment]
Hi @luketheobscure - thanks for submitting this issue!

It looks like it works again. ✨
