### ISSUE TITLE
Discord Links on Community Page

### ISSUE THREAD

**Issue by MelSumner** [emberjs/website#3593]
## Current Behavior
![image](https://user-images.githubusercontent.com/4587451/46349569-03cbc200-c618-11e8-8e1b-b8c3f9498489.png)

## Expected Behavior
Links should be displayed correctly

## Solution
Use HTML instead of Markdown.

**Comment by ftonato** [comment]
I'll look into it!

**Comment by ftonato** [comment]
@MelSumner I sent a [PR](https://github.com/emberjs/website/pull/3595) with possible solution :v:
