### ISSUE TITLE
Apple uses Ember!

### ISSUE THREAD

**Issue by arch-lord** [emberjs/website#3626]
Apple uses Ember on parts of their website. I have already been able to find it in the source code of artist pages like [this](https://itunes.apple.com/artist/xeborch/1438352920).

I suggest updating the carousel on the home page to include Apple's logo, if that's possible.

**Comment by sivakumar-kailasam** [comment]
Thanks for opening this issue. We've noticed it over the years too 🙂

 We'd love for someone from Apple to open a PR to add themselves to the list of users. The guidelines can be found on https://emberjs.com/ember-users/. 

We can't add them ourselves because of legal reasons.
