### ISSUE TITLE
Docs for Route don't open on 3.6

### ISSUE THREAD

**Issue by mariogintili** [emberjs/website#3762]
A picture is worth more than a thousand words 😄 

![image](https://user-images.githubusercontent.com/3522106/50825555-367d0900-1331-11e9-8683-b1a912163e26.png)

**Comment by mansona** [comment]
@mariogintili thanks for the issue report! Any chance you can open it in https://github.com/ember-learn/ember-api-docs? If you open it there then the people that can help fix it are more likely to notice the issue and respond (because they may not be monitoring this repo) 👍

**Comment by mariogintili** [comment]
https://github.com/ember-learn/ember-api-docs/issues/588

**Comment by mansona** [comment]
thanks @mariogintili you're a ⭐️
