### ISSUE TITLE
Guides - EmberData will cause an error in the browser.

### ISSUE THREAD

**Issue by ddewaele** [emberjs/website#629]
When following this guide http://emberjs.com/guides/getting-started/adding-a-route-and-template/

People will see the following error :

```
Assertion failed: You included Ember Data but didn't define Todos.Store ember-1.0.0-rc.7.js:364
Uncaught Error: Attempting to inject an unknown injection: `store:main` 
```

Related to the following :

https://github.com/emberjs/data/issues/1084

Either we shouldn't include EmberData here, or we should already define a Store in the application.js

```
Todos.Store = DS.Store.extend();
```

**Comment by darylhemeon** [comment]
Thanks everybody for the super helpful comments - I got this step working today.  Word.

**Comment by pavell-hyuna** [comment]
Thank you @jaromirmuller
